import type { Q } from "../_lib/qbank";

export const PHYSICAL_SET_6: Q[] = [
  {
    stem: "For a reaction with rate law rate = k[A][B]², what is the overall order?",
    topic: "Rate Laws & Order",
    explanation: "The overall order is the sum of the exponents in the rate law: 1 + 2 = 3, so the reaction is third order overall. It is first order in A and second order in B.",
    choices: [
      { text: "third order", isCorrect: true },
      { text: "second order" },
      { text: "first order" },
      { text: "fourth order" },
    ],
  },
  {
    stem: "The rate constant k of a reaction depends on which variable?",
    topic: "Rate Laws & Order",
    explanation: "The rate constant depends on temperature (and on any catalyst) through the Arrhenius equation, but not on the reactant concentrations. Concentrations enter the rate only through the rate law.",
    choices: [
      { text: "temperature", isCorrect: true },
      { text: "reactant concentration" },
      { text: "total pressure at fixed T" },
      { text: "the reaction vessel size" },
    ],
  },
  {
    stem: "For a reaction that is zero order in A, the rate is",
    topic: "Rate Laws & Order",
    explanation: "A zero-order rate law is rate = k[A]⁰ = k, so the rate is constant and independent of [A]. Such behavior often arises when a surface or enzyme is saturated.",
    choices: [
      { text: "independent of [A] entirely", isCorrect: true },
      { text: "directly proportional to [A]" },
      { text: "proportional to [A]²" },
      { text: "inversely proportional to [A]" },
    ],
  },
  {
    stem: "The units of the rate constant for a first-order reaction are",
    topic: "Rate Laws & Order",
    explanation: "For first order, rate (M/s) = k[A] (M), so k has units of s⁻¹ (per second, i.e. inverse time). The units of k always depend on the overall order.",
    choices: [
      { text: "s⁻¹ (first order)", isCorrect: true },
      { text: "M⁻¹ s⁻¹ (second order)" },
      { text: "M s⁻¹ (unusual case)" },
      { text: "M⁻² s⁻¹ (third order)" },
    ],
  },
  {
    stem: "The units of the rate constant for a second-order reaction (rate = k[A]²) are",
    topic: "Rate Laws & Order",
    explanation: "For second order, rate (M/s) = k[A]² (M²), so k has units M⁻¹ s⁻¹ = L mol⁻¹ s⁻¹. Each increase in order lowers the concentration power in k by one.",
    choices: [
      { text: "M⁻¹ s⁻¹", isCorrect: true },
      { text: "s⁻¹" },
      { text: "M s⁻¹" },
      { text: "M⁻² s⁻²" },
    ],
  },
  {
    stem: "The order of a reaction with respect to a reactant is determined by",
    topic: "Rate Laws & Order",
    explanation: "Reaction order is found experimentally (e.g. from initial-rate or integrated-rate data); it cannot be read off the balanced equation unless the reaction is a single elementary step.",
    choices: [
      { text: "experiment, not the balanced equation", isCorrect: true },
      { text: "the stoichiometric coefficients directly" },
      { text: "the sign of the enthalpy change" },
      { text: "the magnitude of the rate constant" },
    ],
  },
  {
    stem: "In the method of initial rates, doubling [A] doubles the rate while [B] is held fixed. The order in A is",
    topic: "Rate Laws & Order",
    explanation: "If rate → [A]m, then doubling [A] multiplies the rate by 2m. A doubling of rate means 2m = 2, so m = 1: the reaction is first order in A.",
    choices: [
      { text: "first order", isCorrect: true },
      { text: "zero order" },
      { text: "second order" },
      { text: "half order" },
    ],
  },
  {
    stem: "In an initial-rate study, doubling [A] quadruples the rate. The order in A is",
    topic: "Rate Laws & Order",
    explanation: "A fourfold rate increase on doubling means 2m = 4, so m = 2: the reaction is second order in A. Initial-rate comparisons isolate the order of one reactant at a time.",
    choices: [
      { text: "second order", isCorrect: true },
      { text: "first order" },
      { text: "zero order" },
      { text: "third order" },
    ],
  },
  {
    stem: "The instantaneous rate of a reaction is obtained from a concentration-time curve as",
    topic: "Rate Laws & Order",
    explanation: "The instantaneous rate is the slope of the tangent to the concentration-versus-time curve at a given instant. The average rate uses a finite interval instead.",
    choices: [
      { text: "the slope of the tangent at that instant", isCorrect: true },
      { text: "the total change over the whole run" },
      { text: "the area under the curve" },
      { text: "the value of the rate constant" },
    ],
  },
  {
    stem: "For 2 N₂O₅ → 4 NO₂ + O₂, the rate of formation of NO₂ compared with the rate of consumption of N₂O₅ is",
    topic: "Rate Laws & Order",
    explanation: "Rates are tied by stoichiometry: -(1/2)d[N₂O₅]/dt = (1/4)d[NO₂]/dt. So NO₂ forms twice as fast as N₂O₅ disappears (4 vs 2).",
    choices: [
      { text: "twice as fast", isCorrect: true },
      { text: "half as fast" },
      { text: "equal in magnitude" },
      { text: "four times as fast" },
    ],
  },
  {
    stem: "The integrated rate law for a first-order reaction is",
    topic: "Integrated Rate Laws",
    explanation: "For first order, ln[A] = ln[A]₀ - kt, so a plot of ln[A] versus time is linear with slope -k. Equivalently [A] = [A]₀e⁻kt.",
    choices: [
      { text: "ln[A] = ln[A]₀ - kt", isCorrect: true },
      { text: "[A] = [A]₀ - kt" },
      { text: "1/[A] = 1/[A]₀ + kt" },
      { text: "[A]² = [A]₀ - kt" },
    ],
  },
  {
    stem: "A plot that is linear for a first-order reaction is",
    topic: "Integrated Rate Laws",
    explanation: "First order gives a straight line for ln[A] versus t (slope -k). Zero order is linear in [A] versus t, and second order is linear in 1/[A] versus t.",
    choices: [
      { text: "ln[A] versus time", isCorrect: true },
      { text: "[A] versus time" },
      { text: "1/[A] versus time" },
      { text: "[A]² versus time" },
    ],
  },
  {
    stem: "For a second-order reaction (rate = k[A]²), which plot is linear?",
    topic: "Integrated Rate Laws",
    explanation: "The integrated second-order law is 1/[A] = 1/[A]₀ + kt, so 1/[A] versus t is a straight line with slope +k. This distinguishes it from first- and zero-order kinetics.",
    choices: [
      { text: "1/[A] versus time", isCorrect: true },
      { text: "ln[A] versus time" },
      { text: "[A] versus time" },
      { text: "[A]² versus time" },
    ],
  },
  {
    stem: "For a zero-order reaction, the concentration of reactant decreases",
    topic: "Integrated Rate Laws",
    explanation: "Zero order gives [A] = [A]₀ - kt, a straight line falling at constant rate k until the reactant runs out. The rate does not slow as [A] drops.",
    choices: [
      { text: "linearly with time", isCorrect: true },
      { text: "exponentially with time" },
      { text: "as the reciprocal of time" },
      { text: "as the square root of time" },
    ],
  },
  {
    stem: "The half-life of a first-order reaction is t₁/₂ = 0.693/k. A key feature is that it",
    topic: "Reaction Half-Life",
    explanation: "For first order the half-life is constant, independent of the starting concentration. This constancy is a hallmark of first-order kinetics and underlies radioactive decay.",
    choices: [
      { text: "is independent of the initial concentration", isCorrect: true },
      { text: "increases with initial concentration" },
      { text: "decreases with initial concentration" },
      { text: "depends on the reaction enthalpy" },
    ],
  },
  {
    stem: "For a first-order reaction, after three half-lives the fraction of reactant remaining is",
    topic: "Reaction Half-Life",
    explanation: "Each half-life halves the amount: after 3 half-lives the fraction left is (1/2)³ = 1/8. This geometric decay is characteristic of first-order processes.",
    choices: [
      { text: "1/8", isCorrect: true },
      { text: "1/3" },
      { text: "1/6" },
      { text: "3/4" },
    ],
  },
  {
    stem: "For a second-order reaction, the half-life t₁/₂ = 1/(k[A]₀)",
    topic: "Reaction Half-Life",
    explanation: "The second-order half-life is inversely proportional to the initial concentration, so it lengthens as the reaction proceeds and [A] falls. This contrasts with the constant first-order half-life.",
    choices: [
      { text: "increases as the reaction proceeds", isCorrect: true },
      { text: "stays constant throughout" },
      { text: "decreases as the reaction proceeds" },
      { text: "is independent of concentration" },
    ],
  },
  {
    stem: "A radioactive isotope decays by first-order kinetics with a half-life of 10 years. After 30 years, the fraction remaining is",
    topic: "Reaction Half-Life",
    explanation: "Thirty years is three half-lives, so the fraction is (1/2)³ = 1/8 = 0.125. Radioactive decay is a standard first-order process with a concentration-independent half-life.",
    choices: [
      { text: "1/8", isCorrect: true },
      { text: "1/3" },
      { text: "1/2" },
      { text: "1/30" },
    ],
  },
  {
    stem: "If a first-order reaction has k = 0.0693 s⁻¹, its half-life is approximately",
    topic: "Reaction Half-Life",
    explanation: "t₁/₂ = 0.693/k = 0.693/0.0693 → 10 s. The simple relation between k and half-life makes first-order kinetics especially convenient to analyze.",
    choices: [
      { text: "about 10 s", isCorrect: true },
      { text: "about 1 s" },
      { text: "about 100 s" },
      { text: "about 0.1 s" },
    ],
  },
  {
    stem: "Which quantity is constant over time for a first-order reaction as it proceeds?",
    topic: "Integrated Rate Laws",
    explanation: "The half-life (and the rate constant k) are constant for first order. The rate itself and [A] both fall with time, so they are not constant.",
    choices: [
      { text: "the half-life", isCorrect: true },
      { text: "the reaction rate" },
      { text: "the reactant concentration" },
      { text: "the total pressure" },
    ],
  },
  {
    stem: "The Arrhenius equation k = A e⁻Ea/RT shows that the rate constant increases when",
    topic: "Temperature & Arrhenius",
    explanation: "Raising the temperature or lowering the activation energy makes the exponent -Ea/RT less negative, so the exponential factor and k increase. A is the pre-exponential (frequency) factor.",
    choices: [
      { text: "temperature increases", isCorrect: true },
      { text: "activation energy increases" },
      { text: "temperature decreases" },
      { text: "the pre-exponential factor is set to zero" },
    ],
  },
  {
    stem: "In the Arrhenius equation, the activation energy Ea represents",
    topic: "Temperature & Arrhenius",
    explanation: "Ea is the minimum energy barrier that colliding molecules must overcome to react. A larger barrier means a smaller fraction of collisions succeed, so k is smaller at a given temperature.",
    choices: [
      { text: "the energy barrier to reaction", isCorrect: true },
      { text: "the energy released by the reaction" },
      { text: "the average kinetic energy of molecules" },
      { text: "the bond energy of the products" },
    ],
  },
  {
    stem: "A plot of ln k versus 1/T (an Arrhenius plot) is a straight line with slope",
    topic: "Temperature & Arrhenius",
    explanation: "Taking logs of the Arrhenius equation gives ln k = ln A - Ea/(RT), so ln k versus 1/T is linear with slope -Ea/R. The intercept gives ln A.",
    choices: [
      { text: "-Ea/R", isCorrect: true },
      { text: "+Ea/R" },
      { text: "-EaR" },
      { text: "+ln A" },
    ],
  },
  {
    stem: "The pre-exponential factor A in the Arrhenius equation is related to",
    topic: "Temperature & Arrhenius",
    explanation: "A reflects the frequency of collisions and the fraction with correct orientation (the steric factor). The exponential term then supplies the fraction of collisions with enough energy.",
    choices: [
      { text: "collision frequency and orientation", isCorrect: true },
      { text: "the height of the energy barrier" },
      { text: "the overall enthalpy change" },
      { text: "the equilibrium constant of the reaction" },
    ],
  },
  {
    stem: "For many reactions near room temperature, a 10 °C rise roughly",
    topic: "Temperature & Arrhenius",
    explanation: "A common rule of thumb is that the rate about doubles for each 10 °C rise, reflecting the steep exponential dependence of k on temperature in the Arrhenius law. The exact factor depends on Ea.",
    choices: [
      { text: "doubles the reaction rate", isCorrect: true },
      { text: "halves the reaction rate" },
      { text: "has no effect on the rate" },
      { text: "increases the rate tenfold" },
    ],
  },
  {
    stem: "A reaction with a higher activation energy is, all else equal,",
    topic: "Temperature & Arrhenius",
    explanation: "A higher Ea means fewer molecules have enough energy to react at a given temperature, so the reaction is slower and its rate is more sensitive to temperature changes.",
    choices: [
      { text: "more sensitive to temperature changes", isCorrect: true },
      { text: "less sensitive to temperature changes" },
      { text: "independent of temperature" },
      { text: "always exothermic" },
    ],
  },
  {
    stem: "The two-point form ln(k₂/k₁) = -(Ea/R)(1/T₂ - 1/T₁) is used to",
    topic: "Temperature & Arrhenius",
    explanation: "It lets you find the activation energy from rate constants at two temperatures, or predict k at a new temperature. It is the integrated Arrhenius relation between two states.",
    choices: [
      { text: "find Ea from k at two temperatures", isCorrect: true },
      { text: "find the equilibrium constant K" },
      { text: "find the reaction order" },
      { text: "find the pre-exponential factor from K" },
    ],
  },
  {
    stem: "On a reaction energy profile, the activation energy is the height from",
    topic: "Temperature & Arrhenius",
    explanation: "Ea is measured from the reactants up to the transition state (the peak of the barrier). The overall ΔH is the difference between product and reactant energies, a separate quantity.",
    choices: [
      { text: "reactants up to the transition state", isCorrect: true },
      { text: "products up to the transition state" },
      { text: "reactants down to the products" },
      { text: "the transition state down to products" },
    ],
  },
  {
    stem: "The molecularity of an elementary reaction is",
    topic: "Reaction Mechanisms",
    explanation: "Molecularity is the number of species that come together in a single elementary step (unimolecular, bimolecular, or termolecular). It applies only to elementary steps, unlike order, which is empirical.",
    choices: [
      { text: "the number of species in that elementary step", isCorrect: true },
      { text: "the sum of the stoichiometric coefficients" },
      { text: "the experimentally measured order" },
      { text: "the number of steps in the mechanism" },
    ],
  },
  {
    stem: "For an elementary step, the rate law",
    topic: "Reaction Mechanisms",
    explanation: "For an elementary step the rate law comes straight from its molecularity, so the exponents equal the stoichiometric coefficients of that step. This is not generally true for overall reactions.",
    choices: [
      { text: "follows directly from its molecularity", isCorrect: true },
      { text: "must be determined only by experiment" },
      { text: "is always first order overall" },
      { text: "cannot be written at all" },
    ],
  },
  {
    stem: "In a multistep mechanism, the overall rate is governed by",
    topic: "Reaction Mechanisms",
    explanation: "The slowest elementary step, the rate-determining step, controls the overall rate much as the narrowest section of a pipe limits flow. Faster steps do not limit the overall rate.",
    choices: [
      { text: "the slowest (rate-determining) step", isCorrect: true },
      { text: "the fastest elementary step" },
      { text: "the first step, whatever its speed" },
      { text: "the step with the most products" },
    ],
  },
  {
    stem: "A reaction intermediate in a mechanism is a species that is",
    topic: "Reaction Mechanisms",
    explanation: "An intermediate is produced in one step and consumed in a later step, so it does not appear in the overall balanced equation. A catalyst, by contrast, is consumed early and regenerated.",
    choices: [
      { text: "formed in one step and consumed in another", isCorrect: true },
      { text: "present in the overall balanced equation" },
      { text: "added at the start and never used up" },
      { text: "the same as the transition state" },
    ],
  },
  {
    stem: "A proposed mechanism is acceptable only if it",
    topic: "Reaction Mechanisms",
    explanation: "A valid mechanism must add up to the overall reaction and be consistent with the experimental rate law. Agreement with the rate law supports, but never absolutely proves, a mechanism.",
    choices: [
      { text: "matches the observed rate law", isCorrect: true },
      { text: "has exactly two elementary steps" },
      { text: "contains no reaction intermediates" },
      { text: "makes every step bimolecular" },
    ],
  },
  {
    stem: "If the first step of a two-step mechanism is slow and rate-determining, the predicted rate law is",
    topic: "Reaction Mechanisms",
    explanation: "When the first step is rate-determining, the overall rate law is just the first elementary step's rate law, written from its molecularity. Later fast steps do not enter the rate law.",
    choices: [
      { text: "the rate law of that first elementary step", isCorrect: true },
      { text: "the rate law of the fast second step" },
      { text: "the product of both step rate laws" },
      { text: "always second order overall" },
    ],
  },
  {
    stem: "The transition state (activated complex) of a reaction is",
    topic: "Reaction Mechanisms",
    explanation: "The transition state is the highest-energy configuration along the reaction path, in which bonds are partly broken and partly formed. Unlike an intermediate, it cannot be isolated.",
    choices: [
      { text: "the highest-energy point on the path", isCorrect: true },
      { text: "a stable, isolable intermediate" },
      { text: "the lowest-energy product state" },
      { text: "identical to the reactants" },
    ],
  },
  {
    stem: "In the steady-state approximation, the concentration of a reactive intermediate is taken to be",
    topic: "Reaction Mechanisms",
    explanation: "The steady-state approximation sets the net rate of change of a reactive intermediate to zero (its formation and consumption rates are balanced), simplifying the derivation of the overall rate law.",
    choices: [
      { text: "nearly constant (net rate of change ≈ 0)", isCorrect: true },
      { text: "equal to the reactant concentration" },
      { text: "increasing linearly with time" },
      { text: "zero at all times" },
    ],
  },
  {
    stem: "For the mechanism where a fast equilibrium precedes a slow step, the intermediate's concentration is expressed using",
    topic: "Reaction Mechanisms",
    explanation: "The pre-equilibrium approximation uses the equilibrium constant of the fast first step to express the intermediate in terms of reactants, which is then substituted into the slow-step rate law.",
    choices: [
      { text: "the equilibrium constant of the fast step", isCorrect: true },
      { text: "the activation energy of the slow step" },
      { text: "the overall reaction enthalpy" },
      { text: "the pre-exponential factor A" },
    ],
  },
  {
    stem: "A termolecular elementary step is rare because",
    topic: "Reaction Mechanisms",
    explanation: "A termolecular step needs three particles to collide simultaneously with the right energy and orientation, which is statistically unlikely. Most mechanisms are built from unimolecular and bimolecular steps.",
    choices: [
      { text: "simultaneous three-body collisions are unlikely", isCorrect: true },
      { text: "three-body collisions violate energy conservation" },
      { text: "such steps must always be exothermic" },
      { text: "they cannot have a rate constant" },
    ],
  },
  {
    stem: "According to collision theory, a reaction occurs when molecules collide with",
    topic: "Theories of Reaction Rates",
    explanation: "Collision theory requires colliding molecules to have at least the activation energy AND the correct mutual orientation. Most collisions fail one or both conditions, so only a fraction lead to reaction.",
    choices: [
      { text: "sufficient energy and proper orientation", isCorrect: true },
      { text: "any energy, regardless of orientation" },
      { text: "proper orientation but any low energy" },
      { text: "energy equal to the bond dissociation energy" },
    ],
  },
  {
    stem: "The steric (orientation) factor in collision theory accounts for the fact that",
    topic: "Theories of Reaction Rates",
    explanation: "Even energetic collisions react only if the molecules are oriented so the reacting groups meet; the steric factor (usually < 1) corrects the collision frequency for this geometric requirement.",
    choices: [
      { text: "molecules must be aligned to react", isCorrect: true },
      { text: "collisions transfer no energy" },
      { text: "all collisions lead to reaction" },
      { text: "temperature has no effect on rate" },
    ],
  },
  {
    stem: "Transition-state theory pictures reactants passing through a high-energy",
    topic: "Theories of Reaction Rates",
    explanation: "Transition-state theory treats reactants as forming an activated complex at the top of the barrier, which then decomposes to products. The theory relates the rate to the properties of this complex.",
    choices: [
      { text: "activated complex before forming products", isCorrect: true },
      { text: "stable intermediate that can be bottled" },
      { text: "catalyst that lowers the barrier" },
      { text: "product molecule directly, with no barrier" },
    ],
  },
  {
    stem: "A catalyst increases the rate of a reaction by",
    topic: "Catalysis",
    explanation: "A catalyst provides an alternative pathway with a lower activation energy, so a larger fraction of collisions succeed. It does not change ΔH, ΔG, or the equilibrium position.",
    choices: [
      { text: "providing a lower-activation-energy path", isCorrect: true },
      { text: "increasing the activation energy" },
      { text: "raising the temperature of the system" },
      { text: "shifting the equilibrium toward products" },
    ],
  },
  {
    stem: "A catalyst affects which of the following?",
    topic: "Catalysis",
    explanation: "A catalyst changes the kinetics (rate) by lowering Ea, but leaves the thermodynamics unchanged: ΔH, ΔG, K, and the equilibrium position are all the same with or without it.",
    choices: [
      { text: "the rate, not the equilibrium", isCorrect: true },
      { text: "the equilibrium constant K" },
      { text: "the standard reaction enthalpy" },
      { text: "the position of equilibrium" },
    ],
  },
  {
    stem: "A homogeneous catalyst is one that is",
    topic: "Catalysis",
    explanation: "A homogeneous catalyst is in the same phase as the reactants (e.g. a dissolved acid catalyzing a solution reaction). A heterogeneous catalyst is in a different phase, such as a solid catalyzing a gas reaction.",
    choices: [
      { text: "in the same phase as the reactants", isCorrect: true },
      { text: "in a different phase from the reactants" },
      { text: "always a solid surface" },
      { text: "consumed permanently in the reaction" },
    ],
  },
  {
    stem: "In enzyme kinetics, the Michaelis-Menten model predicts that at very high substrate concentration the rate",
    topic: "Enzyme Kinetics",
    explanation: "When substrate saturates the enzyme, essentially all active sites are occupied, so the rate approaches its maximum Vmax and becomes independent of substrate (zero order in substrate).",
    choices: [
      { text: "approaches a maximum value Vmax", isCorrect: true },
      { text: "increases without any limit" },
      { text: "falls back toward zero" },
      { text: "becomes first order in substrate" },
    ],
  },
  {
    stem: "The Michaelis constant KM of an enzyme equals the substrate concentration at which",
    topic: "Enzyme Kinetics",
    explanation: "KM is the substrate concentration giving half the maximum rate (Vmax/2). A small KM indicates the enzyme reaches half-maximal rate at low substrate, often read as high apparent affinity.",
    choices: [
      { text: "the rate is half of Vmax", isCorrect: true },
      { text: "the rate is exactly Vmax" },
      { text: "the enzyme is fully denatured" },
      { text: "the substrate is completely used up" },
    ],
  },
  {
    stem: "An enzyme lowers the activation energy of a biochemical reaction, which",
    topic: "Enzyme Kinetics",
    explanation: "By lowering Ea, an enzyme speeds both the forward and reverse reactions equally, so it hastens the approach to equilibrium without changing the equilibrium position or ΔG.",
    choices: [
      { text: "speeds forward and reverse alike", isCorrect: true },
      { text: "shifts the equilibrium toward products" },
      { text: "changes the reaction ΔG" },
      { text: "is consumed stoichiometrically" },
    ],
  },
  {
    stem: "A heterogeneous catalyst such as a metal surface typically works by",
    topic: "Catalysis",
    explanation: "Reactants adsorb onto the surface, where bonds weaken and the activation energy is lowered; products then desorb, freeing the site. Surface area and active sites strongly affect the rate.",
    choices: [
      { text: "adsorbing reactants and weakening their bonds", isCorrect: true },
      { text: "dissolving uniformly among the reactants" },
      { text: "raising the temperature of the gas" },
      { text: "being consumed to form the product" },
    ],
  },
  {
    stem: "Poisoning of a catalyst refers to",
    topic: "Catalysis",
    explanation: "A catalyst poison binds strongly to active sites and blocks them, reducing or destroying catalytic activity. This is why catalytic converters can be spoiled by certain impurities.",
    choices: [
      { text: "blocking of active sites by an impurity", isCorrect: true },
      { text: "thermal decomposition of the products" },
      { text: "an increase in catalytic activity" },
      { text: "the catalyst dissolving into solution" },
    ],
  },
  {
    stem: "The rate of a chemical reaction is generally defined as the change in concentration",
    topic: "Rate Laws & Order",
    explanation: "Reaction rate is the change in concentration of a reactant or product per unit time, made positive and normalized by the stoichiometric coefficient. Its usual units are mol L⁻¹ s⁻¹.",
    choices: [
      { text: "of a species per unit time", isCorrect: true },
      { text: "of a species per unit volume" },
      { text: "per unit mass of catalyst" },
      { text: "per unit temperature change" },
    ],
  },
  {
    stem: "For the reaction A → products, the rate is expressed as -d[A]/dt. The negative sign is present because",
    topic: "Rate Laws & Order",
    explanation: "The reactant concentration decreases with time, so d[A]/dt is negative; the minus sign makes the reported rate a positive number. Product rates use +d[P]/dt.",
    choices: [
      { text: "[A] falls, so the rate stays positive", isCorrect: true },
      { text: "the reaction is always exothermic" },
      { text: "concentration can be negative" },
      { text: "time runs backward in kinetics" },
    ],
  },
  {
    stem: "Doubling both [A] and [B] in a reaction with rate = k[A][B] changes the rate by a factor of",
    topic: "Rate Laws & Order",
    explanation: "The rate scales as [A]1[B]1, so doubling each multiplies the rate by 2 · 2 = 4. Rate-law exponents combine multiplicatively when several concentrations change.",
    choices: [
      { text: "4", isCorrect: true },
      { text: "2" },
      { text: "8" },
      { text: "16" },
    ],
  },
  {
    stem: "A reaction is found to be first order in A and zero order in B. Doubling [B] alone will",
    topic: "Rate Laws & Order",
    explanation: "Because the order in B is zero, the rate does not depend on [B], so doubling [B] leaves the rate unchanged. Only changing [A] would alter the rate here.",
    choices: [
      { text: "leave the rate unchanged", isCorrect: true },
      { text: "double the rate" },
      { text: "quadruple the rate" },
      { text: "halve the rate" },
    ],
  },
  {
    stem: "The pseudo-first-order method simplifies rate studies by",
    topic: "Rate Laws & Order",
    explanation: "Holding one reactant in large excess keeps its concentration nearly constant, folding it into the rate constant so the reaction appears first order in the other reactant. This isolates one order at a time.",
    choices: [
      { text: "keeping one reactant in large excess", isCorrect: true },
      { text: "running the reaction at 0 K" },
      { text: "removing the catalyst entirely" },
      { text: "measuring only the final concentration" },
    ],
  },
  {
    stem: "For a first-order reaction with k = 0.10 s⁻¹, roughly how long until 50 percent of A remains?",
    topic: "Reaction Half-Life",
    explanation: "The half-life is t₁/₂ = 0.693/k = 0.693/0.10 → 6.9 s, the time for [A] to fall to 50 percent. This value is independent of the starting concentration.",
    choices: [
      { text: "about 6.9 s", isCorrect: true },
      { text: "about 0.69 s" },
      { text: "about 69 s" },
      { text: "about 10 s" },
    ],
  },
  {
    stem: "On a reaction coordinate diagram, ΔH for the reaction is given by",
    topic: "Temperature & Arrhenius",
    explanation: "The reaction enthalpy is the energy difference between products and reactants (Eproducts - Ereactants). It is unrelated to the barrier height, which is the activation energy from reactants to the transition state.",
    choices: [
      { text: "the products' energy minus the reactants' energy", isCorrect: true },
      { text: "the height of the barrier above reactants" },
      { text: "the height of the barrier above products" },
      { text: "the energy of the transition state alone" },
    ],
  },
  {
    stem: "For an exothermic elementary reaction, the activation energy of the reverse reaction is",
    topic: "Temperature & Arrhenius",
    explanation: "For an exothermic step, products lie below reactants, so climbing back to the transition state (the reverse Ea) is larger than the forward Ea; the difference equals |ΔH|.",
    choices: [
      { text: "larger than the forward activation energy", isCorrect: true },
      { text: "smaller than the forward activation energy" },
      { text: "equal to the forward activation energy" },
      { text: "always zero for exothermic steps" },
    ],
  },
  {
    stem: "Which experimental observation most directly gives the activation energy of a reaction?",
    topic: "Temperature & Arrhenius",
    explanation: "Measuring the rate constant at several temperatures and plotting ln k against 1/T yields a slope of -Ea/R, giving the activation energy. A single measurement cannot supply Ea.",
    choices: [
      { text: "the slope of ln k versus 1/T", isCorrect: true },
      { text: "the value of k at one temperature" },
      { text: "the equilibrium constant K" },
      { text: "the sign of the reaction enthalpy" },
    ],
  },
  {
    stem: "For the overall reaction with mechanism steps summing correctly, the sum of the elementary steps must equal",
    topic: "Reaction Mechanisms",
    explanation: "When the elementary steps are added, intermediates cancel and the result must reproduce the overall balanced equation. This is a basic requirement for any proposed mechanism.",
    choices: [
      { text: "the overall balanced equation", isCorrect: true },
      { text: "the rate-determining step alone" },
      { text: "twice the overall reaction" },
      { text: "the fastest step only" },
    ],
  },
  {
    stem: "If experiment gives rate = k[A]² but the balanced equation is 2A + B → products, we conclude that",
    topic: "Reaction Mechanisms",
    explanation: "Because the measured order (2 in A, 0 in B) does not match the stoichiometry, the reaction cannot be a single elementary step; it must proceed by a multistep mechanism whose slow step is second order in A.",
    choices: [
      { text: "the reaction proceeds by more than one step", isCorrect: true },
      { text: "the reaction is a single elementary step" },
      { text: "the rate law was measured incorrectly" },
      { text: "B is a catalyst for the reaction" },
    ],
  },
  {
    stem: "The rate constant of a reaction was found to increase with temperature. This is explained by",
    topic: "Temperature & Arrhenius",
    explanation: "As temperature rises, a larger fraction of molecules have kinetic energy exceeding Ea, so more collisions are effective and k increases, as the Arrhenius exponential predicts.",
    choices: [
      { text: "more molecules exceed the barrier", isCorrect: true },
      { text: "a decrease in the activation energy" },
      { text: "a shift of the equilibrium constant" },
      { text: "a rise in the concentration of reactants" },
    ],
  },
  {
    stem: "A reaction that is zero order overall proceeds at a rate that",
    topic: "Integrated Rate Laws",
    explanation: "A zero-order rate is constant (equal to k) until a reactant is exhausted, regardless of concentration. This is typical when a catalyst or surface is saturated and limits the throughput.",
    choices: [
      { text: "stays constant until reactant runs out", isCorrect: true },
      { text: "continuously decreases with time" },
      { text: "continuously increases with time" },
      { text: "oscillates with concentration" },
    ],
  },
  {
    stem: "The difference between average rate and instantaneous rate is that the instantaneous rate",
    topic: "Rate Laws & Order",
    explanation: "The instantaneous rate applies at a single moment (the tangent slope), whereas the average rate is taken over a finite time interval (a secant slope). They coincide only as the interval shrinks to zero.",
    choices: [
      { text: "applies at a single instant in time", isCorrect: true },
      { text: "is always larger than the average" },
      { text: "is measured over the whole reaction" },
      { text: "ignores the reactant concentrations" },
    ],
  },
  {
    stem: "For a first-order reaction, doubling the initial concentration of reactant changes the half-life",
    topic: "Reaction Half-Life",
    explanation: "The first-order half-life t₁/₂ = 0.693/k does not contain the concentration, so doubling [A]₀ leaves the half-life unchanged. Only second- and zero-order half-lives depend on concentration.",
    choices: [
      { text: "not at all", isCorrect: true },
      { text: "by doubling it" },
      { text: "by halving it" },
      { text: "by quadrupling it" },
    ],
  },
  {
    stem: "Which statement correctly relates molecularity and order?",
    topic: "Reaction Mechanisms",
    explanation: "Molecularity is a theoretical count for a single elementary step and is always a small whole number; order is an empirical quantity for the overall reaction and can be fractional or zero. They coincide only for elementary steps.",
    choices: [
      { text: "molecularity is theory; order is measured", isCorrect: true },
      { text: "they are always numerically the same value" },
      { text: "order applies only to elementary steps" },
      { text: "molecularity can be fractional" },
    ],
  },
  {
    stem: "An elementary unimolecular step A → products has the rate law",
    topic: "Reaction Mechanisms",
    explanation: "A unimolecular elementary step is first order in its single reactant: rate = k[A]. The molecularity (one) directly sets the order for an elementary step.",
    choices: [
      { text: "rate = k[A]", isCorrect: true },
      { text: "rate = k[A]²" },
      { text: "rate = k (zero order)" },
      { text: "rate = k[A][B]" },
    ],
  },
  {
    stem: "The rate law of a reaction can be established by",
    topic: "Rate Laws & Order",
    explanation: "Rate laws are found empirically, for example by the initial-rates method or by fitting integrated-rate plots. The balanced equation alone cannot supply the orders except for elementary steps.",
    choices: [
      { text: "measuring how rate varies with concentration", isCorrect: true },
      { text: "reading exponents off the balanced equation" },
      { text: "calculating the reaction enthalpy" },
      { text: "measuring the equilibrium constant" },
    ],
  },
  {
    stem: "For rate = k[A]¹/², the reaction is described as",
    topic: "Rate Laws & Order",
    explanation: "The exponent 1/2 makes this a half-order reaction in A. Fractional orders often signal a complex mechanism, such as one involving a chain or a dissociation pre-equilibrium.",
    choices: [
      { text: "half order in A", isCorrect: true },
      { text: "first order in A" },
      { text: "second order in A" },
      { text: "zero order in A" },
    ],
  },
  {
    stem: "When a reaction rate is limited by how fast reactants diffuse together, it is said to be",
    topic: "Theories of Reaction Rates",
    explanation: "A diffusion-controlled reaction proceeds essentially on every encounter, so its rate is set by how fast molecules diffuse together rather than by an energy barrier. Such reactions have very small activation energies.",
    choices: [
      { text: "diffusion-controlled", isCorrect: true },
      { text: "activation-controlled" },
      { text: "zero order in solvent" },
      { text: "thermodynamically controlled" },
    ],
  },
  {
    stem: "In an energy profile with two humps, the higher hump corresponds to",
    topic: "Reaction Mechanisms",
    explanation: "The taller barrier is the transition state of the slower, rate-determining step; the valley between the humps is a reaction intermediate. The overall rate is governed by the higher barrier.",
    choices: [
      { text: "the rate-determining step", isCorrect: true },
      { text: "the fastest step" },
      { text: "a stable product" },
      { text: "the reactant ground state" },
    ],
  },
  {
    stem: "Which change would NOT affect the rate constant k of a given reaction?",
    topic: "Temperature & Arrhenius",
    explanation: "k depends on temperature and on the presence of a catalyst (both change Ea or the path). Changing the concentration of reactants alters the rate but not k itself.",
    choices: [
      { text: "the reactant concentrations", isCorrect: true },
      { text: "raising the temperature" },
      { text: "adding a catalyst" },
      { text: "lowering the temperature" },
    ],
  },
  {
    stem: "For the decomposition following first-order kinetics, a graph of ln[A] versus time gave a slope of -0.020 s⁻¹. The rate constant is",
    topic: "Integrated Rate Laws",
    explanation: "For first order, the slope of ln[A] versus t equals -k, so k = 0.020 s⁻¹. The half-life would then be 0.693/0.020 → 35 s.",
    choices: [
      { text: "0.020 s⁻¹", isCorrect: true },
      { text: "-0.020 s⁻¹" },
      { text: "0.693 s⁻¹" },
      { text: "50 s⁻¹" },
    ],
  },
  {
    stem: "A catalyst appears in the mechanism as a species that is",
    topic: "Catalysis",
    explanation: "A catalyst is consumed in an early step and regenerated in a later one, so it speeds the reaction without being used up overall and does not appear in the net equation. An intermediate is the reverse pattern.",
    choices: [
      { text: "used up early and regenerated later", isCorrect: true },
      { text: "formed early and consumed later" },
      { text: "present in the overall equation" },
      { text: "permanently converted to product" },
    ],
  },
  {
    stem: "The observation that the rate of an enzyme-catalyzed reaction levels off at high substrate is explained by",
    topic: "Enzyme Kinetics",
    explanation: "At high substrate the enzyme's active sites become saturated, so adding more substrate cannot increase the rate; it plateaus at Vmax. This saturation is central to the Michaelis-Menten model.",
    choices: [
      { text: "the active sites become saturated", isCorrect: true },
      { text: "denaturation of all the enzyme" },
      { text: "a rise in the activation energy" },
      { text: "depletion of the catalyst" },
    ],
  },
  {
    stem: "For a reaction with a very small activation energy, the rate is",
    topic: "Temperature & Arrhenius",
    explanation: "A small Ea means almost all collisions have enough energy, so the reaction is fast and only weakly sensitive to temperature. Large-Ea reactions are slow and strongly temperature-dependent.",
    choices: [
      { text: "fast and only weakly temperature-dependent", isCorrect: true },
      { text: "slow and strongly temperature-dependent" },
      { text: "independent of the collision frequency" },
      { text: "always zero order overall" },
    ],
  },
  {
    stem: "The rate of a reaction typically decreases as it proceeds because",
    topic: "Rate Laws & Order",
    explanation: "For most positive-order reactions the reactant concentration falls as products form, and since rate depends on concentration, the rate declines. Zero-order reactions are the exception, staying constant.",
    choices: [
      { text: "reactant concentrations decrease over time", isCorrect: true },
      { text: "the rate constant decreases over time" },
      { text: "the temperature always drops" },
      { text: "the activation energy rises over time" },
    ],
  },
  {
    stem: "Two reactions have the same pre-exponential factor A, but reaction 1 has a larger Ea. At the same temperature, reaction 1 is",
    topic: "Temperature & Arrhenius",
    explanation: "With equal A, the reaction with the larger activation energy has the smaller exponential factor e⁻Ea/RT, so it is slower. Activation energy is the dominant control on relative rates at a fixed temperature.",
    choices: [
      { text: "slower than reaction 2", isCorrect: true },
      { text: "faster than reaction 2" },
      { text: "equal in rate to reaction 2" },
      { text: "independent of temperature" },
    ],
  },
  {
    stem: "The steady-state approximation is most appropriate when the intermediate is",
    topic: "Reaction Mechanisms",
    explanation: "The steady-state treatment works well for a highly reactive intermediate whose concentration stays low and nearly constant because it is consumed almost as fast as it forms.",
    choices: [
      { text: "reactive and at a low concentration", isCorrect: true },
      { text: "stable and present in large amounts" },
      { text: "the major product of the reaction" },
      { text: "identical to the catalyst" },
    ],
  },
  {
    stem: "For a bimolecular elementary step A + B → products, the rate law is",
    topic: "Reaction Mechanisms",
    explanation: "A bimolecular elementary step is first order in each reactant, so rate = k[A][B] and second order overall. The molecularity (two) sets the order for an elementary step.",
    choices: [
      { text: "rate = k[A][B]", isCorrect: true },
      { text: "rate = k[A]" },
      { text: "rate = k (zero order)" },
      { text: "rate = k[A]²[B]²" },
    ],
  },
  {
    stem: "If the rate of a reaction quadruples when temperature rises by 20 °C, and doubles per 10 °C, this is consistent with",
    topic: "Temperature & Arrhenius",
    explanation: "Two successive 10 °C rises each about double the rate, giving a fourfold increase over 20 °C. This compounding reflects the exponential Arrhenius dependence of k on temperature.",
    choices: [
      { text: "the exponential Arrhenius dependence", isCorrect: true },
      { text: "a linear dependence of rate on temperature" },
      { text: "zero-order kinetics in temperature" },
      { text: "a temperature-independent rate constant" },
    ],
  },
  {
    stem: "A reaction intermediate differs from a transition state in that the intermediate",
    topic: "Reaction Mechanisms",
    explanation: "An intermediate sits in an energy valley and has a finite lifetime (it can sometimes be detected), whereas the transition state sits at an energy maximum and exists only fleetingly.",
    choices: [
      { text: "sits in an energy well, finite lifetime", isCorrect: true },
      { text: "lies at the top of the energy barrier" },
      { text: "cannot be detected even in principle" },
      { text: "is the same as the activated complex" },
    ],
  },
  {
    stem: "Increasing the surface area of a solid reactant (for example, by powdering it)",
    topic: "Theories of Reaction Rates",
    explanation: "More surface area exposes more particles to collisions per unit time, so a heterogeneous reaction speeds up. This is why fine powders react (and sometimes ignite) far faster than lumps.",
    choices: [
      { text: "increases the reaction rate", isCorrect: true },
      { text: "decreases the reaction rate" },
      { text: "has no effect on the rate" },
      { text: "changes the equilibrium constant" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which factors generally increase the rate of a chemical reaction? Select all that apply.",
    topic: "Rate Laws & Order",
    explanation: "Higher temperature, higher reactant concentration (for positive order), and a catalyst all raise the rate. Raising the activation energy or cooling the system would slow it.",
    choices: [
      { text: "raising the temperature", isCorrect: true },
      { text: "increasing reactant concentration", isCorrect: true },
      { text: "adding a suitable catalyst", isCorrect: true },
      { text: "increasing the activation energy" },
      { text: "cooling the reaction mixture" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about the rate constant k are correct? Select all that apply.",
    topic: "Temperature & Arrhenius",
    explanation: "k depends on temperature and on catalysis through the Arrhenius law, and its units depend on the overall order. It does not depend on the reactant concentrations.",
    choices: [
      { text: "it depends on temperature", isCorrect: true },
      { text: "it is changed by a catalyst", isCorrect: true },
      { text: "its units depend on the reaction order", isCorrect: true },
      { text: "it depends on reactant concentration" },
      { text: "it equals the reaction rate always" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which are true of a first-order reaction? Select all that apply.",
    topic: "Integrated Rate Laws",
    explanation: "First order gives a constant half-life, a linear ln[A]-versus-t plot, and exponential decay of [A]. Its k has units of inverse time; 1/[A] versus t is linear only for second order.",
    choices: [
      { text: "the half-life is constant", isCorrect: true },
      { text: "ln[A] versus time is linear", isCorrect: true },
      { text: "[A] decays exponentially", isCorrect: true },
      { text: "1/[A] versus time is linear" },
      { text: "k has units of M⁻¹ s⁻¹" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about activation energy Ea are correct? Select all that apply.",
    topic: "Temperature & Arrhenius",
    explanation: "Ea is the barrier from reactants to the transition state; a larger Ea means a slower, more temperature-sensitive reaction; a catalyst lowers it. Ea is not the overall energy released.",
    choices: [
      { text: "it is the barrier from reactants to the transition state", isCorrect: true },
      { text: "larger Ea means a slower reaction", isCorrect: true },
      { text: "a catalyst lowers it", isCorrect: true },
      { text: "it equals the energy released by the reaction" },
      { text: "it is unrelated to temperature sensitivity" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements correctly describe a catalyst? Select all that apply.",
    topic: "Catalysis",
    explanation: "A catalyst lowers Ea by offering an alternative path and speeds forward and reverse alike; it is not consumed overall and leaves K and ΔG unchanged. It does not shift the equilibrium position.",
    choices: [
      { text: "it lowers the activation energy", isCorrect: true },
      { text: "it is regenerated (not consumed overall)", isCorrect: true },
      { text: "it speeds forward and reverse reactions equally", isCorrect: true },
      { text: "it shifts the equilibrium toward products" },
      { text: "it changes the reaction ΔG" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which conditions must a colliding pair of molecules meet to react, per collision theory? Select all that apply.",
    topic: "Theories of Reaction Rates",
    explanation: "Effective collisions require energy at least equal to Ea and a proper orientation of the reacting groups. Neither low-energy nor mis-oriented collisions lead to reaction, however frequent.",
    choices: [
      { text: "they must have at least the activation energy", isCorrect: true },
      { text: "they must be correctly oriented", isCorrect: true },
      { text: "any collision suffices regardless of energy" },
      { text: "orientation is irrelevant to reaction" },
      { text: "they must form a stable intermediate first" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about reaction mechanisms are correct? Select all that apply.",
    topic: "Reaction Mechanisms",
    explanation: "The slowest step is rate-determining; the elementary steps must sum to the overall equation; intermediates form then are consumed. Elementary-step rate laws follow molecularity, but overall orders are empirical.",
    choices: [
      { text: "the slowest step is rate-determining", isCorrect: true },
      { text: "the steps must sum to the overall reaction", isCorrect: true },
      { text: "an intermediate is made then consumed", isCorrect: true },
      { text: "overall order always equals the coefficients" },
      { text: "every mechanism has exactly one step" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which plots give a straight line for the indicated order? Select all that apply.",
    topic: "Integrated Rate Laws",
    explanation: "Zero order is linear in [A] versus t, first order in ln[A] versus t, and second order in 1/[A] versus t. A ln[A]-versus-t line does not indicate second order.",
    choices: [
      { text: "[A] versus t for zero order", isCorrect: true },
      { text: "ln[A] versus t for first order", isCorrect: true },
      { text: "1/[A] versus t for second order", isCorrect: true },
      { text: "ln[A] versus t for second order" },
      { text: "[A] versus t for first order" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about enzyme (Michaelis-Menten) kinetics are correct? Select all that apply.",
    topic: "Enzyme Kinetics",
    explanation: "At high substrate the rate saturates at Vmax; KM is the substrate concentration at half Vmax; the enzyme lowers Ea without shifting equilibrium. The enzyme is not consumed by the reaction.",
    choices: [
      { text: "the rate saturates at Vmax at high substrate", isCorrect: true },
      { text: "KM is the substrate level at half Vmax", isCorrect: true },
      { text: "the enzyme lowers the activation energy", isCorrect: true },
      { text: "the enzyme shifts the equilibrium to products" },
      { text: "the enzyme is used up stoichiometrically" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which changes raise the fraction of effective collisions in a gas reaction? Select all that apply.",
    topic: "Theories of Reaction Rates",
    explanation: "Higher temperature raises the fraction of molecules above Ea; a catalyst lowers Ea so more collisions qualify. Lowering temperature or raising Ea reduces the effective fraction.",
    choices: [
      { text: "increasing the temperature", isCorrect: true },
      { text: "adding a catalyst that lowers Ea", isCorrect: true },
      { text: "lowering the temperature" },
      { text: "increasing the activation energy" },
      { text: "removing all reactant molecules" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which quantities are unchanged by adding a catalyst? Select all that apply.",
    topic: "Catalysis",
    explanation: "A catalyst is purely kinetic: it leaves ΔH, ΔG, K, and the equilibrium position unchanged, altering only the rate and the activation energy of the path.",
    choices: [
      { text: "the standard reaction enthalpy ΔH", isCorrect: true },
      { text: "the equilibrium constant K", isCorrect: true },
      { text: "the position of equilibrium", isCorrect: true },
      { text: "the activation energy of the path" },
      { text: "the rate of the reaction" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "The rate constant of a reaction is independent of the reactant concentrations.",
    topic: "Rate Laws & Order",
    explanation: "k depends on temperature and catalysis but not on how much reactant is present; concentration enters the rate only through the rate law. So k is concentration-independent.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "For a first-order reaction, the half-life depends on the initial concentration of reactant.",
    topic: "Reaction Half-Life",
    explanation: "False. The first-order half-life t₁/₂ = 0.693/k contains no concentration term, so it is independent of the starting amount. Only zero- and second-order half-lives depend on concentration.",
    choices: [
      { text: "True" },
      { text: "False", isCorrect: true },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "A catalyst speeds a reaction by lowering its activation energy.",
    topic: "Catalysis",
    explanation: "A catalyst provides an alternative pathway with a lower activation energy, so more collisions succeed and the rate rises. It does not change the thermodynamics of the reaction.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "The order of a reaction can always be read directly from the coefficients of the balanced equation.",
    topic: "Rate Laws & Order",
    explanation: "False. Order is an experimental quantity and equals the coefficients only for a single elementary step. For overall reactions it must be determined from rate measurements.",
    choices: [
      { text: "True" },
      { text: "False", isCorrect: true },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "In a multistep mechanism, the slowest step determines the overall rate.",
    topic: "Reaction Mechanisms",
    explanation: "The rate-determining step is the slowest elementary step, and it limits the overall rate much as a bottleneck limits flow. Faster steps do not control the overall rate.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "Raising the temperature increases the rate mainly by increasing the activation energy.",
    topic: "Temperature & Arrhenius",
    explanation: "False. Temperature does not change Ea; it increases the fraction of molecules with energy above the fixed barrier, so more collisions are effective and k rises.",
    choices: [
      { text: "True" },
      { text: "False", isCorrect: true },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "A catalyst does not change the equilibrium constant of a reaction.",
    topic: "Catalysis",
    explanation: "A catalyst speeds forward and reverse reactions equally, so it hastens the approach to equilibrium but leaves K and the equilibrium position unchanged. It is kinetic, not thermodynamic.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
];
