import type { Q } from "../_lib/qbank";

export const PHYSICAL_SET_3: Q[] = [
  {
    stem: "The second law of thermodynamics, in the Clausius statement, asserts that heat cannot flow spontaneously from a:",
    topic: "Entropy & the Second Law",
    explanation: "Clausius's statement: heat does not pass spontaneously from a colder to a hotter body without work being done. This directional restriction is what the first law alone does not provide.",
    choices: [
      { text: "Colder body to a hotter body unaided", isCorrect: true },
      { text: "Hotter body to a colder body ever" },
      { text: "Gas to a liquid at any time" },
      { text: "System to its surroundings at all" },
    ],
  },
  {
    stem: "Entropy is best described as a state function that measures the:",
    topic: "Entropy & the Second Law",
    explanation: "Entropy S measures the dispersal of energy and matter — often summarised as the number of accessible microstates. As a state function, ΔS depends only on the initial and final states.",
    choices: [
      { text: "Dispersal of energy among accessible microstates", isCorrect: true },
      { text: "Total heat content of a system" },
      { text: "Rate of a chemical reaction" },
      { text: "Force exerted on the container" },
    ],
  },
  {
    stem: "For a reversible process, the infinitesimal entropy change is defined as:",
    topic: "Entropy & the Second Law",
    explanation: "The thermodynamic definition is dS = dq_rev/T: entropy change is the reversible heat divided by the absolute temperature. Only the reversible path gives the true ΔS.",
    choices: [
      { text: "dS = dq_rev/T", isCorrect: true },
      { text: "dS = dq_rev·T" },
      { text: "dS = T/dq_rev" },
      { text: "dS = dw/T" },
    ],
  },
  {
    stem: "The Clausius inequality, which holds for any real (irreversible) process, states that:",
    topic: "Entropy & the Second Law",
    explanation: "The Clausius inequality is dS ≥ dq/T, with equality only for a reversible path. For an irreversible process the entropy change exceeds the heat divided by temperature.",
    choices: [
      { text: "dS ≥ dq/T", isCorrect: true },
      { text: "dS ≤ dq/T" },
      { text: "dS = dq·T" },
      { text: "dS = 0 always" },
    ],
  },
  {
    stem: "For an isolated system, the second law requires that any spontaneous change has:",
    topic: "Entropy & the Second Law",
    explanation: "In an isolated system no heat crosses the boundary, so a spontaneous process must have ΔS_total > 0; entropy increases until equilibrium, where it is maximal. At equilibrium ΔS = 0.",
    choices: [
      { text: "A positive total entropy change", isCorrect: true },
      { text: "A negative total entropy change" },
      { text: "Zero entropy change always" },
      { text: "A decrease in temperature" },
    ],
  },
  {
    stem: "The total entropy change that determines spontaneity is the sum of the entropy changes of the:",
    topic: "Entropy & the Second Law",
    explanation: "Spontaneity is governed by ΔS_total = ΔS_system + ΔS_surroundings > 0. A process with negative system entropy can still be spontaneous if the surroundings gain enough entropy.",
    choices: [
      { text: "System and its surroundings", isCorrect: true },
      { text: "System alone in every case" },
      { text: "Surroundings alone always" },
      { text: "Reactants minus the catalyst" },
    ],
  },
  {
    stem: "When heat q is released to surroundings at temperature T, the entropy change of the surroundings is:",
    topic: "Entropy & the Second Law",
    explanation: "The surroundings act as a large reservoir at constant T, so ΔS_surr = −q_system/T = +q_released/T. Exothermic reactions raise the surroundings' entropy.",
    choices: [
      { text: "q_released/T (a positive increase)", isCorrect: true },
      { text: "−q_released·T" },
      { text: "Zero regardless of q" },
      { text: "q_released·T²" },
    ],
  },
  {
    stem: "The entropy change on isothermal reversible expansion of an ideal gas from V₁ to V₂ is:",
    topic: "Entropy & the Second Law",
    explanation: "At constant T, ΔS = nR ln(V₂/V₁). Expansion (V₂ > V₁) increases entropy as the gas accesses more positional microstates; the heat absorbed equals TΔS.",
    choices: [
      { text: "ΔS = nR ln(V₂/V₁)", isCorrect: true },
      { text: "ΔS = nR ln(V₁/V₂)" },
      { text: "ΔS = nR(V₂ − V₁)" },
      { text: "ΔS = 0 for expansion" },
    ],
  },
  {
    stem: "Entropy generally increases in the order solid → liquid → gas because:",
    topic: "Entropy & the Second Law",
    explanation: "Melting and vaporising increase molecular freedom and the number of accessible microstates, so S(gas) > S(liquid) > S(solid). The gas phase has by far the largest positional and momentum disorder.",
    choices: [
      { text: "Molecular disorder and freedom increase", isCorrect: true },
      { text: "Molecular mass increases in that order" },
      { text: "Temperature must fall in that order" },
      { text: "Bonds become stronger in that order" },
    ],
  },
  {
    stem: "For a reaction, a positive standard entropy change (ΔS° > 0) is most often associated with:",
    topic: "Entropy & the Second Law",
    explanation: "An increase in the moles of gas (Δn_gas > 0) strongly raises entropy, since gases dominate the entropy of a system. Producing more gas molecules typically gives ΔS° > 0.",
    choices: [
      { text: "An increase in the number of gas molecules", isCorrect: true },
      { text: "A decrease in the number of gas molecules" },
      { text: "Formation of a solid from gases" },
      { text: "No change in the amount of gas" },
    ],
  },
  {
    stem: "The entropy change accompanying a phase transition at its transition temperature is given by:",
    topic: "Entropy & the Second Law",
    explanation: "At the transition temperature the change is reversible, so ΔS_trans = ΔH_trans/T_trans. For vaporisation, ΔS_vap = ΔH_vap/T_b — the basis of Trouton's rule.",
    choices: [
      { text: "ΔS = ΔH_trans/T_trans", isCorrect: true },
      { text: "ΔS = ΔH_trans·T_trans" },
      { text: "ΔS = T_trans/ΔH_trans" },
      { text: "ΔS = ΔH_trans − T_trans" },
    ],
  },
  {
    stem: "Trouton's rule states that the standard entropy of vaporisation for many liquids is approximately:",
    topic: "Entropy & the Second Law",
    explanation: "Trouton's rule notes that ΔS_vap ≈ 85 J K⁻¹ mol⁻¹ for many normal liquids, reflecting a similar increase in disorder on vaporisation. Hydrogen-bonded liquids (e.g. water) deviate upward.",
    choices: [
      { text: "A constant near 85 J K⁻¹ mol⁻¹", isCorrect: true },
      { text: "Zero for all liquids" },
      { text: "Equal to R for all liquids" },
      { text: "Proportional to molar mass only" },
    ],
  },
  {
    stem: "A reversible heat engine operating between two reservoirs converts heat to work with an efficiency limited by the:",
    topic: "Carnot Cycle",
    explanation: "The Carnot efficiency, η = 1 − T_c/T_h, sets the maximum fraction of heat convertible to work between hot (T_h) and cold (T_c) reservoirs. No engine can exceed it.",
    choices: [
      { text: "Temperatures of the two reservoirs", isCorrect: true },
      { text: "Size of the working substance" },
      { text: "Colour of the engine" },
      { text: "Molar mass of the gas used" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about entropy and the second law are correct? Select all that apply.",
    topic: "Entropy & the Second Law",
    explanation: "Entropy is a state function; dS = dq_rev/T; the Clausius inequality is dS ≥ dq/T; a spontaneous change in an isolated system has ΔS > 0. Entropy is not conserved in irreversible processes — it increases.",
    choices: [
      { text: "Entropy is a state function", isCorrect: true },
      { text: "For a reversible step, dS = dq_rev/T", isCorrect: true },
      { text: "The Clausius inequality is dS ≥ dq/T", isCorrect: true },
      { text: "An isolated system's spontaneous change has ΔS > 0", isCorrect: true },
      { text: "Total entropy is conserved in irreversible processes" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which changes are expected to increase the entropy of a system? Select all that apply.",
    topic: "Entropy & the Second Law",
    explanation: "Melting, vaporising, isothermal expansion of a gas, and producing more moles of gas all raise entropy. Freezing a liquid to a solid lowers entropy.",
    choices: [
      { text: "Melting a solid to a liquid", isCorrect: true },
      { text: "Vaporising a liquid to a gas", isCorrect: true },
      { text: "Isothermal expansion of a gas", isCorrect: true },
      { text: "A reaction that increases the moles of gas", isCorrect: true },
      { text: "Freezing a liquid into a solid" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "For any spontaneous process, the total entropy of the system plus its surroundings increases.",
    topic: "Entropy & the Second Law",
    explanation: "The second law requires ΔS_total = ΔS_system + ΔS_surroundings > 0 for a spontaneous change; at equilibrium the total entropy is at its maximum and ΔS_total = 0.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "The Carnot cycle consists of four reversible steps in the sequence:",
    topic: "Carnot Cycle",
    explanation: "The Carnot cycle is: isothermal expansion, adiabatic expansion, isothermal compression, adiabatic compression. Two isotherms and two adiabats form the most efficient cycle between two temperatures.",
    choices: [
      { text: "Two isothermal and two adiabatic steps", isCorrect: true },
      { text: "Four isothermal steps" },
      { text: "Four adiabatic steps" },
      { text: "Two isobaric and two isochoric steps" },
    ],
  },
  {
    stem: "The efficiency of a Carnot engine operating between hot (T_h) and cold (T_c) reservoirs is:",
    topic: "Carnot Cycle",
    explanation: "η = 1 − T_c/T_h, with temperatures in kelvin. Efficiency rises as the reservoirs' temperature difference grows and approaches 1 only as T_c → 0.",
    choices: [
      { text: "η = 1 − T_c/T_h", isCorrect: true },
      { text: "η = 1 − T_h/T_c" },
      { text: "η = T_c/T_h" },
      { text: "η = T_h − T_c" },
    ],
  },
  {
    stem: "A Carnot engine takes in 1000 J from a hot reservoir at 500 K and rejects heat to a 300 K reservoir. Its maximum work output is:",
    topic: "Carnot Cycle",
    explanation: "η = 1 − 300/500 = 0.40, so w = 0.40 × 1000 J = 400 J. The remaining 600 J is rejected to the cold reservoir; no real engine between these temperatures can do better.",
    choices: [
      { text: "400 J", isCorrect: true },
      { text: "1000 J" },
      { text: "600 J" },
      { text: "200 J" },
    ],
  },
  {
    stem: "No engine operating between two given temperatures can be more efficient than a reversible (Carnot) engine — this is:",
    topic: "Carnot Cycle",
    explanation: "Carnot's theorem: all reversible engines between the same two reservoirs have the same efficiency, and no irreversible engine can exceed it. It follows directly from the second law.",
    choices: [
      { text: "Carnot's theorem", isCorrect: true },
      { text: "Hess's law" },
      { text: "Trouton's rule" },
      { text: "Raoult's law" },
    ],
  },
  {
    stem: "Summing dq_rev/T around a complete reversible cycle gives zero, which establishes that:",
    topic: "Entropy & the Second Law",
    explanation: "The Clausius theorem — the cyclic integral of dq_rev/T is zero — proves that entropy (dS = dq_rev/T) is a state function, since its change around any closed path vanishes.",
    choices: [
      { text: "Entropy is a state function", isCorrect: true },
      { text: "Heat is a state function" },
      { text: "Work is conserved in a cycle" },
      { text: "Temperature is always constant" },
    ],
  },
  {
    stem: "A refrigerator moves heat from cold to hot surroundings; the second law requires that this can happen only if:",
    topic: "Carnot Cycle",
    explanation: "Moving heat 'uphill' from cold to hot is not spontaneous, so it requires work input (electrical energy). A refrigerator is a heat engine run in reverse, driven by work.",
    choices: [
      { text: "Work is supplied to the device", isCorrect: true },
      { text: "The process is left to occur spontaneously" },
      { text: "The cold reservoir is warmer than the hot" },
      { text: "No energy is supplied at all" },
    ],
  },
  {
    stem: "The entropy change of the universe for a reversible process is:",
    topic: "Entropy & the Second Law",
    explanation: "For a reversible process, ΔS_universe = 0: the entropy gained by one part exactly balances the entropy lost by another. Any real (irreversible) process gives ΔS_universe > 0.",
    choices: [
      { text: "Zero", isCorrect: true },
      { text: "Always positive" },
      { text: "Always negative" },
      { text: "Equal to ΔH/T" },
    ],
  },
  {
    stem: "The entropy change of the universe for a spontaneous, irreversible process is:",
    topic: "Entropy & the Second Law",
    explanation: "Every real spontaneous process generates entropy, so ΔS_universe > 0. The magnitude of this positive quantity measures how far the process is from reversibility.",
    choices: [
      { text: "Greater than zero", isCorrect: true },
      { text: "Equal to zero" },
      { text: "Less than zero" },
      { text: "Undefined" },
    ],
  },
  {
    stem: "Heat flows spontaneously from a hot body to a cold body because the process gives a net:",
    topic: "Entropy & the Second Law",
    explanation: "The cold body gains entropy q/T_c and the hot body loses q/T_h; since T_c < T_h, the gain exceeds the loss, so ΔS_universe > 0. This positive total drives the spontaneous flow.",
    choices: [
      { text: "Increase in the entropy of the universe", isCorrect: true },
      { text: "Decrease in total entropy" },
      { text: "Increase in the total energy" },
      { text: "Decrease in the temperature difference only" },
    ],
  },
  {
    stem: "The coefficient of performance of a refrigerator is highest when the temperature difference between the reservoirs is:",
    topic: "Carnot Cycle",
    explanation: "A refrigerator works most efficiently (highest coefficient of performance) when it pumps heat across a small temperature gap; a large gap demands much more work per unit of heat moved.",
    choices: [
      { text: "Small", isCorrect: true },
      { text: "Very large" },
      { text: "Exactly zero kelvin" },
      { text: "Infinite" },
    ],
  },
  {
    stem: "Two large blocks at different temperatures are placed in thermal contact and allowed to reach a common temperature. The entropy of the universe:",
    topic: "Entropy & the Second Law",
    explanation: "Irreversible heat flow between finite bodies at different temperatures generates entropy, so ΔS_universe > 0 until they reach a common temperature, at which point equilibrium (maximum entropy) is attained.",
    choices: [
      { text: "Increases until they reach equilibrium", isCorrect: true },
      { text: "Decreases as they equalise" },
      { text: "Stays exactly constant" },
      { text: "Becomes negative" },
    ],
  },
  {
    stem: "The maximum work obtainable from a given quantity of heat is limited by the second law because some heat must be:",
    topic: "Carnot Cycle",
    explanation: "A heat engine must reject some heat to a cold reservoir; only the fraction (1 − T_c/T_h) can become work. This unavoidable rejection is why heat cannot be fully converted to work in a cycle.",
    choices: [
      { text: "Rejected to a cold reservoir", isCorrect: true },
      { text: "Created from the work output" },
      { text: "Stored as potential energy" },
      { text: "Converted entirely to work" },
    ],
  },
  {
    stem: "The Kelvin–Planck statement of the second law says it is impossible to build a cyclic engine that does nothing but:",
    topic: "Entropy & the Second Law",
    explanation: "Kelvin–Planck: no cyclic process can convert heat completely into work with no other effect. Some heat must always be discarded to a colder reservoir — equivalent to the Clausius statement.",
    choices: [
      { text: "Convert heat entirely into work", isCorrect: true },
      { text: "Move heat from hot to cold" },
      { text: "Compress a gas isothermally" },
      { text: "Raise the temperature of a gas" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about the Carnot cycle and heat engines are correct? Select all that apply.",
    topic: "Carnot Cycle",
    explanation: "The Carnot cycle uses two isotherms and two adiabats; its efficiency is 1 − T_c/T_h; no engine between the same reservoirs can beat it; some heat must be rejected. Efficiency does not reach 100% at any finite temperature.",
    choices: [
      { text: "It comprises two isothermal and two adiabatic steps", isCorrect: true },
      { text: "Its efficiency is 1 − T_c/T_h", isCorrect: true },
      { text: "No real engine between the same reservoirs can exceed it", isCorrect: true },
      { text: "Some heat must be rejected to the cold reservoir", isCorrect: true },
      { text: "Its efficiency reaches 100%% at ordinary temperatures" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about the entropy of the universe are correct? Select all that apply.",
    topic: "Entropy & the Second Law",
    explanation: "A reversible process gives ΔS_univ = 0; an irreversible (spontaneous) one gives ΔS_univ > 0; spontaneous heat flow hot→cold raises it; ΔS_univ = ΔS_sys + ΔS_surr. It never decreases for a real process.",
    choices: [
      { text: "A reversible process has ΔS_universe = 0", isCorrect: true },
      { text: "A spontaneous process has ΔS_universe > 0", isCorrect: true },
      { text: "ΔS_universe = ΔS_system + ΔS_surroundings", isCorrect: true },
      { text: "Spontaneous hot-to-cold heat flow increases it", isCorrect: true },
      { text: "A real spontaneous process decreases it" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "A Carnot engine's efficiency depends only on the temperatures of its two reservoirs, not on the working substance used.",
    topic: "Carnot Cycle",
    explanation: "By Carnot's theorem, all reversible engines between the same two temperatures share the efficiency 1 − T_c/T_h, independent of whether the working substance is an ideal gas, a real gas, or anything else.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "The Gibbs free energy is defined in terms of enthalpy, temperature and entropy as:",
    topic: "Free Energy & Spontaneity",
    explanation: "G = H − TS. Changes in G at constant temperature and pressure indicate the direction of spontaneous change and the maximum non-expansion work available.",
    choices: [
      { text: "G = H − TS", isCorrect: true },
      { text: "G = H + TS" },
      { text: "G = U − TS" },
      { text: "G = TS − H" },
    ],
  },
  {
    stem: "At constant temperature and pressure, a process is spontaneous when the Gibbs free energy change is:",
    topic: "Free Energy & Spontaneity",
    explanation: "A negative ΔG (ΔG < 0) signals a spontaneous process at constant T and p. When ΔG = 0 the system is at equilibrium, and ΔG > 0 means the reverse direction is spontaneous.",
    choices: [
      { text: "Negative (ΔG < 0)", isCorrect: true },
      { text: "Positive (ΔG > 0)" },
      { text: "Exactly zero always" },
      { text: "Equal to ΔH" },
    ],
  },
  {
    stem: "The relationship linking the Gibbs energy change to enthalpy and entropy changes is:",
    topic: "Free Energy & Spontaneity",
    explanation: "ΔG = ΔH − TΔS. This ties spontaneity to the competition between the enthalpy change and the temperature-weighted entropy change.",
    choices: [
      { text: "ΔG = ΔH − TΔS", isCorrect: true },
      { text: "ΔG = ΔH + TΔS" },
      { text: "ΔG = TΔS − ΔH" },
      { text: "ΔG = ΔH·TΔS" },
    ],
  },
  {
    stem: "A reaction that is exothermic (ΔH < 0) and increases entropy (ΔS > 0) is:",
    topic: "Free Energy & Spontaneity",
    explanation: "With ΔH < 0 and ΔS > 0, ΔG = ΔH − TΔS is negative at all temperatures, so the reaction is spontaneous at every temperature. Both terms favour spontaneity.",
    choices: [
      { text: "Spontaneous at all temperatures", isCorrect: true },
      { text: "Never spontaneous" },
      { text: "Spontaneous only at high temperature" },
      { text: "Spontaneous only at low temperature" },
    ],
  },
  {
    stem: "A reaction that is endothermic (ΔH > 0) and decreases entropy (ΔS < 0) is:",
    topic: "Free Energy & Spontaneity",
    explanation: "With ΔH > 0 and ΔS < 0, ΔG = ΔH − TΔS is positive at all temperatures, so the reaction is non-spontaneous at every temperature. Both terms oppose spontaneity.",
    choices: [
      { text: "Non-spontaneous at all temperatures", isCorrect: true },
      { text: "Spontaneous at all temperatures" },
      { text: "Spontaneous only at high temperature" },
      { text: "Spontaneous only at low temperature" },
    ],
  },
  {
    stem: "An endothermic reaction (ΔH > 0) with a positive entropy change (ΔS > 0) becomes spontaneous:",
    topic: "Free Energy & Spontaneity",
    explanation: "When ΔH > 0 and ΔS > 0, the −TΔS term can overcome ΔH only at high temperature, making ΔG negative there. Such reactions are entropy-driven and spontaneous only above a certain temperature.",
    choices: [
      { text: "Only at high temperature", isCorrect: true },
      { text: "Only at low temperature" },
      { text: "At all temperatures" },
      { text: "At no temperature" },
    ],
  },
  {
    stem: "An exothermic reaction (ΔH < 0) with a negative entropy change (ΔS < 0) is spontaneous:",
    topic: "Free Energy & Spontaneity",
    explanation: "With ΔH < 0 and ΔS < 0, ΔG is negative only when the favourable ΔH outweighs the unfavourable −TΔS, which occurs at low temperature. These reactions are enthalpy-driven.",
    choices: [
      { text: "Only at low temperature", isCorrect: true },
      { text: "Only at high temperature" },
      { text: "At all temperatures" },
      { text: "At no temperature" },
    ],
  },
  {
    stem: "The temperature at which a reaction changes from non-spontaneous to spontaneous (ΔG = 0) is approximately:",
    topic: "Free Energy & Spontaneity",
    explanation: "Setting ΔG = 0 in ΔG = ΔH − TΔS gives the crossover temperature T = ΔH/ΔS. Below or above it (depending on signs) the sign of ΔG flips.",
    choices: [
      { text: "T = ΔH/ΔS", isCorrect: true },
      { text: "T = ΔS/ΔH" },
      { text: "T = ΔH·ΔS" },
      { text: "T = ΔH − ΔS" },
    ],
  },
  {
    stem: "The Gibbs free energy change equals the maximum ______ obtainable from a process at constant temperature and pressure.",
    topic: "Free Energy & Spontaneity",
    explanation: "−ΔG equals the maximum non-expansion (e.g. electrical) work a process can deliver at constant T and p. This links thermodynamics to electrochemical cell work.",
    choices: [
      { text: "Non-expansion work", isCorrect: true },
      { text: "Expansion work only" },
      { text: "Heat released" },
      { text: "Entropy generated" },
    ],
  },
  {
    stem: "The Helmholtz free energy, the criterion for spontaneity at constant temperature and volume, is defined as:",
    topic: "Free Energy & Spontaneity",
    explanation: "A = U − TS. At constant T and V a spontaneous process has ΔA < 0, and −ΔA equals the maximum total work obtainable. It complements G, which applies at constant T and p.",
    choices: [
      { text: "A = U − TS", isCorrect: true },
      { text: "A = H − TS" },
      { text: "A = U + TS" },
      { text: "A = TS − U" },
    ],
  },
  {
    stem: "The standard Gibbs energy of reaction is calculated from standard Gibbs energies of formation as:",
    topic: "Free Energy & Spontaneity",
    explanation: "ΔG°_rxn = ΣΔG°_f(products) − ΣΔG°_f(reactants), mirroring the Hess's-law treatment of enthalpies. Elements in their standard states have ΔG°_f = 0.",
    choices: [
      { text: "Σ ΔG°_f(products) − Σ ΔG°_f(reactants)", isCorrect: true },
      { text: "Σ ΔG°_f(reactants) − Σ ΔG°_f(products)" },
      { text: "Σ ΔG°_f(products) + Σ ΔG°_f(reactants)" },
      { text: "The average of the ΔG°_f values" },
    ],
  },
  {
    stem: "The Gibbs free energy of a system is at a minimum when the system is at:",
    topic: "Free Energy & Spontaneity",
    explanation: "At constant T and p, G decreases during any spontaneous change and reaches its minimum at equilibrium, where ΔG = 0. This minimum principle locates the equilibrium composition.",
    choices: [
      { text: "Equilibrium", isCorrect: true },
      { text: "The start of the reaction" },
      { text: "Absolute zero only" },
      { text: "Maximum temperature" },
    ],
  },
  {
    stem: "Which of the following makes the largest favourable contribution to a negative ΔG at high temperature?",
    topic: "Free Energy & Spontaneity",
    explanation: "Because the entropy term is weighted by T, a positive ΔS contributes −TΔS, which becomes increasingly negative (favourable) as temperature rises. Entropy dominates spontaneity at high T.",
    choices: [
      { text: "A large positive entropy change", isCorrect: true },
      { text: "A large positive enthalpy change" },
      { text: "A negative entropy change" },
      { text: "A zero entropy change" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about Gibbs free energy are correct? Select all that apply.",
    topic: "Free Energy & Spontaneity",
    explanation: "G = H − TS; ΔG = ΔH − TΔS; ΔG < 0 means spontaneous at constant T,p; −ΔG is the maximum non-expansion work; G is minimum at equilibrium. A positive ΔG does not indicate spontaneity.",
    choices: [
      { text: "G is defined as H − TS", isCorrect: true },
      { text: "ΔG = ΔH − TΔS", isCorrect: true },
      { text: "ΔG < 0 indicates a spontaneous process at constant T and p", isCorrect: true },
      { text: "−ΔG equals the maximum non-expansion work", isCorrect: true },
      { text: "A positive ΔG indicates a spontaneous process" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which combinations of ΔH and ΔS give a reaction that is spontaneous only at high temperature? Select all that apply.",
    topic: "Free Energy & Spontaneity",
    explanation: "Only ΔH > 0 with ΔS > 0 is spontaneous just at high T (the −TΔS term must overcome a positive ΔH). ΔH<0,ΔS>0 is always spontaneous; ΔH<0,ΔS<0 only at low T; ΔH>0,ΔS<0 never.",
    choices: [
      { text: "ΔH > 0 and ΔS > 0", isCorrect: true },
      { text: "ΔH < 0 and ΔS > 0" },
      { text: "ΔH < 0 and ΔS < 0" },
      { text: "ΔH > 0 and ΔS < 0" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "At constant temperature and pressure, a reaction with ΔG = 0 is at equilibrium.",
    topic: "Free Energy & Spontaneity",
    explanation: "When ΔG = 0 the forward and reverse directions are equally favourable and the Gibbs energy is at its minimum, which is the condition for equilibrium at constant T and p.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "The third law of thermodynamics states that the entropy of a perfect crystalline substance at absolute zero is:",
    topic: "The Third Law",
    explanation: "The third law: the entropy of a perfect, pure crystal approaches zero as T → 0 K. This provides an absolute zero of entropy from which absolute entropies are measured.",
    choices: [
      { text: "Zero", isCorrect: true },
      { text: "Equal to R" },
      { text: "Infinite" },
      { text: "Equal to ΔH_fus" },
    ],
  },
  {
    stem: "Because of the third law, it is possible to assign substances a value of their:",
    topic: "The Third Law",
    explanation: "With S = 0 at 0 K as a reference, one can determine absolute (third-law) entropies by integrating C_p/T from 0 K upward, adding entropies of any phase transitions along the way.",
    choices: [
      { text: "Absolute (third-law) entropy", isCorrect: true },
      { text: "Absolute enthalpy" },
      { text: "Absolute internal energy" },
      { text: "Absolute Gibbs energy" },
    ],
  },
  {
    stem: "The absolute entropy of a substance at temperature T is obtained by integrating, from 0 K, the quantity:",
    topic: "The Third Law",
    explanation: "S(T) = ∫₀ᵀ (C_p/T) dT plus the entropy contributions of any phase changes. The heat capacity divided by temperature, integrated over T, gives the entropy accumulated on warming.",
    choices: [
      { text: "C_p/T with respect to temperature", isCorrect: true },
      { text: "C_p·T with respect to temperature" },
      { text: "C_p with respect to pressure" },
      { text: "H/T with respect to volume" },
    ],
  },
  {
    stem: "Unlike enthalpies of formation, standard molar entropies of elements in their standard states are:",
    topic: "The Third Law",
    explanation: "Standard molar entropies S° are absolute values (referenced to zero at 0 K), so even elements have non-zero, positive S°. This contrasts with ΔH°_f, which is defined as zero for elements.",
    choices: [
      { text: "Non-zero and positive", isCorrect: true },
      { text: "Exactly zero by definition" },
      { text: "Always negative" },
      { text: "Undefined" },
    ],
  },
  {
    stem: "A 'perfect crystal' is required for zero entropy at 0 K because any residual disorder, such as random orientations, leaves a:",
    topic: "The Third Law",
    explanation: "Imperfections like frozen-in molecular orientations (e.g. CO's head-to-tail disorder) give a non-zero residual entropy at 0 K. Only a perfectly ordered crystal reaches S = 0.",
    choices: [
      { text: "Residual entropy at absolute zero", isCorrect: true },
      { text: "Negative entropy at absolute zero" },
      { text: "Higher melting point" },
      { text: "Zero heat capacity at all T" },
    ],
  },
  {
    stem: "The third law implies that reaching absolute zero temperature in a finite number of steps is:",
    topic: "The Third Law",
    explanation: "A consequence of the third law is the unattainability of absolute zero: no finite sequence of processes can cool a system exactly to 0 K, though it can be approached arbitrarily closely.",
    choices: [
      { text: "Impossible", isCorrect: true },
      { text: "Easily achievable" },
      { text: "Required for any refrigerator" },
      { text: "Guaranteed by the first law" },
    ],
  },
  {
    stem: "The standard entropy change of a reaction is computed from absolute entropies as:",
    topic: "The Third Law",
    explanation: "ΔS°_rxn = ΣS°(products) − ΣS°(reactants), using tabulated absolute (third-law) entropies. Because elements have non-zero S°, they contribute to this sum (unlike in the ΔH°_f treatment).",
    choices: [
      { text: "Σ S°(products) − Σ S°(reactants)", isCorrect: true },
      { text: "Σ S°(reactants) − Σ S°(products)" },
      { text: "Σ S°(products) + Σ S°(reactants)" },
      { text: "Zero for every reaction" },
    ],
  },
  {
    stem: "As the temperature of a substance approaches absolute zero, its heat capacity C_p approaches:",
    topic: "The Third Law",
    explanation: "Consistent with the third law, heat capacities fall toward zero as T → 0 K (for a solid, C_p ∝ T³ at low temperature, the Debye behaviour). This ensures the entropy integral converges.",
    choices: [
      { text: "Zero", isCorrect: true },
      { text: "A constant equal to R" },
      { text: "Infinity" },
      { text: "(3/2)R" },
    ],
  },
  {
    stem: "A fundamental thermodynamic relation combining the first and second laws for a reversible change is:",
    topic: "Thermodynamic Relations",
    explanation: "dU = T dS − p dV combines dU = dq + dw with dq_rev = T dS and dw = −p dV. It is the master equation from which many thermodynamic relations follow.",
    choices: [
      { text: "dU = T dS − p dV", isCorrect: true },
      { text: "dU = T dS + p dV" },
      { text: "dU = p dV − T dS" },
      { text: "dU = T dS − V dp" },
    ],
  },
  {
    stem: "The temperature variation of the Gibbs energy at constant pressure is governed by the relation (∂G/∂T)_p =:",
    topic: "Thermodynamic Relations",
    explanation: "From dG = −S dT + V dp, it follows that (∂G/∂T)_p = −S. Since entropy is positive, G always decreases as temperature rises at constant pressure.",
    choices: [
      { text: "−S", isCorrect: true },
      { text: "+S" },
      { text: "+V" },
      { text: "−V" },
    ],
  },
  {
    stem: "The pressure variation of the Gibbs energy at constant temperature is (∂G/∂p)_T =:",
    topic: "Thermodynamic Relations",
    explanation: "From dG = −S dT + V dp, (∂G/∂p)_T = V. Because volume is positive, G increases with pressure at constant temperature; the effect is largest for gases.",
    choices: [
      { text: "+V", isCorrect: true },
      { text: "−V" },
      { text: "−S" },
      { text: "+S" },
    ],
  },
  {
    stem: "For an ideal gas at constant temperature, the change in molar Gibbs energy with pressure is:",
    topic: "Thermodynamic Relations",
    explanation: "Integrating (∂G/∂p)_T = V_m = RT/p gives ΔG_m = RT ln(p₂/p₁). This logarithmic pressure dependence underlies the RT ln Q term in reaction thermodynamics.",
    choices: [
      { text: "ΔG_m = RT ln(p₂/p₁)", isCorrect: true },
      { text: "ΔG_m = RT(p₂ − p₁)" },
      { text: "ΔG_m = R ln(p₂/p₁)" },
      { text: "ΔG_m = 0 always" },
    ],
  },
  {
    stem: "The Gibbs–Helmholtz equation relates the temperature dependence of G/T to the system's:",
    topic: "Thermodynamic Relations",
    explanation: "The Gibbs–Helmholtz equation, [∂(G/T)/∂T]_p = −H/T², connects how G/T changes with temperature to the enthalpy. It is used to find how equilibrium constants vary with temperature.",
    choices: [
      { text: "Enthalpy", isCorrect: true },
      { text: "Volume only" },
      { text: "Molar mass" },
      { text: "Pressure only" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about the third law and absolute entropies are correct? Select all that apply.",
    topic: "The Third Law",
    explanation: "A perfect crystal has S → 0 as T → 0; absolute entropies come from integrating C_p/T; elements have non-zero S°; C_p → 0 as T → 0; absolute zero is unattainable. Elements' S° is not zero by definition (that's ΔH°_f).",
    choices: [
      { text: "A perfect crystal has zero entropy at 0 K", isCorrect: true },
      { text: "Absolute entropy is found by integrating C_p/T from 0 K", isCorrect: true },
      { text: "Elements have non-zero standard molar entropies", isCorrect: true },
      { text: "Heat capacity approaches zero as T approaches 0 K", isCorrect: true },
      { text: "Elements have zero standard entropy by definition" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which thermodynamic relations are correct? Select all that apply.",
    topic: "Thermodynamic Relations",
    explanation: "dU = T dS − p dV; (∂G/∂T)_p = −S; (∂G/∂p)_T = V; for an ideal gas ΔG_m = RT ln(p₂/p₁). The Gibbs energy increases (not decreases) with pressure at constant T.",
    choices: [
      { text: "dU = T dS − p dV", isCorrect: true },
      { text: "(∂G/∂T)_p = −S", isCorrect: true },
      { text: "(∂G/∂p)_T = V", isCorrect: true },
      { text: "For an ideal gas, ΔG_m = RT ln(p₂/p₁)", isCorrect: true },
      { text: "G decreases with increasing pressure at constant T" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "Standard molar entropies are absolute values referenced to zero entropy at 0 K, so even elements in their standard states have positive, non-zero entropies.",
    topic: "The Third Law",
    explanation: "Because the third law fixes S = 0 for a perfect crystal at 0 K, absolute entropies can be measured; elements accumulate positive entropy on warming to 298 K, unlike their zero standard enthalpy of formation.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "A reaction has ΔH = −100 kJ mol⁻¹ and ΔS = −200 J K⁻¹ mol⁻¹. At 298 K, ΔG is closest to:",
    topic: "Free Energy & Spontaneity",
    explanation: "ΔG = ΔH − TΔS = −100 − (298 × −0.200) = −100 + 59.6 ≈ −40 kJ mol⁻¹. The reaction is spontaneous at 298 K, though the unfavourable entropy term reduces the driving force.",
    choices: [
      { text: "−40 kJ mol⁻¹", isCorrect: true },
      { text: "−160 kJ mol⁻¹" },
      { text: "+40 kJ mol⁻¹" },
      { text: "−100 kJ mol⁻¹" },
    ],
  },
  {
    stem: "For a reaction with ΔH = +50 kJ mol⁻¹ and ΔS = +125 J K⁻¹ mol⁻¹, the temperature above which it becomes spontaneous is about:",
    topic: "Free Energy & Spontaneity",
    explanation: "Spontaneity begins where ΔG = 0, i.e. T = ΔH/ΔS = 50000/125 = 400 K. Above 400 K the −TΔS term outweighs the positive ΔH and ΔG turns negative.",
    choices: [
      { text: "400 K", isCorrect: true },
      { text: "125 K" },
      { text: "298 K" },
      { text: "40 K" },
    ],
  },
  {
    stem: "When one mole of ice melts at 0 °C (273 K) with ΔH_fus = 6.0 kJ mol⁻¹, the entropy change is about:",
    topic: "Entropy & the Second Law",
    explanation: "ΔS_fus = ΔH_fus/T = 6000 J / 273 K ≈ 22 J K⁻¹ mol⁻¹. Melting increases disorder, giving a positive entropy change at the melting point.",
    choices: [
      { text: "+22 J K⁻¹ mol⁻¹", isCorrect: true },
      { text: "−22 J K⁻¹ mol⁻¹" },
      { text: "+6000 J K⁻¹ mol⁻¹" },
      { text: "0 J K⁻¹ mol⁻¹" },
    ],
  },
  {
    stem: "Two moles of an ideal gas expand isothermally and reversibly to double their volume at 300 K. The entropy change of the gas is about:",
    topic: "Entropy & the Second Law",
    explanation: "ΔS = nR ln(V₂/V₁) = 2 × 8.314 × ln 2 ≈ 11.5 J K⁻¹. Doubling the volume increases the positional entropy; the value is positive.",
    choices: [
      { text: "+11.5 J K⁻¹", isCorrect: true },
      { text: "−11.5 J K⁻¹" },
      { text: "+23 J K⁻¹" },
      { text: "0 J K⁻¹" },
    ],
  },
  {
    stem: "If ΔS_system is negative but the reaction is exothermic, the reaction can still be spontaneous provided:",
    topic: "Free Energy & Spontaneity",
    explanation: "A negative system entropy can be overcome if the heat released raises the surroundings' entropy enough that ΔS_universe > 0 — equivalently, if ΔG = ΔH − TΔS is still negative, which favours low temperature.",
    choices: [
      { text: "The surroundings gain enough entropy from the released heat", isCorrect: true },
      { text: "The temperature is made very high" },
      { text: "The entropy of the gas is ignored" },
      { text: "The reaction is run in a vacuum" },
    ],
  },
  {
    stem: "The standard Gibbs energy of a reaction is related to its equilibrium constant by:",
    topic: "Free Energy & Spontaneity",
    explanation: "ΔG° = −RT ln K. A large negative ΔG° corresponds to a large K (products favoured); ΔG° = 0 gives K = 1. This bridges thermodynamics and chemical equilibrium.",
    choices: [
      { text: "ΔG° = −RT ln K", isCorrect: true },
      { text: "ΔG° = +RT ln K" },
      { text: "ΔG° = −RT/K" },
      { text: "ΔG° = K/RT" },
    ],
  },
  {
    stem: "A reaction with ΔG° = 0 has an equilibrium constant K equal to:",
    topic: "Free Energy & Spontaneity",
    explanation: "From ΔG° = −RT ln K, setting ΔG° = 0 gives ln K = 0, so K = 1. Reactants and products are equally favoured under standard conditions.",
    choices: [
      { text: "1", isCorrect: true },
      { text: "0" },
      { text: "Infinity" },
      { text: "Equal to RT" },
    ],
  },
  {
    stem: "Combining ΔG = ΔH − TΔS with ΔG° = −RT ln K shows that ln K generally ______ with temperature for an endothermic reaction.",
    topic: "Free Energy & Spontaneity",
    explanation: "For an endothermic reaction (ΔH > 0), the van 't Hoff relation makes ln K increase with temperature, so K grows — consistent with Le Chatelier's prediction that heating favours the endothermic direction.",
    choices: [
      { text: "Increases", isCorrect: true },
      { text: "Decreases" },
      { text: "Stays constant" },
      { text: "Becomes negative" },
    ],
  },
  {
    stem: "The entropy change of the surroundings for an exothermic reaction at constant temperature is:",
    topic: "Entropy & the Second Law",
    explanation: "ΔS_surr = −ΔH_system/T; for an exothermic reaction ΔH < 0, so ΔS_surr > 0. Releasing heat to the surroundings increases their entropy, favouring spontaneity.",
    choices: [
      { text: "Positive", isCorrect: true },
      { text: "Negative" },
      { text: "Zero" },
      { text: "Equal to ΔS_system" },
    ],
  },
  {
    stem: "Which statement about a reaction with ΔH < 0 and ΔS > 0 is correct?",
    topic: "Free Energy & Spontaneity",
    explanation: "Both a negative ΔH and a positive ΔS drive ΔG = ΔH − TΔS negative regardless of temperature, so the reaction is spontaneous at all temperatures and K > 1 throughout.",
    choices: [
      { text: "It is spontaneous at every temperature", isCorrect: true },
      { text: "It is spontaneous only when heated" },
      { text: "It is never spontaneous" },
      { text: "It has K < 1 at all temperatures" },
    ],
  },
  {
    stem: "For melting at the normal melting point, ΔG of fusion is exactly zero because the process is:",
    topic: "Free Energy & Spontaneity",
    explanation: "At the melting point solid and liquid coexist in equilibrium, so ΔG_fus = 0 and ΔS_fus = ΔH_fus/T_m. Away from the melting point one phase becomes more stable and ΔG ≠ 0.",
    choices: [
      { text: "At equilibrium between the two phases", isCorrect: true },
      { text: "Strongly exothermic" },
      { text: "Completely irreversible" },
      { text: "Independent of temperature" },
    ],
  },
  {
    stem: "The maximum electrical work a battery can deliver at constant temperature and pressure is equal to:",
    topic: "Free Energy & Spontaneity",
    explanation: "The non-expansion (electrical) work available equals −ΔG at constant T and p. This is why cell potentials are related to Gibbs energies by ΔG = −nFE.",
    choices: [
      { text: "−ΔG of the cell reaction", isCorrect: true },
      { text: "−ΔH of the cell reaction" },
      { text: "+TΔS of the cell reaction" },
      { text: "The heat released, q" },
    ],
  },
  {
    stem: "For a reaction at equilibrium, increasing temperature shifts an exothermic reaction's equilibrium constant so that K:",
    topic: "Free Energy & Spontaneity",
    explanation: "For an exothermic reaction (ΔH < 0), the van 't Hoff equation gives a decreasing K with rising temperature, so raising the temperature reduces the yield of products — consistent with Le Chatelier.",
    choices: [
      { text: "Decreases", isCorrect: true },
      { text: "Increases" },
      { text: "Stays constant" },
      { text: "Becomes infinite" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements linking Gibbs energy to equilibrium are correct? Select all that apply.",
    topic: "Free Energy & Spontaneity",
    explanation: "ΔG° = −RT ln K; ΔG° = 0 gives K = 1; a large negative ΔG° gives a large K; −ΔG is the maximum non-expansion work. A positive ΔG° does not give K > 1 (it gives K < 1).",
    choices: [
      { text: "ΔG° = −RT ln K", isCorrect: true },
      { text: "ΔG° = 0 corresponds to K = 1", isCorrect: true },
      { text: "A large negative ΔG° gives a large K", isCorrect: true },
      { text: "−ΔG is the maximum non-expansion work available", isCorrect: true },
      { text: "A positive ΔG° corresponds to K greater than 1" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which calculations are set up correctly? Select all that apply.",
    topic: "Free Energy & Spontaneity",
    explanation: "ΔG = ΔH − TΔS; crossover T = ΔH/ΔS; ΔS_fus = ΔH_fus/T_m; isothermal ΔS = nR ln(V₂/V₁). The surroundings' entropy change is −ΔH/T, not +ΔH·T.",
    choices: [
      { text: "ΔG = ΔH − TΔS", isCorrect: true },
      { text: "The crossover temperature is ΔH/ΔS", isCorrect: true },
      { text: "ΔS of fusion is ΔH_fus/T_m", isCorrect: true },
      { text: "Isothermal gas entropy change is nR ln(V₂/V₁)", isCorrect: true },
      { text: "The surroundings' entropy change is +ΔH·T" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "A reaction with a large negative standard Gibbs energy change has a large equilibrium constant favouring products.",
    topic: "Free Energy & Spontaneity",
    explanation: "Because ΔG° = −RT ln K, a large negative ΔG° makes ln K large and positive, so K is large and the equilibrium lies far toward products.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "The statistical interpretation of entropy, due to Boltzmann, expresses entropy as:",
    topic: "Entropy & the Second Law",
    explanation: "Boltzmann's equation, S = k ln W, relates entropy to W, the number of microstates consistent with the macrostate. More accessible microstates mean higher entropy.",
    choices: [
      { text: "S = k ln W", isCorrect: true },
      { text: "S = k W" },
      { text: "S = W/k" },
      { text: "S = k/ln W" },
    ],
  },
  {
    stem: "In Boltzmann's entropy equation, the symbol W represents the:",
    topic: "Entropy & the Second Law",
    explanation: "W is the number of microstates (the statistical weight) corresponding to a given macrostate. A state with more ways to arrange its particles and energy has larger W and higher entropy.",
    choices: [
      { text: "Number of accessible microstates", isCorrect: true },
      { text: "Work done by the system" },
      { text: "Molar mass of the substance" },
      { text: "Weight of the sample" },
    ],
  },
  {
    stem: "A spontaneous mixing of two ideal gases at constant temperature and pressure is driven by:",
    topic: "Entropy & the Second Law",
    explanation: "Mixing increases the number of accessible microstates, giving a positive entropy of mixing with no enthalpy change for ideal gases. The rise in entropy alone makes mixing spontaneous.",
    choices: [
      { text: "An increase in entropy (entropy of mixing)", isCorrect: true },
      { text: "A large release of heat" },
      { text: "A decrease in entropy" },
      { text: "A decrease in volume" },
    ],
  },
  {
    stem: "The entropy of mixing of two ideal gases is always:",
    topic: "Entropy & the Second Law",
    explanation: "ΔS_mix = −nR Σ xᵢ ln xᵢ, which is positive because mole fractions are less than one (their logarithms are negative). Mixing therefore always increases entropy.",
    choices: [
      { text: "Positive", isCorrect: true },
      { text: "Negative" },
      { text: "Zero" },
      { text: "Dependent on molar mass" },
    ],
  },
  {
    stem: "An adiabatic reversible process has an entropy change of:",
    topic: "Entropy & the Second Law",
    explanation: "In a reversible adiabatic (isentropic) process, dq_rev = 0, so dS = dq_rev/T = 0. Such processes trace out curves of constant entropy.",
    choices: [
      { text: "Zero", isCorrect: true },
      { text: "A large positive value" },
      { text: "A large negative value" },
      { text: "Equal to nR ln 2" },
    ],
  },
  {
    stem: "A free (irreversible) expansion of an ideal gas into a vacuum has an entropy change that is:",
    topic: "Entropy & the Second Law",
    explanation: "Even though q = 0 for free expansion, entropy is a state function, so ΔS = nR ln(V₂/V₁) > 0 — the same as the reversible path between the same states. Irreversibility generates entropy.",
    choices: [
      { text: "Positive", isCorrect: true },
      { text: "Zero because q = 0" },
      { text: "Negative" },
      { text: "Undefined" },
    ],
  },
  {
    stem: "The efficiency of a real (irreversible) heat engine compared with a Carnot engine between the same reservoirs is:",
    topic: "Carnot Cycle",
    explanation: "Real engines suffer from friction and irreversibility, so their efficiency is always less than the Carnot maximum for the same two reservoir temperatures.",
    choices: [
      { text: "Lower than the Carnot efficiency", isCorrect: true },
      { text: "Higher than the Carnot efficiency" },
      { text: "Exactly equal to it" },
      { text: "Always exactly 100%%" },
    ],
  },
  {
    stem: "A process is described as reversible if it can be reversed by an infinitesimal change and proceeds through states that are:",
    topic: "Entropy & the Second Law",
    explanation: "A reversible process passes through a continuous series of equilibrium states, generating no net entropy in the universe. Real processes are irreversible and always produce some entropy.",
    choices: [
      { text: "Always at equilibrium", isCorrect: true },
      { text: "Far from equilibrium" },
      { text: "At absolute zero" },
      { text: "Chemically inert" },
    ],
  },
  {
    stem: "For an ideal gas, entropy increases with temperature at constant volume because the integrand C_V/T contributes a term proportional to:",
    topic: "Entropy & the Second Law",
    explanation: "Heating at constant volume gives ΔS = C_V ln(T₂/T₁): entropy rises with the logarithm of the temperature ratio as more energy microstates become accessible.",
    choices: [
      { text: "ln(T₂/T₁)", isCorrect: true },
      { text: "(T₂ − T₁)" },
      { text: "(T₂/T₁)²" },
      { text: "1/(T₂ − T₁)" },
    ],
  },
  {
    stem: "The 'heat death' idea associated with the second law refers to the universe tending toward a state of:",
    topic: "Entropy & the Second Law",
    explanation: "Because the entropy of the universe increases, it tends toward maximum entropy — a uniform, equilibrium state with no free energy available to do work. This is the informal 'heat death'.",
    choices: [
      { text: "Maximum entropy and no available free energy", isCorrect: true },
      { text: "Minimum entropy and maximum order" },
      { text: "Absolute zero everywhere immediately" },
      { text: "Constant decrease in total entropy" },
    ],
  },
  {
    stem: "At constant temperature and pressure, the direction of spontaneous change is always toward:",
    topic: "Free Energy & Spontaneity",
    explanation: "Systems move spontaneously toward lower Gibbs energy, reaching equilibrium at the minimum of G. This single criterion accounts for both enthalpy and entropy effects at constant T and p.",
    choices: [
      { text: "Lower Gibbs free energy", isCorrect: true },
      { text: "Higher Gibbs free energy" },
      { text: "Higher enthalpy always" },
      { text: "Lower entropy always" },
    ],
  },
  {
    stem: "The negative sign in the relation (∂G/∂T)_p = −S means that, as temperature rises, the Gibbs energy of a substance:",
    topic: "Thermodynamic Relations",
    explanation: "Since S is positive, (∂G/∂T)_p = −S is negative, so G falls as temperature increases. The decrease is steepest for gases, which have the largest entropies.",
    choices: [
      { text: "Decreases", isCorrect: true },
      { text: "Increases" },
      { text: "Stays constant" },
      { text: "Becomes infinite" },
    ],
  },
  {
    stem: "Gases contribute more to the entropy of a system than solids or liquids mainly because they have far more accessible:",
    topic: "Entropy & the Second Law",
    explanation: "Gases have vastly more translational (positional and momentum) microstates than condensed phases, giving them much larger molar entropies. This is why reactions producing gas usually have ΔS > 0.",
    choices: [
      { text: "Translational microstates", isCorrect: true },
      { text: "Chemical bonds" },
      { text: "Electrons per atom" },
      { text: "Protons per nucleus" },
    ],
  },
  {
    stem: "At the boiling point of a liquid, the Gibbs energy change of vaporisation is:",
    topic: "Free Energy & Spontaneity",
    explanation: "At the normal boiling point liquid and vapour are in equilibrium, so ΔG_vap = 0 and ΔS_vap = ΔH_vap/T_b. Above the boiling point the vapour is the more stable phase.",
    choices: [
      { text: "Zero (the phases are in equilibrium)", isCorrect: true },
      { text: "Large and negative" },
      { text: "Large and positive" },
      { text: "Equal to ΔH_vap" },
    ],
  },
  {
    stem: "Which quantity must increase for any process occurring in an isolated system?",
    topic: "Entropy & the Second Law",
    explanation: "In an isolated system the only spontaneous direction is one of increasing entropy; the total entropy rises until equilibrium. Energy is conserved (constant), not increased.",
    choices: [
      { text: "The entropy of the system", isCorrect: true },
      { text: "The internal energy of the system" },
      { text: "The enthalpy of the system" },
      { text: "The temperature of the system" },
    ],
  },
  {
    stem: "The 'unavailability' of some energy to do work, as temperature increases, is quantified by the term:",
    topic: "Free Energy & Spontaneity",
    explanation: "The TΔS term in ΔG = ΔH − TΔS represents energy that is dispersed and unavailable for non-expansion work. Only ΔG (not the full ΔH) is convertible to useful work at constant T and p.",
    choices: [
      { text: "TΔS", isCorrect: true },
      { text: "ΔH alone" },
      { text: "pΔV only" },
      { text: "nRT ln K" },
    ],
  },
  {
    stem: "For a reaction carried out reversibly at constant temperature, the heat exchanged with the surroundings equals:",
    topic: "Entropy & the Second Law",
    explanation: "For a reversible isothermal change, q_rev = TΔS. This reversible heat, divided by T, gives the true entropy change of the system.",
    choices: [
      { text: "TΔS", isCorrect: true },
      { text: "ΔH − TΔS" },
      { text: "ΔG of the reaction" },
      { text: "Zero always" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about reversible and irreversible processes are correct? Select all that apply.",
    topic: "Entropy & the Second Law",
    explanation: "A reversible process gives ΔS_univ = 0 and passes through equilibrium states; a reversible adiabatic step is isentropic; free expansion still raises entropy; real engines fall short of Carnot efficiency. Irreversible processes generate entropy, they don't conserve it.",
    choices: [
      { text: "A reversible process has ΔS_universe = 0", isCorrect: true },
      { text: "A reversible adiabatic step has ΔS = 0", isCorrect: true },
      { text: "Free expansion into a vacuum increases entropy", isCorrect: true },
      { text: "Real engines are less efficient than a Carnot engine", isCorrect: true },
      { text: "Irreversible processes conserve the entropy of the universe" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "Boltzmann's equation S = k ln W links a system's entropy to the number of microstates W available to it, so a state with more accessible microstates has higher entropy.",
    topic: "Entropy & the Second Law",
    explanation: "The statistical definition S = k ln W shows entropy rising with the logarithm of the number of microstates; greater molecular disorder (more microstates) corresponds to greater entropy.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "The entropy change for the free expansion of an ideal gas into a vacuum is zero because no heat is exchanged.",
    topic: "Entropy & the Second Law",
    explanation: "This is false: although q = 0, entropy is a state function, so ΔS = nR ln(V₂/V₁) > 0 — identical to the reversible path between the same initial and final states.",
    choices: [
      { text: "True" },
      { text: "False", isCorrect: true },
    ],
  },
];
