import type { Q } from "../_lib/qbank";

export const PHYSICAL_SET_4: Q[] = [
  {
    stem: "A phase diagram plots the conditions under which each phase of a substance is stable, using the axes:",
    topic: "Phase Diagrams",
    explanation: "A one-component phase diagram plots pressure against temperature, with regions for solid, liquid and gas separated by coexistence lines. Each point specifies the stable phase at that p and T.",
    choices: [
      { text: "Pressure versus temperature", isCorrect: true },
      { text: "Volume versus mass" },
      { text: "Entropy versus enthalpy" },
      { text: "Concentration versus time" },
    ],
  },
  {
    stem: "On a phase diagram, a line separating two phase regions represents conditions where the two phases are:",
    topic: "Phase Diagrams",
    explanation: "A coexistence (phase boundary) line marks the p, T values at which two phases are in equilibrium. Along it, the molar Gibbs energies of the two phases are equal.",
    choices: [
      { text: "In mutual equilibrium", isCorrect: true },
      { text: "Both unstable" },
      { text: "Chemically reacting" },
      { text: "At absolute zero" },
    ],
  },
  {
    stem: "The triple point of a substance is the unique temperature and pressure at which:",
    topic: "Phase Diagrams",
    explanation: "The triple point is where solid, liquid and gas coexist in equilibrium simultaneously — a single fixed point on the phase diagram, invariant for a pure substance.",
    choices: [
      { text: "Solid, liquid and gas coexist", isCorrect: true },
      { text: "Only solid and liquid coexist" },
      { text: "The substance becomes an ideal gas" },
      { text: "The liquid boils under vacuum" },
    ],
  },
  {
    stem: "Above the critical point of a substance, the liquid and gas phases:",
    topic: "Phase Diagrams",
    explanation: "Beyond the critical temperature and pressure, liquid and gas become indistinguishable, forming a single supercritical fluid. The liquid–gas coexistence line ends at the critical point.",
    choices: [
      { text: "Merge into a single supercritical fluid", isCorrect: true },
      { text: "Separate into two distinct liquids" },
      { text: "Both freeze into solids" },
      { text: "Cannot exist at all" },
    ],
  },
  {
    stem: "Water's phase diagram is unusual because its solid–liquid boundary has a:",
    topic: "Phase Diagrams",
    explanation: "The ice–water line slopes negatively (to the left): increasing pressure lowers the melting point, because ice is less dense than liquid water. Most substances show the opposite (positive) slope.",
    choices: [
      { text: "Negative slope", isCorrect: true },
      { text: "Positive slope like most substances" },
      { text: "Vertical, pressure-independent boundary" },
      { text: "A perfectly horizontal boundary" },
    ],
  },
  {
    stem: "The Gibbs phase rule for a system at equilibrium is:",
    topic: "The Phase Rule",
    explanation: "The phase rule is F = C − P + 2, relating the number of degrees of freedom F to the components C and phases P. The '2' accounts for temperature and pressure.",
    choices: [
      { text: "F = C − P + 2", isCorrect: true },
      { text: "F = C + P − 2" },
      { text: "F = P − C + 2" },
      { text: "F = C − P − 2" },
    ],
  },
  {
    stem: "For a single pure substance (one component) at its triple point, the number of degrees of freedom is:",
    topic: "The Phase Rule",
    explanation: "With C = 1 and three coexisting phases (P = 3), F = 1 − 3 + 2 = 0. The triple point is invariant — fixed at one temperature and one pressure.",
    choices: [
      { text: "0 (invariant)", isCorrect: true },
      { text: "1" },
      { text: "2" },
      { text: "3" },
    ],
  },
  {
    stem: "For a one-component system with a single phase present, the number of degrees of freedom is:",
    topic: "The Phase Rule",
    explanation: "With C = 1 and P = 1, F = 1 − 1 + 2 = 2. Both temperature and pressure can be varied independently while remaining within the single-phase region.",
    choices: [
      { text: "2", isCorrect: true },
      { text: "0" },
      { text: "1" },
      { text: "3" },
    ],
  },
  {
    stem: "Along a two-phase coexistence line of a one-component system, the number of degrees of freedom is:",
    topic: "The Phase Rule",
    explanation: "With C = 1 and two phases in equilibrium (P = 2), F = 1 − 2 + 2 = 1. Only one variable is independent: fixing the temperature fixes the pressure along the line.",
    choices: [
      { text: "1", isCorrect: true },
      { text: "0" },
      { text: "2" },
      { text: "3" },
    ],
  },
  {
    stem: "In the phase rule F = C − P + 2, the term C (the number of components) is the:",
    topic: "The Phase Rule",
    explanation: "C is the minimum number of independent chemical species needed to specify the composition of every phase. For pure water C = 1; for a salt-water mixture C = 2.",
    choices: [
      { text: "Number of independent species", isCorrect: true },
      { text: "The total number of atoms present in all phases" },
      { text: "Number of phases present" },
      { text: "Number of molecules per unit cell" },
    ],
  },
  {
    stem: "Sublimation corresponds to crossing which boundary on a phase diagram?",
    topic: "Phase Diagrams",
    explanation: "Sublimation is the direct solid-to-gas transition, occurring along the solid–gas coexistence line, which lies below the triple-point pressure. Carbon dioxide sublimes at 1 atm for this reason.",
    choices: [
      { text: "The solid–gas boundary", isCorrect: true },
      { text: "The liquid–gas boundary" },
      { text: "The solid–liquid boundary" },
      { text: "The critical isotherm" },
    ],
  },
  {
    stem: "Carbon dioxide sublimes rather than melts at ordinary atmospheric pressure because its triple point lies:",
    topic: "Phase Diagrams",
    explanation: "CO₂'s triple point is at about 5.1 atm, above 1 atm. At 1 atm the liquid phase is not stable, so solid CO₂ (dry ice) passes directly to gas — it sublimes.",
    choices: [
      { text: "Above atmospheric pressure", isCorrect: true },
      { text: "Below atmospheric pressure" },
      { text: "Exactly at 1 atm" },
      { text: "At absolute zero" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about phase diagrams are correct? Select all that apply.",
    topic: "Phase Diagrams",
    explanation: "Phase diagrams plot p vs T; boundary lines mark two-phase equilibrium; the triple point has all three phases; above the critical point a supercritical fluid forms. Water's solid–liquid line slopes negatively, not positively.",
    choices: [
      { text: "They plot pressure against temperature", isCorrect: true },
      { text: "A boundary line marks two phases in equilibrium", isCorrect: true },
      { text: "The triple point has solid, liquid and gas coexisting", isCorrect: true },
      { text: "Above the critical point a supercritical fluid exists", isCorrect: true },
      { text: "Water's solid–liquid boundary has a positive slope" },
    ],
  },
  {
    type: "MULTI",
    stem: "Using the phase rule F = C − P + 2 for a one-component system, which are correct? Select all that apply.",
    topic: "The Phase Rule",
    explanation: "Single phase: F = 2; two-phase line: F = 1; triple point: F = 0. The triple point is invariant. A one-component system cannot have four phases coexisting at equilibrium (F would be negative).",
    choices: [
      { text: "A single phase gives F = 2", isCorrect: true },
      { text: "A two-phase line gives F = 1", isCorrect: true },
      { text: "The triple point gives F = 0", isCorrect: true },
      { text: "The triple point is invariant", isCorrect: true },
      { text: "Four phases can coexist for one component" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "At the triple point of a pure substance, solid, liquid and gas coexist in equilibrium, and the system has zero degrees of freedom.",
    topic: "The Phase Rule",
    explanation: "With C = 1 and P = 3, the phase rule gives F = 1 − 3 + 2 = 0, so the triple point is fixed at a single temperature and pressure — it is invariant.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "The Clapeyron equation gives the slope of a phase-boundary line, dp/dT, as:",
    topic: "Clausius–Clapeyron",
    explanation: "The Clapeyron equation is dp/dT = ΔS_trans/ΔV_trans = ΔH_trans/(TΔV_trans). It applies to any two-phase coexistence line for a pure substance.",
    choices: [
      { text: "ΔH_trans/(TΔV_trans)", isCorrect: true },
      { text: "ΔV_trans/(TΔH_trans)" },
      { text: "TΔH_trans/ΔV_trans" },
      { text: "ΔH_trans·TΔV_trans" },
    ],
  },
  {
    stem: "The Clausius–Clapeyron equation, applied to liquid–vapour equilibrium, assumes the vapour behaves ideally and that:",
    topic: "Clausius–Clapeyron",
    explanation: "It approximates ΔV_vap by the vapour's molar volume (neglecting the liquid's) and treats the vapour as ideal, giving d(ln p)/dT = ΔH_vap/(RT²).",
    choices: [
      { text: "The liquid's molar volume is negligible", isCorrect: true },
      { text: "The enthalpy of vaporisation is zero" },
      { text: "The temperature is constant" },
      { text: "The vapour has zero pressure" },
    ],
  },
  {
    stem: "The integrated Clausius–Clapeyron equation relating vapour pressures at two temperatures is:",
    topic: "Clausius–Clapeyron",
    explanation: "ln(p₂/p₁) = −(ΔH_vap/R)(1/T₂ − 1/T₁). It lets the vapour pressure at one temperature be found from its value at another, given ΔH_vap.",
    choices: [
      { text: "ln(p₂/p₁) = −(ΔH_vap/R)(1/T₂ − 1/T₁)", isCorrect: true },
      { text: "ln(p₂/p₁) = (R/ΔH_vap)(T₂ − T₁)" },
      { text: "p₂/p₁ = ΔH_vap(T₂ − T₁)" },
      { text: "ln(p₂/p₁) = ΔH_vap·R·T" },
    ],
  },
  {
    stem: "According to the Clausius–Clapeyron equation, the vapour pressure of a liquid increases with temperature:",
    topic: "Clausius–Clapeyron",
    explanation: "Because d(ln p)/dT = ΔH_vap/(RT²) is positive, vapour pressure rises with temperature — and does so exponentially, since ln p is roughly linear in −1/T.",
    choices: [
      { text: "Exponentially", isCorrect: true },
      { text: "Linearly" },
      { text: "Not at all" },
      { text: "Inversely" },
    ],
  },
  {
    stem: "A liquid boils when its vapour pressure becomes equal to the:",
    topic: "Clausius–Clapeyron",
    explanation: "Boiling occurs when the liquid's saturated vapour pressure equals the external (atmospheric) pressure, allowing bubbles of vapour to form throughout the liquid.",
    choices: [
      { text: "External pressure", isCorrect: true },
      { text: "Critical pressure" },
      { text: "Triple-point pressure" },
      { text: "Osmotic pressure" },
    ],
  },
  {
    stem: "At higher altitude, where atmospheric pressure is lower, water boils at a temperature that is:",
    topic: "Clausius–Clapeyron",
    explanation: "Lower external pressure is matched by the liquid's vapour pressure at a lower temperature, so water boils below 100 °C at altitude. This is why cooking takes longer on high mountains.",
    choices: [
      { text: "Lower than 100 °C", isCorrect: true },
      { text: "Higher than 100 °C" },
      { text: "Exactly 100 °C regardless" },
      { text: "Equal to the critical temperature" },
    ],
  },
  {
    stem: "A plot of ln(vapour pressure) against 1/T for a liquid is approximately linear, with a slope equal to:",
    topic: "Clausius–Clapeyron",
    explanation: "From ln p = −(ΔH_vap/R)(1/T) + constant, the slope of ln p versus 1/T is −ΔH_vap/R, providing an experimental route to the enthalpy of vaporisation.",
    choices: [
      { text: "−ΔH_vap/R", isCorrect: true },
      { text: "+ΔH_vap/R" },
      { text: "−R/ΔH_vap" },
      { text: "+ΔH_vap·R" },
    ],
  },
  {
    stem: "The steep positive slope of the solid–liquid line on most phase diagrams reflects that fusion has a:",
    topic: "Clausius–Clapeyron",
    explanation: "For fusion, ΔV is small, so dp/dT = ΔH_fus/(TΔV_fus) is large — the solid–liquid line is nearly vertical (steep). Its sign follows the sign of ΔV_fus.",
    choices: [
      { text: "Small volume change (ΔV_fus)", isCorrect: true },
      { text: "Very large volume change" },
      { text: "Zero enthalpy change" },
      { text: "Negative enthalpy of fusion" },
    ],
  },
  {
    stem: "Applying the Clapeyron equation to the ice–water line, the negative slope arises because for water:",
    topic: "Clausius–Clapeyron",
    explanation: "Water expands on freezing, so the molar volume of ice exceeds that of liquid water: ΔV_fus < 0. With ΔH_fus > 0, dp/dT = ΔH_fus/(TΔV_fus) is negative, giving the leftward slope.",
    choices: [
      { text: "The liquid is denser than the solid", isCorrect: true },
      { text: "The solid is denser than the liquid" },
      { text: "The enthalpy of fusion is negative" },
      { text: "The vapour pressure drops to zero" },
    ],
  },
  {
    stem: "For sublimation, the relevant enthalpy in the Clausius–Clapeyron treatment is the enthalpy of:",
    topic: "Clausius–Clapeyron",
    explanation: "The solid–gas line uses the enthalpy of sublimation, ΔH_sub = ΔH_fus + ΔH_vap. Because sublimation involves the largest enthalpy, the solid–gas line is steeper than the liquid–gas line near the triple point.",
    choices: [
      { text: "Sublimation", isCorrect: true },
      { text: "Fusion only" },
      { text: "Neutralisation" },
      { text: "Combustion" },
    ],
  },
  {
    stem: "If the enthalpy of vaporisation of a liquid is large, its vapour pressure at a given temperature tends to be:",
    topic: "Clausius–Clapeyron",
    explanation: "A large ΔH_vap reflects strong intermolecular forces holding molecules in the liquid, so fewer escape and the vapour pressure is comparatively low at a given temperature.",
    choices: [
      { text: "Comparatively low", isCorrect: true },
      { text: "Comparatively high" },
      { text: "Independent of ΔH_vap" },
      { text: "Exactly 1 atm" },
    ],
  },
  {
    stem: "A pressure cooker raises the boiling point of water by:",
    topic: "Clausius–Clapeyron",
    explanation: "Sealing the vessel lets pressure build above atmospheric, so the vapour pressure must reach a higher value to boil — raising the boiling temperature and cooking food faster.",
    choices: [
      { text: "Increasing the pressure above the liquid", isCorrect: true },
      { text: "Lowering the external pressure" },
      { text: "Removing all the water vapour" },
      { text: "Adding a non-volatile solute only" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about the Clausius–Clapeyron equation and vapour pressure are correct? Select all that apply.",
    topic: "Clausius–Clapeyron",
    explanation: "d(ln p)/dT = ΔH_vap/(RT²); vapour pressure rises exponentially with T; a ln p vs 1/T plot has slope −ΔH_vap/R; boiling occurs when vapour pressure equals external pressure. Vapour pressure does not fall as temperature rises.",
    choices: [
      { text: "d(ln p)/dT = ΔH_vap/(RT²)", isCorrect: true },
      { text: "Vapour pressure increases roughly exponentially with temperature", isCorrect: true },
      { text: "A plot of ln p vs 1/T has slope −ΔH_vap/R", isCorrect: true },
      { text: "Boiling occurs when vapour pressure equals external pressure", isCorrect: true },
      { text: "Vapour pressure decreases as temperature rises" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about phase-boundary slopes (Clapeyron equation) are correct? Select all that apply.",
    topic: "Clausius–Clapeyron",
    explanation: "dp/dT = ΔH/(TΔV); the small ΔV of fusion makes the solid–liquid line steep; water's ice–liquid slope is negative because ice is less dense; sublimation uses ΔH_sub = ΔH_fus + ΔH_vap. The solid–liquid slope is not always negative — it's negative only for water-like substances.",
    choices: [
      { text: "dp/dT = ΔH_trans/(TΔV_trans)", isCorrect: true },
      { text: "The small ΔV of fusion makes the solid–liquid line steep", isCorrect: true },
      { text: "Water's solid–liquid slope is negative (ice less dense)", isCorrect: true },
      { text: "Sublimation uses ΔH_sub = ΔH_fus + ΔH_vap", isCorrect: true },
      { text: "The solid–liquid slope is negative for all substances" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "According to the Clausius–Clapeyron equation, lowering the external pressure lowers the boiling point of a liquid.",
    topic: "Clausius–Clapeyron",
    explanation: "Boiling occurs when vapour pressure equals the external pressure; at lower external pressure that equality is reached at a lower temperature, so the boiling point drops (as at high altitude).",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "Raoult's law states that the partial vapour pressure of a component in an ideal solution equals:",
    topic: "Solutions & Raoult's Law",
    explanation: "Raoult's law: pᵢ = xᵢ·pᵢ*, the mole fraction of the component times its pure vapour pressure. An ideal solution obeys this over the whole composition range.",
    choices: [
      { text: "Mole fraction times pure vapour pressure", isCorrect: true },
      { text: "Its pure vapour pressure alone, unscaled" },
      { text: "The total pressure divided by two" },
      { text: "Its molar mass times pressure" },
    ],
  },
  {
    stem: "An ideal solution is one in which the interactions between unlike molecules are:",
    topic: "Solutions & Raoult's Law",
    explanation: "In an ideal solution, A–B interactions are essentially the same as A–A and B–B interactions, so mixing has zero enthalpy and the solution obeys Raoult's law across all compositions.",
    choices: [
      { text: "The same as those between like molecules", isCorrect: true },
      { text: "Much stronger than like–like interactions" },
      { text: "Completely absent" },
      { text: "Always repulsive" },
    ],
  },
  {
    stem: "A non-volatile solute lowers the vapour pressure of a solvent because the solute:",
    topic: "Solutions & Raoult's Law",
    explanation: "By Raoult's law, adding solute lowers the solvent's mole fraction, so its vapour pressure falls proportionally. The reduced escaping tendency underlies the colligative properties.",
    choices: [
      { text: "Reduces the mole fraction of the solvent", isCorrect: true },
      { text: "Increases the solvent's pure vapour pressure" },
      { text: "Raises the temperature of the solution" },
      { text: "Adds its own large vapour pressure" },
    ],
  },
  {
    stem: "Henry's law describes the solubility of a gas in a liquid, stating that the amount dissolved is proportional to the:",
    topic: "Solutions & Raoult's Law",
    explanation: "Henry's law: the concentration (or mole fraction) of a dissolved gas is proportional to its partial pressure above the solution, p = K_H·x. It governs dilute solutions of gases.",
    choices: [
      { text: "Partial pressure of the gas", isCorrect: true },
      { text: "Temperature of the liquid only" },
      { text: "Molar mass of the solvent" },
      { text: "Vapour pressure of the pure solvent" },
    ],
  },
  {
    stem: "A positive deviation from Raoult's law occurs when interactions between unlike molecules are:",
    topic: "Solutions & Raoult's Law",
    explanation: "Weaker A–B interactions than A–A/B–B let molecules escape more readily, raising the vapour pressure above the Raoult prediction — a positive deviation, with endothermic mixing.",
    choices: [
      { text: "Weaker than those between like molecules", isCorrect: true },
      { text: "Stronger than those between like molecules" },
      { text: "Exactly equal to like–like interactions" },
      { text: "Purely ionic" },
    ],
  },
  {
    stem: "A colligative property is one that depends on the:",
    topic: "Colligative Properties",
    explanation: "Colligative properties depend on the number (concentration) of solute particles, not their chemical identity. Examples are vapour-pressure lowering, boiling-point elevation, freezing-point depression, and osmotic pressure.",
    choices: [
      { text: "The number of solute particles", isCorrect: true },
      { text: "Chemical identity of the solute" },
      { text: "The colour of the final solution" },
      { text: "Molar mass of the solvent only" },
    ],
  },
  {
    stem: "Boiling-point elevation of a solution is given by ΔT_b =:",
    topic: "Colligative Properties",
    explanation: "ΔT_b = K_b·m, where K_b is the ebullioscopic constant and m the molality. A non-volatile solute raises the boiling point in proportion to solute concentration.",
    choices: [
      { text: "K_b·m", isCorrect: true },
      { text: "The ratio K_b/m" },
      { text: "The product K_b·m²" },
      { text: "The ratio m/K_b" },
    ],
  },
  {
    stem: "Freezing-point depression is given by ΔT_f =:",
    topic: "Colligative Properties",
    explanation: "ΔT_f = K_f·m, with K_f the cryoscopic constant and m the molality. Dissolved solute lowers the freezing point — the basis of salting icy roads and using antifreeze.",
    choices: [
      { text: "K_f·m", isCorrect: true },
      { text: "The ratio K_f/m" },
      { text: "The product K_f·m²" },
      { text: "The difference m − K_f" },
    ],
  },
  {
    stem: "Osmotic pressure of a dilute solution is given by the van 't Hoff expression:",
    topic: "Colligative Properties",
    explanation: "Π = cRT (equivalently Π = (n/V)RT), analogous to the ideal gas law. Osmotic pressure is the pressure needed to stop solvent flowing across a semipermeable membrane into the solution.",
    choices: [
      { text: "Π = cRT", isCorrect: true },
      { text: "Π = cRT²" },
      { text: "Π = RT/c" },
      { text: "Π = c/RT" },
    ],
  },
  {
    stem: "For an electrolyte such as NaCl, colligative effects are enhanced by the van 't Hoff factor i, which accounts for the:",
    topic: "Colligative Properties",
    explanation: "The van 't Hoff factor i is the number of particles produced per formula unit on dissolving (≈2 for NaCl, ≈3 for CaCl₂). Colligative formulae become ΔT = i·K·m, since particle count is what matters.",
    choices: [
      { text: "Particles produced per formula unit", isCorrect: true },
      { text: "Molar mass of the electrolyte" },
      { text: "The colour of the dissolved ions" },
      { text: "Charge on the solvent" },
    ],
  },
  {
    stem: "Osmosis is the net movement of solvent across a semipermeable membrane from a region of:",
    topic: "Colligative Properties",
    explanation: "Solvent flows from lower solute concentration (higher solvent activity) to higher solute concentration, tending to equalise concentrations. Osmotic pressure opposes and can halt this flow.",
    choices: [
      { text: "Low to high solute concentration", isCorrect: true },
      { text: "High solute to low solute concentration" },
      { text: "High pressure to low pressure only" },
      { text: "Colder regions to hotter regions" },
    ],
  },
  {
    stem: "Measuring osmotic pressure is especially useful for determining the molar mass of large molecules because osmotic pressure is:",
    topic: "Colligative Properties",
    explanation: "Even small molar concentrations of macromolecules give measurable osmotic pressures, so osmometry is sensitive for large molar masses (e.g. polymers, proteins) where other colligative effects are too small.",
    choices: [
      { text: "Large and easy to measure", isCorrect: true },
      { text: "Completely independent of concentration" },
      { text: "Zero for macromolecules" },
      { text: "Only ever measurable for gases" },
    ],
  },
  {
    stem: "The activity of a component replaces its concentration in real (non-ideal) solutions and is defined as:",
    topic: "Activities & Real Solutions",
    explanation: "Activity is aᵢ = γᵢ·xᵢ, the activity coefficient times the mole fraction (or concentration). It is the 'effective' concentration that makes thermodynamic equations valid for non-ideal solutions.",
    choices: [
      { text: "Activity coefficient times mole fraction", isCorrect: true },
      { text: "Mole fraction divided by pressure" },
      { text: "Molar mass times concentration" },
      { text: "The pressure times the volume" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about Raoult's and Henry's laws are correct? Select all that apply.",
    topic: "Solutions & Raoult's Law",
    explanation: "Raoult: pᵢ = xᵢpᵢ*; ideal solutions obey it with zero mixing enthalpy; a non-volatile solute lowers solvent vapour pressure; Henry: dissolved gas ∝ partial pressure. Positive deviations come from weaker (not stronger) unlike interactions.",
    choices: [
      { text: "Raoult's law: pᵢ = xᵢ·pᵢ*", isCorrect: true },
      { text: "An ideal solution has zero enthalpy of mixing", isCorrect: true },
      { text: "A non-volatile solute lowers the solvent's vapour pressure", isCorrect: true },
      { text: "Henry's law: dissolved gas is proportional to its partial pressure", isCorrect: true },
      { text: "Positive deviations arise from stronger unlike-molecule interactions" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which are colligative properties? Select all that apply.",
    topic: "Colligative Properties",
    explanation: "Vapour-pressure lowering, boiling-point elevation, freezing-point depression, and osmotic pressure all depend on the number of solute particles. Solution colour depends on the solute's identity, so it is not colligative.",
    choices: [
      { text: "Vapour-pressure lowering", isCorrect: true },
      { text: "Boiling-point elevation", isCorrect: true },
      { text: "Freezing-point depression", isCorrect: true },
      { text: "Osmotic pressure", isCorrect: true },
      { text: "The colour of the solution" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "Colligative properties depend on the number of dissolved solute particles rather than on their chemical identity.",
    topic: "Colligative Properties",
    explanation: "By definition, colligative properties (vapour-pressure lowering, boiling-point elevation, freezing-point depression, osmotic pressure) scale with the concentration of solute particles, not what those particles are.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "The chemical potential of a component is the partial molar Gibbs energy, defined as the change in G when:",
    topic: "Partial Molar Quantities",
    explanation: "The chemical potential μᵢ = (∂G/∂nᵢ) is the change in Gibbs energy per mole of component i added at constant T, p and other amounts. It is the driving quantity for phase and reaction equilibria.",
    choices: [
      { text: "A mole of it is added at constant T, p", isCorrect: true },
      { text: "The temperature is raised by one degree" },
      { text: "The volume is doubled" },
      { text: "One mole of solvent evaporates" },
    ],
  },
  {
    stem: "At equilibrium between two phases, the chemical potential of each component is:",
    topic: "Partial Molar Quantities",
    explanation: "Phase equilibrium requires that each component's chemical potential be equal in all phases present. If they differed, matter would flow from high to low potential until equality.",
    choices: [
      { text: "Equal in both phases", isCorrect: true },
      { text: "Larger in the denser phase" },
      { text: "Zero in one of the phases" },
      { text: "Different in the two phases" },
    ],
  },
  {
    stem: "The partial molar volume of a component in a mixture is the change in total volume when:",
    topic: "Partial Molar Quantities",
    explanation: "The partial molar volume V̄ᵢ = (∂V/∂nᵢ) is the volume change on adding one mole of i to a large amount of the mixture at constant T, p. It can even be negative (e.g. MgSO₄ in water).",
    choices: [
      { text: "One mole is added to the mixture", isCorrect: true },
      { text: "The temperature of the mixture is doubled" },
      { text: "The pressure is halved" },
      { text: "The whole mixture is frozen" },
    ],
  },
  {
    stem: "For an ideal solution, the enthalpy of mixing and the volume of mixing are both:",
    topic: "Solutions & Raoult's Law",
    explanation: "Ideal mixing has ΔH_mix = 0 and ΔV_mix = 0, because unlike interactions match like interactions. The only driving force is the positive entropy of mixing.",
    choices: [
      { text: "Zero", isCorrect: true },
      { text: "Large and positive" },
      { text: "Large and negative" },
      { text: "Equal to RT" },
    ],
  },
  {
    stem: "The Gibbs energy of mixing for an ideal solution is negative because of the:",
    topic: "Solutions & Raoult's Law",
    explanation: "ΔG_mix = ΔH_mix − TΔS_mix = −TΔS_mix (since ΔH_mix = 0). The positive entropy of mixing makes ΔG_mix negative, so mixing is always spontaneous for an ideal solution.",
    choices: [
      { text: "Positive entropy of mixing", isCorrect: true },
      { text: "Large negative enthalpy of mixing" },
      { text: "Decrease in temperature" },
      { text: "Increase in pressure" },
    ],
  },
  {
    stem: "A negative deviation from Raoult's law is associated with mixing that is:",
    topic: "Solutions & Raoult's Law",
    explanation: "Stronger A–B interactions than like–like interactions hold molecules more tightly, lowering vapour pressure below the Raoult line (negative deviation) and releasing heat (exothermic mixing).",
    choices: [
      { text: "Exothermic; stronger unlike interactions", isCorrect: true },
      { text: "Endothermic, with weaker unlike interactions" },
      { text: "Athermal (zero heat) in every case" },
      { text: "Accompanied by a large volume increase" },
    ],
  },
  {
    stem: "An azeotrope is a mixture that, on boiling, produces vapour with a composition:",
    topic: "Solutions & Raoult's Law",
    explanation: "At an azeotrope the vapour and liquid have identical compositions, so the mixture boils at constant temperature and cannot be further separated by simple distillation.",
    choices: [
      { text: "Identical to that of the liquid", isCorrect: true },
      { text: "Always pure in one component" },
      { text: "Richer in the non-volatile solute" },
      { text: "Independent of the liquid composition" },
    ],
  },
  {
    stem: "Fractional distillation separates two miscible volatile liquids by exploiting their difference in:",
    topic: "Solutions & Raoult's Law",
    explanation: "Because the more volatile component is enriched in the vapour, repeated vaporisation–condensation on a fractionating column progressively separates liquids that differ in volatility (boiling point).",
    choices: [
      { text: "Volatility", isCorrect: true },
      { text: "Their colour" },
      { text: "Molar mass only" },
      { text: "Their density only" },
    ],
  },
  {
    stem: "A solution that obeys Raoult's law over the entire composition range is termed:",
    topic: "Solutions & Raoult's Law",
    explanation: "Such a solution is 'ideal' — its components mix with no enthalpy or volume change, and each partial pressure follows pᵢ = xᵢpᵢ* at all compositions.",
    choices: [
      { text: "Ideal", isCorrect: true },
      { text: "Azeotropic" },
      { text: "Saturated" },
      { text: "Supercritical" },
    ],
  },
  {
    stem: "When a solute dissolves such that the solution is saturated, the dissolved solute is in equilibrium with:",
    topic: "Solutions & Raoult's Law",
    explanation: "A saturated solution is in dynamic equilibrium with undissolved (excess) solute; the rates of dissolving and crystallising are equal, and the concentration is the solubility limit.",
    choices: [
      { text: "Undissolved excess solute", isCorrect: true },
      { text: "Pure solvent vapour only" },
      { text: "A second immiscible liquid" },
      { text: "The container walls" },
    ],
  },
  {
    stem: "The molality of a solution, used in colligative formulae, is defined as moles of solute per:",
    topic: "Colligative Properties",
    explanation: "Molality is moles of solute per kilogram of solvent. It is preferred for colligative properties because, unlike molarity, it does not change with temperature (mass is temperature-independent).",
    choices: [
      { text: "Kilogram of solvent", isCorrect: true },
      { text: "Litre of solution" },
      { text: "Mole of solution" },
      { text: "Square metre of surface" },
    ],
  },
  {
    stem: "Molality is preferred over molarity for colligative measurements because molality does not depend on:",
    topic: "Colligative Properties",
    explanation: "Molality uses solvent mass, which is independent of temperature, whereas molarity uses solution volume, which expands or contracts with temperature. So molality gives temperature-stable results.",
    choices: [
      { text: "Temperature", isCorrect: true },
      { text: "The identity of the solute" },
      { text: "The number of particles" },
      { text: "The mass of solute" },
    ],
  },
  {
    stem: "Adding antifreeze (ethylene glycol) to a car radiator both lowers the freezing point and raises the boiling point of the water because these are:",
    topic: "Colligative Properties",
    explanation: "Both freezing-point depression and boiling-point elevation are colligative effects of the dissolved glycol, widening the liquid range so the coolant resists both freezing and boiling.",
    choices: [
      { text: "Colligative effects of the dissolved solute", isCorrect: true },
      { text: "Due to the colour of the antifreeze" },
      { text: "Caused by a chemical reaction with water" },
      { text: "Independent of solute concentration" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about partial molar quantities and chemical potential are correct? Select all that apply.",
    topic: "Partial Molar Quantities",
    explanation: "Chemical potential is the partial molar Gibbs energy (∂G/∂nᵢ); at equilibrium it is equal across phases; partial molar volume is (∂V/∂nᵢ) and can be negative; ideal mixing has ΔH_mix = ΔV_mix = 0. Chemical potentials are not equal to zero at equilibrium — they are equal to each other.",
    choices: [
      { text: "Chemical potential is the partial molar Gibbs energy", isCorrect: true },
      { text: "At equilibrium, a component's chemical potential is equal in all phases", isCorrect: true },
      { text: "Partial molar volume is (∂V/∂nᵢ) and can be negative", isCorrect: true },
      { text: "Ideal mixing has zero enthalpy and volume of mixing", isCorrect: true },
      { text: "At equilibrium every chemical potential equals zero" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about ideal and non-ideal solutions are correct? Select all that apply.",
    topic: "Solutions & Raoult's Law",
    explanation: "Ideal solutions obey Raoult's law throughout; ΔG_mix is negative from the entropy of mixing; positive deviations come from weaker unlike interactions (endothermic); azeotropes boil with identical vapour and liquid compositions. Negative deviations are exothermic, not endothermic.",
    choices: [
      { text: "An ideal solution obeys Raoult's law at all compositions", isCorrect: true },
      { text: "ΔG_mix is negative because of the entropy of mixing", isCorrect: true },
      { text: "Positive deviations arise from weaker unlike interactions", isCorrect: true },
      { text: "An azeotrope has identical vapour and liquid compositions", isCorrect: true },
      { text: "Negative deviations from Raoult's law are endothermic" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "At equilibrium between phases, each component has the same chemical potential in every phase in which it is present.",
    topic: "Partial Molar Quantities",
    explanation: "Equality of chemical potentials across phases is the condition for phase equilibrium; any difference would drive net transfer of that component from the phase of higher potential to that of lower potential.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "Dissolving 1 mol of glucose in 1 kg of water (K_f = 1.86 K kg mol⁻¹) lowers the freezing point by about:",
    topic: "Colligative Properties",
    explanation: "ΔT_f = K_f·m = 1.86 × 1 = 1.86 K, since glucose is a non-electrolyte (i = 1). The solution freezes near −1.86 °C.",
    choices: [
      { text: "1.86 K", isCorrect: true },
      { text: "0.93 K" },
      { text: "3.72 K" },
      { text: "0 K" },
    ],
  },
  {
    stem: "Dissolving 1 mol of NaCl in 1 kg of water lowers the freezing point roughly twice as much as 1 mol of glucose because NaCl has a van 't Hoff factor of about:",
    topic: "Colligative Properties",
    explanation: "NaCl dissociates into Na⁺ and Cl⁻, giving i ≈ 2, so it produces about twice the particles per mole and roughly doubles the freezing-point depression relative to glucose (i = 1).",
    choices: [
      { text: "2", isCorrect: true },
      { text: "1" },
      { text: "0.5" },
      { text: "4" },
    ],
  },
  {
    stem: "A 0.10 mol L⁻¹ solution at 300 K has an osmotic pressure (Π = cRT) of about:",
    topic: "Colligative Properties",
    explanation: "Π = cRT = 0.10 × 0.0821 × 300 ≈ 2.5 atm (using L·atm units). Even a dilute solution generates a substantial osmotic pressure.",
    choices: [
      { text: "About 2.5 atm", isCorrect: true },
      { text: "About 0.025 atm" },
      { text: "About 25 atm" },
      { text: "Exactly 1 atm" },
    ],
  },
  {
    stem: "A liquid has a vapour pressure of 0.50 atm at 350 K. Adding a non-volatile solute to mole fraction 0.10 lowers the solvent's vapour pressure to about:",
    topic: "Solutions & Raoult's Law",
    explanation: "By Raoult's law the solvent's partial pressure becomes x_solvent·p* = 0.90 × 0.50 = 0.45 atm. The vapour-pressure lowering is x_solute·p* = 0.05 atm.",
    choices: [
      { text: "0.45 atm", isCorrect: true },
      { text: "0.50 atm" },
      { text: "0.05 atm" },
      { text: "0.90 atm" },
    ],
  },
  {
    stem: "For a mixture of two volatile liquids A and B obeying Raoult's law, the total vapour pressure is:",
    topic: "Solutions & Raoult's Law",
    explanation: "p_total = x_A p_A* + x_B p_B*, the sum of the two partial pressures. The vapour is richer in the more volatile component (higher pure vapour pressure).",
    choices: [
      { text: "x_A p_A* + x_B p_B*", isCorrect: true },
      { text: "p_A* + p_B* only" },
      { text: "x_A x_B (p_A* + p_B*)" },
      { text: "p_A*·p_B*" },
    ],
  },
  {
    stem: "The vapour above an ideal mixture of two volatile liquids is always richer in the component with the:",
    topic: "Solutions & Raoult's Law",
    explanation: "The more volatile component (higher pure vapour pressure, lower boiling point) is enriched in the vapour phase — the principle exploited by fractional distillation.",
    choices: [
      { text: "Higher pure vapour pressure", isCorrect: true },
      { text: "Higher molar mass" },
      { text: "Lower vapour pressure" },
      { text: "Higher boiling point" },
    ],
  },
  {
    stem: "Using the integrated Clausius–Clapeyron equation, doubling knowledge of vapour pressure at two temperatures lets one calculate the:",
    topic: "Clausius–Clapeyron",
    explanation: "From ln(p₂/p₁) = −(ΔH_vap/R)(1/T₂ − 1/T₁), two (p, T) points give ΔH_vap. This is a standard way to obtain a liquid's enthalpy of vaporisation.",
    choices: [
      { text: "Enthalpy of vaporisation", isCorrect: true },
      { text: "Molar mass of the liquid" },
      { text: "Critical temperature" },
      { text: "Osmotic pressure" },
    ],
  },
  {
    stem: "A solute that depresses a solvent's freezing point by 0.52 K, where K_f = 1.86 K kg mol⁻¹, is present at a molality of about:",
    topic: "Colligative Properties",
    explanation: "m = ΔT_f/K_f = 0.52/1.86 ≈ 0.28 mol kg⁻¹ (for a non-electrolyte). Rearranging the colligative formula gives the concentration from the measured depression.",
    choices: [
      { text: "0.28 mol kg⁻¹", isCorrect: true },
      { text: "0.97 mol kg⁻¹" },
      { text: "1.86 mol kg⁻¹" },
      { text: "0.52 mol kg⁻¹" },
    ],
  },
  {
    stem: "The reverse-osmosis purification of water works by applying a pressure that is:",
    topic: "Colligative Properties",
    explanation: "Applying a pressure greater than the solution's osmotic pressure forces solvent backward through a semipermeable membrane, leaving solutes behind — the basis of desalination.",
    choices: [
      { text: "Greater than the osmotic pressure", isCorrect: true },
      { text: "Less than the osmotic pressure" },
      { text: "Exactly equal to atmospheric pressure" },
      { text: "Reduced all the way to zero" },
    ],
  },
  {
    stem: "A non-ideal solution's real behaviour is captured in thermodynamic equations by replacing pressure or concentration with:",
    topic: "Activities & Real Solutions",
    explanation: "Activities (effective concentrations, aᵢ = γᵢxᵢ) and fugacities (effective pressures) replace ideal concentrations and pressures so that the ideal-solution equations still apply to real systems.",
    choices: [
      { text: "Activities and fugacities", isCorrect: true },
      { text: "Molar masses" },
      { text: "The component boiling points" },
      { text: "Colours" },
    ],
  },
  {
    stem: "The activity coefficient γ of a component approaches 1 in the limit of:",
    topic: "Activities & Real Solutions",
    explanation: "As a solution becomes very dilute (solvent) or approaches ideal behaviour, γ → 1 and activity equals mole fraction. Deviations of γ from 1 measure non-ideality.",
    choices: [
      { text: "An ideal or infinitely dilute solution", isCorrect: true },
      { text: "A highly concentrated solution" },
      { text: "The critical point" },
      { text: "Absolute zero" },
    ],
  },
  {
    stem: "For a gas dissolving in a liquid, raising the temperature usually causes the solubility to:",
    topic: "Solutions & Raoult's Law",
    explanation: "Gas solubility typically decreases with rising temperature (dissolving a gas is usually exothermic, so heat drives gas out — consistent with Le Chatelier). This is why warm soda goes flat faster.",
    choices: [
      { text: "Decrease", isCorrect: true },
      { text: "Increase sharply" },
      { text: "Stay exactly constant" },
      { text: "Become infinite" },
    ],
  },
  {
    stem: "A semipermeable membrane in osmosis allows the passage of:",
    topic: "Colligative Properties",
    explanation: "A semipermeable membrane permits solvent molecules through but blocks solute particles, setting up the concentration-driven flow that produces osmotic pressure.",
    choices: [
      { text: "Solvent but not solute particles", isCorrect: true },
      { text: "Solute particles but not solvent" },
      { text: "Both solvent and solute freely" },
      { text: "Neither solvent nor solute" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which calculations using colligative formulae are correct? Select all that apply.",
    topic: "Colligative Properties",
    explanation: "ΔT_f = K_f·m; ΔT_b = K_b·m; Π = cRT; electrolytes multiply the effect by i. Osmotic pressure is not RT/c — it is cRT.",
    choices: [
      { text: "ΔT_f = K_f·m for a non-electrolyte", isCorrect: true },
      { text: "ΔT_b = K_b·m", isCorrect: true },
      { text: "Π = cRT for a dilute solution", isCorrect: true },
      { text: "An electrolyte multiplies the effect by its van 't Hoff factor i", isCorrect: true },
      { text: "Osmotic pressure is Π = RT/c" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about vapour pressure over solutions are correct? Select all that apply.",
    topic: "Solutions & Raoult's Law",
    explanation: "Total pressure over an ideal binary mixture is x_A p_A* + x_B p_B*; the vapour is richer in the more volatile component; a non-volatile solute lowers solvent vapour pressure; fractional distillation exploits volatility differences. A non-volatile solute does not raise the solvent's vapour pressure.",
    choices: [
      { text: "Total pressure is x_A p_A* + x_B p_B* for an ideal mixture", isCorrect: true },
      { text: "The vapour is richer in the more volatile component", isCorrect: true },
      { text: "A non-volatile solute lowers the solvent's vapour pressure", isCorrect: true },
      { text: "Fractional distillation exploits differences in volatility", isCorrect: true },
      { text: "A non-volatile solute raises the solvent's vapour pressure" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "Adding a non-volatile solute to a solvent raises its boiling point and lowers its freezing point, both in proportion to the molality of solute particles.",
    topic: "Colligative Properties",
    explanation: "Boiling-point elevation (ΔT_b = iK_b m) and freezing-point depression (ΔT_f = iK_f m) are colligative: they scale with the molal concentration of solute particles, widening the liquid range.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "The normal boiling point of a liquid is the temperature at which its vapour pressure equals:",
    topic: "Clausius–Clapeyron",
    explanation: "The normal boiling point is defined at 1 atm (101.325 kPa): the temperature where the saturated vapour pressure equals one standard atmosphere.",
    choices: [
      { text: "1 atm", isCorrect: true },
      { text: "The triple-point pressure" },
      { text: "The critical pressure" },
      { text: "Zero" },
    ],
  },
  {
    stem: "The melting of most substances is favoured by higher pressure because their solid is:",
    topic: "Phase Diagrams",
    explanation: "For most substances the solid is denser than the liquid (ΔV_fus > 0), so the solid–liquid line has a positive slope and higher pressure raises the melting point. Water is the notable exception.",
    choices: [
      { text: "Denser than the liquid", isCorrect: true },
      { text: "Less dense than the liquid" },
      { text: "The same density as the liquid" },
      { text: "A supercritical fluid" },
    ],
  },
  {
    stem: "A eutectic point on a two-component solid–liquid phase diagram is the composition and temperature at which:",
    topic: "Phase Diagrams",
    explanation: "The eutectic is the lowest melting point of a binary mixture, where liquid solidifies into two solid phases simultaneously at a fixed temperature — used in solders and freezing mixtures.",
    choices: [
      { text: "The mixture melts at its lowest point", isCorrect: true },
      { text: "A single pure solid first forms" },
      { text: "The liquid becomes supercritical" },
      { text: "The two liquids become immiscible" },
    ],
  },
  {
    stem: "Two liquids that do not mix in all proportions are described as:",
    topic: "Solutions & Raoult's Law",
    explanation: "Partially miscible (or immiscible) liquids separate into layers; each phase is a saturated solution of one liquid in the other. Oil and water are a familiar example.",
    choices: [
      { text: "Partially miscible", isCorrect: true },
      { text: "Perfectly ideal in all ratios" },
      { text: "Azeotropic" },
      { text: "Supercritical" },
    ],
  },
  {
    stem: "Steam distillation allows a high-boiling, water-immiscible compound to distil below 100 °C because the total vapour pressure is the:",
    topic: "Solutions & Raoult's Law",
    explanation: "For immiscible liquids, each exerts its own vapour pressure independently, so the total is the sum of the two pure vapour pressures. Boiling occurs when that sum reaches atmospheric pressure — below either pure boiling point.",
    choices: [
      { text: "Sum of the two separate vapour pressures", isCorrect: true },
      { text: "Product of the vapour pressures" },
      { text: "Average of the two vapour pressures" },
      { text: "Vapour pressure of water alone" },
    ],
  },
  {
    stem: "The distribution (partition) coefficient describes how a solute distributes itself between:",
    topic: "Solutions & Raoult's Law",
    explanation: "The partition coefficient is the ratio of a solute's equilibrium concentrations in two immiscible solvents. It underlies solvent extraction and drug distribution between phases.",
    choices: [
      { text: "Two immiscible solvents", isCorrect: true },
      { text: "A solid and its vapour" },
      { text: "Two temperatures" },
      { text: "A gas and a plasma" },
    ],
  },
  {
    stem: "Solvent extraction is more efficient when carried out as several small portions of solvent rather than one large portion because this:",
    topic: "Solutions & Raoult's Law",
    explanation: "Repeated extractions with fresh solvent shift the partition equilibrium each time, removing more solute overall than a single extraction with the same total volume.",
    choices: [
      { text: "Removes more solute overall", isCorrect: true },
      { text: "Uses less solvent in total" },
      { text: "Changes the partition coefficient" },
      { text: "Heats the mixture" },
    ],
  },
  {
    stem: "The vapour pressure of a solution containing a non-volatile solute is always ______ that of the pure solvent.",
    topic: "Solutions & Raoult's Law",
    explanation: "Because the solute lowers the solvent's mole fraction (Raoult's law), the solution's vapour pressure is always lower than the pure solvent's at the same temperature.",
    choices: [
      { text: "Lower than", isCorrect: true },
      { text: "Higher than" },
      { text: "Equal to" },
      { text: "Double" },
    ],
  },
  {
    stem: "On a temperature–composition (boiling) diagram, the region between the liquid and vapour curves represents:",
    topic: "Solutions & Raoult's Law",
    explanation: "Between the lower (liquidus) and upper (vapourus) curves, liquid and vapour of differing compositions coexist. A tie line connects the compositions in equilibrium at a given temperature.",
    choices: [
      { text: "Coexisting liquid and vapour", isCorrect: true },
      { text: "Pure solid only" },
      { text: "A supercritical fluid" },
      { text: "A vacuum" },
    ],
  },
  {
    stem: "The lever rule applied to a two-phase region of a phase diagram gives the:",
    topic: "Phase Diagrams",
    explanation: "The lever rule uses the tie-line segment lengths to find the relative amounts of the two coexisting phases at a given overall composition and temperature.",
    choices: [
      { text: "Relative amounts of the two phases present", isCorrect: true },
      { text: "Absolute temperature of the system" },
      { text: "Vapour pressure of the solvent" },
      { text: "Critical pressure" },
    ],
  },
  {
    stem: "Henry's law constant for a gas increases with temperature, which corresponds to the gas becoming:",
    topic: "Solutions & Raoult's Law",
    explanation: "A larger Henry's law constant means a given partial pressure dissolves less gas, so gas solubility falls as temperature rises — consistent with the usual exothermic dissolution of gases.",
    choices: [
      { text: "Less soluble as temperature rises", isCorrect: true },
      { text: "More soluble as temperature rises" },
      { text: "Insoluble at all temperatures" },
      { text: "Independent of temperature" },
    ],
  },
  {
    stem: "The freezing-point depression method (cryoscopy) can be used to determine a solute's:",
    topic: "Colligative Properties",
    explanation: "Measuring ΔT_f for a known mass of solute in a known mass of solvent gives the molality, and hence the molar mass of an unknown non-electrolyte solute.",
    choices: [
      { text: "Molar mass", isCorrect: true },
      { text: "Colour" },
      { text: "Boiling point of the pure solute" },
      { text: "Critical temperature" },
    ],
  },
  {
    stem: "For water, the solid–liquid coexistence line slopes slightly to the left, meaning that applying pressure to ice at 0 °C tends to:",
    topic: "Phase Diagrams",
    explanation: "Because higher pressure lowers ice's melting point (negative slope), squeezing ice can melt it. This unusual behaviour reflects ice being less dense than liquid water.",
    choices: [
      { text: "Melt it", isCorrect: true },
      { text: "Freeze it harder" },
      { text: "Sublime it directly" },
      { text: "Have no effect at all" },
    ],
  },
  {
    stem: "Colligative properties of dilute solutions ultimately arise because dissolving a solute lowers the solvent's:",
    topic: "Colligative Properties",
    explanation: "Adding solute lowers the solvent's chemical potential in the liquid, shifting all the equilibria (vapour, freezing, boiling, osmosis) — the common thermodynamic origin of every colligative property.",
    choices: [
      { text: "Liquid-phase chemical potential", isCorrect: true },
      { text: "Molar mass" },
      { text: "The colour intensity" },
      { text: "Nuclear charge" },
    ],
  },
  {
    stem: "An ideal-dilute solution obeys Raoult's law for the solvent and ______ for the solute.",
    topic: "Solutions & Raoult's Law",
    explanation: "In the ideal-dilute range, the solvent (in excess) follows Raoult's law while the dilute solute follows Henry's law. The two laws describe the two ends of the composition range.",
    choices: [
      { text: "Henry's law", isCorrect: true },
      { text: "The ideal gas law" },
      { text: "Hess's law" },
      { text: "Graham's law" },
    ],
  },
  {
    stem: "The boiling point of seawater is slightly higher than that of pure water because dissolved salts cause:",
    topic: "Colligative Properties",
    explanation: "Dissolved salts raise the boiling point through boiling-point elevation (a colligative effect), since the ions lower the solvent's escaping tendency; the effect scales with total ion concentration.",
    choices: [
      { text: "Boiling-point elevation", isCorrect: true },
      { text: "Freezing-point elevation" },
      { text: "A drop in osmotic pressure" },
      { text: "A chemical reaction with water" },
    ],
  },
  {
    stem: "A supercritical fluid is often useful as a solvent because it combines gas-like ______ with liquid-like density.",
    topic: "Phase Diagrams",
    explanation: "Supercritical fluids (e.g. supercritical CO₂) diffuse and penetrate like gases yet dissolve solutes like liquids, making them tunable, low-residue extraction solvents (as in decaffeination).",
    choices: [
      { text: "Diffusivity", isCorrect: true },
      { text: "Colour" },
      { text: "Rigidity" },
      { text: "Ionic charge" },
    ],
  },
  {
    stem: "The maximum amount of solute that dissolves in a given solvent at a set temperature is the solute's:",
    topic: "Solutions & Raoult's Law",
    explanation: "Solubility is the equilibrium concentration of a saturated solution at a specified temperature; beyond it, excess solute remains undissolved in equilibrium with the solution.",
    choices: [
      { text: "Solubility", isCorrect: true },
      { text: "Molality of mixing" },
      { text: "Partition coefficient" },
      { text: "Activity coefficient" },
    ],
  },
  {
    stem: "Osmotic pressure differences across cell membranes cause red blood cells placed in pure water to:",
    topic: "Colligative Properties",
    explanation: "In hypotonic pure water, solvent flows into the cell by osmosis (toward higher internal solute concentration), swelling and potentially bursting it (haemolysis). This shows osmosis in a biological setting.",
    choices: [
      { text: "Swell as water flows in", isCorrect: true },
      { text: "Shrink as water flows out" },
      { text: "Remain completely unchanged" },
      { text: "Release all their solutes" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about phase behaviour of mixtures are correct? Select all that apply.",
    topic: "Solutions & Raoult's Law",
    explanation: "Immiscible liquids each exert their own vapour pressure (steam distillation); azeotropes can't be separated by simple distillation; the lever rule gives phase amounts; the eutectic is the lowest-melting composition. Adding a non-volatile solute lowers (not raises) vapour pressure.",
    choices: [
      { text: "Immiscible liquids each exert their own vapour pressure", isCorrect: true },
      { text: "An azeotrope cannot be separated by simple distillation", isCorrect: true },
      { text: "The lever rule gives the relative amounts of two phases", isCorrect: true },
      { text: "A eutectic is the lowest-melting composition of a binary mixture", isCorrect: true },
      { text: "A non-volatile solute raises the solvent's vapour pressure" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "For two immiscible liquids, the total vapour pressure is the sum of the vapour pressures of the two pure liquids, so the mixture boils below the boiling point of either component.",
    topic: "Solutions & Raoult's Law",
    explanation: "Because each immiscible liquid contributes its full pure vapour pressure, the total reaches atmospheric pressure at a lower temperature than either pure liquid alone — the principle of steam distillation.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "Raising the temperature always increases the solubility of a gas in a liquid.",
    topic: "Solutions & Raoult's Law",
    explanation: "This is false: gas solubility usually decreases as temperature rises, because dissolving a gas is typically exothermic, so heating drives dissolved gas out of solution.",
    choices: [
      { text: "True" },
      { text: "False", isCorrect: true },
    ],
  },
];
