import type { Q } from "../_lib/qbank";

export const PHYSICAL_SET_5: Q[] = [
  {
    stem: "For the gas-phase reaction N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g), how is the equilibrium constant Kc written?",
    topic: "Chemical Equilibrium",
    explanation: "The equilibrium constant is the product concentrations over reactant concentrations, each raised to its stoichiometric coefficient. Pure solids and liquids are omitted; here all species are gases.",
    choices: [
      { text: "[NH₃]² / ([N₂][H₂]³)", isCorrect: true },
      { text: "[N₂][H₂]³ / [NH₃]²" },
      { text: "[NH₃] / ([N₂][H₂])" },
      { text: "2[NH₃] / (3[H₂] + [N₂])" },
    ],
  },
  {
    stem: "The relationship between Kp and Kc for a gas-phase reaction is Kp = Kc(RT)Dn, where Dn is the change in moles of gas. For N₂ + 3 H₂ ⇌ 2 NH₃, what is Dn?",
    topic: "Chemical Equilibrium",
    explanation: "Dn = (moles of gaseous products) - (moles of gaseous reactants) = 2 - (1 + 3) = -2. This exponent links the pressure and concentration constants through the factor (RT) raised to Dn.",
    choices: [
      { text: "-2", isCorrect: true },
      { text: "+2" },
      { text: "-1" },
      { text: "+4" },
    ],
  },
  {
    stem: "For a reaction at equilibrium, the reaction quotient Q equals which quantity?",
    topic: "Chemical Equilibrium",
    explanation: "Q has the same algebraic form as the equilibrium constant but uses the current (arbitrary) concentrations. At equilibrium the system satisfies Q = K, which is the defining condition of equilibrium.",
    choices: [
      { text: "the equilibrium constant K", isCorrect: true },
      { text: "the rate constant k" },
      { text: "always the value 1" },
      { text: "the sum of all concentrations" },
    ],
  },
  {
    stem: "If Q < K for a reaction mixture, in which direction does the reaction proceed to reach equilibrium?",
    topic: "Chemical Equilibrium",
    explanation: "When Q is smaller than K there are too many reactants relative to products, so the net reaction runs forward (toward products) until Q rises to equal K. If Q > K it would run in reverse.",
    choices: [
      { text: "forward, toward products", isCorrect: true },
      { text: "reverse, toward reactants" },
      { text: "it is already at equilibrium" },
      { text: "no net direction is defined" },
    ],
  },
  {
    stem: "A large equilibrium constant (K >> 1) indicates what about a reaction at equilibrium?",
    topic: "Chemical Equilibrium",
    explanation: "A very large K means the numerator (products) dominates the denominator (reactants) at equilibrium, so products are strongly favored. It says nothing about how fast equilibrium is reached, which is a kinetic matter.",
    choices: [
      { text: "products are strongly favored", isCorrect: true },
      { text: "reactants are strongly favored" },
      { text: "the reaction is very fast" },
      { text: "the reaction is endothermic" },
    ],
  },
  {
    stem: "For the reaction H₂(g) + I₂(g) ⇌ 2 HI(g), Kp and Kc are numerically equal. Why?",
    topic: "Chemical Equilibrium",
    explanation: "Because Dn = 2 - 2 = 0, the factor (RT)^{Dn} = (RT)^0 = 1, so Kp = Kc(1) = Kc. Whenever the moles of gas are unchanged, the two constants coincide.",
    choices: [
      { text: "the change in moles of gas is zero", isCorrect: true },
      { text: "the reaction is exothermic overall" },
      { text: "all species are diatomic gases" },
      { text: "the temperature equals 273 K" },
    ],
  },
  {
    stem: "Which change to a reaction's stoichiometry converts its equilibrium constant K into 1/K?",
    topic: "Chemical Equilibrium",
    explanation: "Reversing a reaction inverts its equilibrium constant, giving 1/K. Multiplying all coefficients by n raises K to the n-th power; adding reactions multiplies their constants.",
    choices: [
      { text: "reversing the direction of the reaction", isCorrect: true },
      { text: "doubling every stoichiometric coefficient" },
      { text: "halving every stoichiometric coefficient" },
      { text: "adding an inert gas at constant volume" },
    ],
  },
  {
    stem: "Pure solids and pure liquids are excluded from the equilibrium-constant expression because",
    topic: "Chemical Equilibrium",
    explanation: "The activity of a pure condensed phase is defined as 1, so its 'concentration' does not vary and drops out of K. Only gases and dissolved species, whose activities change, appear in the expression.",
    choices: [
      { text: "their activities are taken to be unity", isCorrect: true },
      { text: "they have no measurable mass" },
      { text: "they react infinitely quickly" },
      { text: "their concentrations are always zero" },
    ],
  },
  {
    stem: "For N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g), how does increasing the total pressure by reducing the volume shift the equilibrium?",
    topic: "Le Chatelier's Principle",
    explanation: "Compressing the system shifts equilibrium toward the side with fewer moles of gas to relieve the pressure. Here the product side has 2 mol versus 4 mol of reactants, so the shift is toward NH₃.",
    choices: [
      { text: "toward the products (fewer gas moles)", isCorrect: true },
      { text: "toward the reactants (more gas moles)" },
      { text: "no shift, since K is unchanged" },
      { text: "toward whichever side is exothermic" },
    ],
  },
  {
    stem: "Adding an inert gas to an equilibrium mixture at constant volume has what effect on the position of equilibrium?",
    topic: "Le Chatelier's Principle",
    explanation: "At constant volume the partial pressures and concentrations of the reacting species are unchanged, so Q is unchanged and there is no shift. Only a volume change (or adding a reactant/product) shifts a gas equilibrium.",
    choices: [
      { text: "no effect on the equilibrium position", isCorrect: true },
      { text: "shifts toward the products always" },
      { text: "shifts toward the reactants always" },
      { text: "shifts toward fewer moles of gas" },
    ],
  },
  {
    stem: "For an exothermic reaction at equilibrium, raising the temperature does what to K and to the yield of product?",
    topic: "Le Chatelier's Principle",
    explanation: "Heat is a product of an exothermic reaction, so added heat drives the equilibrium backward: K decreases and the product yield falls. For an endothermic reaction the opposite holds.",
    choices: [
      { text: "both K and product yield decrease", isCorrect: true },
      { text: "both K and product yield increase" },
      { text: "K is unchanged; only the rate rises" },
      { text: "K increases but yield decreases" },
    ],
  },
  {
    stem: "Which action shifts the equilibrium 2 SO₂(g) + O₂(g) ⇌ 2 SO₃(g) toward more SO₃?",
    topic: "Le Chatelier's Principle",
    explanation: "Removing a product (SO₃) or adding a reactant, or compressing toward fewer gas moles (3 mol → 2 mol), all favor product. Increasing volume favors the reactant side, so it is the wrong choice.",
    choices: [
      { text: "increasing the total pressure", isCorrect: true },
      { text: "increasing the container volume" },
      { text: "adding a noble gas at fixed volume" },
      { text: "removing some SO₂ reactant" },
    ],
  },
  {
    stem: "A catalyst added to a system at equilibrium changes which of the following?",
    topic: "Le Chatelier's Principle",
    explanation: "A catalyst speeds the forward and reverse reactions equally, so it shortens the time to reach equilibrium but leaves K and the equilibrium concentrations unchanged. It alters kinetics, not thermodynamics.",
    choices: [
      { text: "the time taken to reach equilibrium", isCorrect: true },
      { text: "the value of the equilibrium constant" },
      { text: "the equilibrium yield of product" },
      { text: "the standard reaction enthalpy" },
    ],
  },
  {
    stem: "For the endothermic dissociation N₂O₄(g) ⇌ 2 NO₂(g), which pair of changes both increase the amount of NO₂ at equilibrium?",
    topic: "Le Chatelier's Principle",
    explanation: "Because it is endothermic and produces more gas moles, heating and expanding the volume (lowering pressure) both shift toward NO₂. Cooling or compressing would favor N₂O₄.",
    choices: [
      { text: "heating and increasing the volume", isCorrect: true },
      { text: "cooling and decreasing the volume" },
      { text: "cooling and adding a catalyst" },
      { text: "heating and increasing the pressure" },
    ],
  },
  {
    stem: "The standard free-energy change and equilibrium constant are linked by which equation?",
    topic: "Equilibrium & Free Energy",
    explanation: "The central bridge between thermodynamics and equilibrium is ΔG° = -RT ln K. A negative ΔG° gives K > 1 (products favored); a positive ΔG° gives K < 1.",
    choices: [
      { text: "ΔG° = -RT ln K", isCorrect: true },
      { text: "ΔG° = +RT ln K" },
      { text: "ΔG° = -RT / ln K" },
      { text: "ΔG° = -K ln(RT)" },
    ],
  },
  {
    stem: "If ΔG° for a reaction is negative, what does that imply about K?",
    topic: "Equilibrium & Free Energy",
    explanation: "From ΔG° = -RT ln K, a negative ΔG° makes ln K positive, so K > 1 and products are favored at equilibrium. A positive ΔG° instead gives K < 1.",
    choices: [
      { text: "K is greater than 1", isCorrect: true },
      { text: "K is less than 1" },
      { text: "K equals exactly 1" },
      { text: "K is negative" },
    ],
  },
  {
    stem: "The van 't Hoff equation ln(K₂/K₁) = -(ΔH°/R)(1/T₂ - 1/T₁) describes what dependence?",
    topic: "Equilibrium & Free Energy",
    explanation: "The van 't Hoff equation gives the temperature dependence of the equilibrium constant in terms of the standard reaction enthalpy. A plot of ln K versus 1/T is linear with slope -ΔH°/R.",
    choices: [
      { text: "how K varies with temperature", isCorrect: true },
      { text: "how K varies with pressure" },
      { text: "how the rate constant varies with T" },
      { text: "how K varies with catalyst amount" },
    ],
  },
  {
    stem: "For an endothermic reaction (ΔH° > 0), a van 't Hoff plot of ln K versus 1/T has what slope?",
    topic: "Equilibrium & Free Energy",
    explanation: "The slope of ln K versus 1/T is -ΔH°/R. For an endothermic reaction ΔH° > 0, so the slope -ΔH°/R is negative, and K rises with temperature.",
    choices: [
      { text: "a negative slope", isCorrect: true },
      { text: "a positive slope" },
      { text: "a slope of exactly zero" },
      { text: "a slope equal to R" },
    ],
  },
  {
    stem: "When a reaction is at equilibrium, the value of ΔG (not ΔG°) for the reaction mixture is",
    topic: "Equilibrium & Free Energy",
    explanation: "At equilibrium the free energy is at a minimum, so the reaction free energy ΔG = 0. The standard value ΔG° is generally nonzero and fixes K through ΔG° = -RT ln K.",
    choices: [
      { text: "equal to zero", isCorrect: true },
      { text: "equal to ΔG°" },
      { text: "always negative" },
      { text: "equal to -RT" },
    ],
  },
  {
    stem: "For a weak acid HA ⇌ H ⁺ + A ⁻, the acid dissociation constant Ka is written as",
    topic: "Acid-Base Equilibria",
    explanation: "The acid constant is the product of the ion concentrations over the undissociated acid: Ka = [H⁺][A⁻]/[HA]. A larger Ka means a stronger acid.",
    choices: [
      { text: "[H⁺][A⁻] / [HA]", isCorrect: true },
      { text: "[HA] / ([H⁺][A⁻])" },
      { text: "[H⁺] / [A⁻]" },
      { text: "[HA][H⁺] / [A⁻]" },
    ],
  },
  {
    stem: "At 25 °C the ion-product of water is Kw = [H ⁺][OH ⁻] = 1.0 · 10⁻¹⁴. What is the pH of pure water?",
    topic: "Acid-Base Equilibria",
    explanation: "In pure water [H⁺] = [OH⁻] = 1.0 · 10⁻⁷ M, so pH = -log(10⁻⁷) = 7.00. Neutral pH is 7 only at 25 °C, because Kw varies with temperature.",
    choices: [
      { text: "7.00", isCorrect: true },
      { text: "14.00" },
      { text: "1.00" },
      { text: "0.00" },
    ],
  },
  {
    stem: "The Henderson-Hasselbalch equation pH = pKa + log([A ⁻]/[HA]) applies to which kind of solution?",
    topic: "Acid-Base Equilibria",
    explanation: "It relates pH to the ratio of conjugate base to weak acid in a buffer. A buffer resists pH change and is most effective when [A⁻] → [HA], i.e. pH → pKa.",
    choices: [
      { text: "a buffer of a weak acid and its conjugate base", isCorrect: true },
      { text: "a solution of a strong acid only" },
      { text: "a solution of a strong base only" },
      { text: "a saturated solution of a salt" },
    ],
  },
  {
    stem: "A buffer resists changes in pH most effectively when the pH of the solution is",
    topic: "Acid-Base Equilibria",
    explanation: "Buffer capacity is greatest when [weak acid] → [conjugate base], which by Henderson-Hasselbalch means pH → pKa. Far from pKa the buffer is easily overwhelmed.",
    choices: [
      { text: "close to the pKa of the weak acid", isCorrect: true },
      { text: "as far below the pKa as possible" },
      { text: "exactly 7 regardless of the acid" },
      { text: "close to 0 or close to 14" },
    ],
  },
  {
    stem: "For the sparingly soluble salt AgCl(s) ⇌ Ag ⁺(aq) + Cl ⁻(aq), the solubility product is",
    topic: "Solubility Equilibria",
    explanation: "Because the pure solid has unit activity, Ksp = [Ag⁺][Cl⁻]. For a salt AxBy the expression raises each ion concentration to its stoichiometric coefficient.",
    choices: [
      { text: "[Ag⁺][Cl⁻]", isCorrect: true },
      { text: "[AgCl] / ([Ag⁺][Cl⁻])" },
      { text: "[Ag⁺] + [Cl⁻]" },
      { text: "[Ag⁺][Cl⁻] / [AgCl]" },
    ],
  },
  {
    stem: "Adding NaCl to a saturated solution of AgCl decreases the solubility of AgCl. This illustrates",
    topic: "Solubility Equilibria",
    explanation: "The added Cl⁻ is a common ion; by Le Chatelier the dissolution equilibrium shifts back toward solid AgCl, lowering its solubility. Ksp itself is unchanged at fixed temperature.",
    choices: [
      { text: "the common-ion effect", isCorrect: true },
      { text: "the levelling effect" },
      { text: "Henry's law" },
      { text: "Hess's law" },
    ],
  },
  {
    stem: "For a salt MX₂ of molar solubility s, the solubility product is Ksp = 4s³. Which relation gives s in terms of Ksp?",
    topic: "Solubility Equilibria",
    explanation: "Dissolving s mol/L of MX₂ gives [M²⁺] = s and [X⁻] = 2s, so Ksp = s(2s)² = 4s³. Solving, s = (Ksp/4)¹/³.",
    choices: [
      { text: "s = (Ksp/4)¹/³", isCorrect: true },
      { text: "s = (Ksp/2)¹/²" },
      { text: "s = (Ksp)¹/²" },
      { text: "s = 4Ksp³" },
    ],
  },
  {
    stem: "In an electrochemical cell, oxidation always occurs at which electrode?",
    topic: "Electrochemistry",
    explanation: "By definition oxidation (loss of electrons) occurs at the anode and reduction at the cathode, in both galvanic and electrolytic cells. A mnemonic is 'an ox, red cat'.",
    choices: [
      { text: "the anode", isCorrect: true },
      { text: "the cathode" },
      { text: "the salt bridge" },
      { text: "the reference electrode" },
    ],
  },
  {
    stem: "A galvanic (voltaic) cell is one in which",
    topic: "Electrochemistry",
    explanation: "A galvanic cell uses a spontaneous redox reaction to produce electrical work, so its cell potential is positive. An electrolytic cell instead consumes electrical energy to drive a non-spontaneous reaction.",
    choices: [
      { text: "a spontaneous reaction produces electricity", isCorrect: true },
      { text: "electricity drives a non-spontaneous reaction" },
      { text: "no net chemical change takes place" },
      { text: "only reduction occurs at both electrodes" },
    ],
  },
  {
    stem: "The standard hydrogen electrode (SHE) is assigned what standard potential?",
    topic: "Electrochemistry",
    explanation: "The SHE is the reference against which all electrode potentials are measured, and it is assigned E° = 0 V by convention (at 1 bar H₂, 1 M H⁺, 25 °C).",
    choices: [
      { text: "exactly 0 V", isCorrect: true },
      { text: "+1.00 V" },
      { text: "-1.00 V" },
      { text: "+0.76 V" },
    ],
  },
  {
    stem: "The standard cell potential is calculated from electrode potentials as Ecell° =",
    topic: "Electrochemistry",
    explanation: "Using reduction potentials, Ecell° = E°(cathode) - E°(anode). Both are tabulated as reductions; the anode term is subtracted because oxidation is the reverse of its reduction.",
    choices: [
      { text: "E°(cathode) - E°(anode)", isCorrect: true },
      { text: "E°(anode) - E°(cathode)" },
      { text: "E°(cathode) + E°(anode)" },
      { text: "E°(cathode) · E°(anode)" },
    ],
  },
  {
    stem: "A positive standard cell potential Ecell° corresponds to a standard reaction free energy that is",
    topic: "Electrochemistry",
    explanation: "The link ΔG° = -nFEcell° shows that a positive cell potential gives a negative ΔG°, i.e. a spontaneous cell reaction. n is the electrons transferred and F is the Faraday constant.",
    choices: [
      { text: "negative (spontaneous)", isCorrect: true },
      { text: "positive (non-spontaneous)" },
      { text: "exactly zero (at equilibrium)" },
      { text: "undefined without the temperature" },
    ],
  },
  {
    stem: "In the equation ΔG° = -nFEcell°, the symbol F represents",
    topic: "Electrochemistry",
    explanation: "F is the Faraday constant, the charge per mole of electrons, about 96 485 C/mol. n is the number of moles of electrons transferred in the balanced cell reaction.",
    choices: [
      { text: "the Faraday constant (charge per mole of e⁻)", isCorrect: true },
      { text: "the gas constant per mole" },
      { text: "the number of electrons transferred" },
      { text: "the force on the moving ions" },
    ],
  },
  {
    stem: "In cell notation such as Zn(s) | Zn ²⁺ || Cu ²⁺ | Cu(s), the double vertical line || denotes",
    topic: "Electrochemistry",
    explanation: "The double bar marks the salt bridge (or liquid junction) separating the two half-cells; a single bar marks a phase boundary. The anode is written on the left, the cathode on the right.",
    choices: [
      { text: "the salt bridge between half-cells", isCorrect: true },
      { text: "a phase boundary within a half-cell" },
      { text: "the external wire connection" },
      { text: "the direction of electron flow" },
    ],
  },
  {
    stem: "The purpose of the salt bridge in a galvanic cell is to",
    topic: "Electrochemistry",
    explanation: "The salt bridge carries ions to keep each half-cell electrically neutral as the reaction proceeds; without it charge would build up and current would quickly stop. It does not carry electrons.",
    choices: [
      { text: "maintain electrical neutrality in each half-cell", isCorrect: true },
      { text: "carry electrons between the electrodes" },
      { text: "catalyze the electrode reactions" },
      { text: "prevent any ion movement between cells" },
    ],
  },
  {
    stem: "During discharge of a galvanic cell, electrons flow through the external circuit from",
    topic: "Electrochemistry",
    explanation: "Electrons are released by oxidation at the anode and travel through the external wire to the cathode, where reduction consumes them. Conventional current flows in the opposite sense.",
    choices: [
      { text: "the anode to the cathode", isCorrect: true },
      { text: "the cathode to the anode" },
      { text: "the salt bridge to the anode" },
      { text: "the cathode to the salt bridge" },
    ],
  },
  {
    stem: "A concentration cell generates a potential because",
    topic: "Electrochemistry",
    explanation: "In a concentration cell both electrodes are the same, so Ecell° = 0; the emf arises purely from the difference in ion concentration, and current flows to equalize them (via the Nernst term).",
    choices: [
      { text: "the two half-cells differ only in concentration", isCorrect: true },
      { text: "the two electrodes are different metals" },
      { text: "the standard potentials differ greatly" },
      { text: "a catalyst lowers the activation energy" },
    ],
  },
  {
    stem: "For the reduction Cu ²⁺ + 2 e ⁻ → Cu, E° = +0.34 V, and for Zn ²⁺ + 2 e ⁻ → Zn, E° = -0.76 V. Which metal is the anode in a Cu-Zn cell?",
    topic: "Electrochemistry",
    explanation: "The electrode with the more negative reduction potential is oxidized, so zinc (-0.76 V) is the anode and copper (+0.34 V) is the cathode. The cell potential is 0.34 - (-0.76) = 1.10 V.",
    choices: [
      { text: "zinc, because its E° is more negative", isCorrect: true },
      { text: "copper, because its E° is more positive" },
      { text: "zinc, because its E° is more positive" },
      { text: "neither; both are reduced together" },
    ],
  },
  {
    stem: "A species with a large positive standard reduction potential is",
    topic: "Electrochemistry",
    explanation: "A high (positive) reduction potential means the species is readily reduced, so it is a strong oxidizing agent (e.g. F₂, E°/2.87 V). Species with very negative potentials are strong reducing agents.",
    choices: [
      { text: "a strong oxidizing agent", isCorrect: true },
      { text: "a strong reducing agent" },
      { text: "a poor electron acceptor" },
      { text: "always a pure metal" },
    ],
  },
  {
    stem: "The Nernst equation E = E° - (RT/nF) ln Q describes how the cell potential depends on",
    topic: "Electrochemistry",
    explanation: "The Nernst equation gives the emf away from standard conditions, correcting E° for the reaction quotient Q (the activities/concentrations). As the cell discharges, Q rises toward K and E falls to 0.",
    choices: [
      { text: "the reaction quotient (concentrations)", isCorrect: true },
      { text: "the electrode surface area" },
      { text: "the mass of the electrodes" },
      { text: "the resistance of the wire" },
    ],
  },
  {
    stem: "At 25 °C the Nernst equation is often written E = E° - (0.0592/n) log Q. The number 0.0592 V comes from",
    topic: "Electrochemistry",
    explanation: "It is 2.303RT/F evaluated at 298 K, converting the natural-log form to base-10 logs: 2.303 · 8.314 · 298 / 96485 → 0.0592 V. Dividing by n adjusts for the electrons transferred.",
    choices: [
      { text: "2.303RT/F evaluated at 298 K", isCorrect: true },
      { text: "the Faraday constant divided by R" },
      { text: "the standard potential of the SHE" },
      { text: "the ideal-gas constant in volts" },
    ],
  },
  {
    stem: "As a galvanic cell discharges and approaches equilibrium, its cell potential E",
    topic: "Electrochemistry",
    explanation: "As Q increases toward K, the Nernst term grows and E falls; at equilibrium Q = K and E = 0, so no further work can be drawn. A 'dead battery' is a cell that has reached E = 0.",
    choices: [
      { text: "decreases toward zero", isCorrect: true },
      { text: "increases without limit" },
      { text: "stays equal to E°" },
      { text: "becomes increasingly negative" },
    ],
  },
  {
    stem: "At equilibrium the Nernst equation gives E = 0, which yields the relation",
    topic: "Electrochemistry",
    explanation: "Setting E = 0 gives E° = (RT/nF) ln K, so ln K = nF E°/RT. This links the standard cell potential to the equilibrium constant of the cell reaction.",
    choices: [
      { text: "ln K = nF E°/RT", isCorrect: true },
      { text: "ln K = -nF E°/RT" },
      { text: "ln K = RT/(nF E°)" },
      { text: "ln K = E°/(nFRT)" },
    ],
  },
  {
    stem: "Faraday's first law of electrolysis states that the mass deposited at an electrode is proportional to",
    topic: "Electrochemistry",
    explanation: "The amount of substance transformed is proportional to the charge passed, Q = It (current · time). The mass follows m = (Q/F)(M/n) via the molar mass and electrons per ion.",
    choices: [
      { text: "the quantity of electric charge passed", isCorrect: true },
      { text: "the voltage applied to the cell" },
      { text: "the surface area of the electrode" },
      { text: "the concentration of the salt bridge" },
    ],
  },
  {
    stem: "How many moles of electrons are required to deposit 1 mol of Al from Al ³⁺ at a cathode?",
    topic: "Electrochemistry",
    explanation: "Reduction is Al³⁺ + 3 e⁻ → Al, so 3 mol of electrons (3 faradays) are needed per mole of aluminium. This stoichiometry underlies Faraday's second law.",
    choices: [
      { text: "3 mol", isCorrect: true },
      { text: "1 mol" },
      { text: "2 mol" },
      { text: "6 mol" },
    ],
  },
  {
    stem: "Passing 1 faraday of charge (96 485 C) through a cell will deposit how much silver from Ag ⁺ (molar mass 108 g/mol)?",
    topic: "Electrochemistry",
    explanation: "Ag⁺ + e⁻ → Ag needs 1 mol e⁻ per mol Ag, so 1 faraday deposits 1 mol = 108 g of silver. This one-electron reduction makes silver a classic coulometric standard.",
    choices: [
      { text: "108 g (1 mol)", isCorrect: true },
      { text: "54 g (0.5 mol)" },
      { text: "216 g (2 mol)" },
      { text: "12 g (1/9 mol)" },
    ],
  },
  {
    stem: "In the electrolysis of molten NaCl, which product forms at the cathode?",
    topic: "Electrochemistry",
    explanation: "The cathode is where reduction occurs, so Na⁺ is reduced to sodium metal; chlorine gas is oxidized from Cl⁻ at the anode. In aqueous NaCl the cathode product is instead H₂ from water.",
    choices: [
      { text: "sodium metal", isCorrect: true },
      { text: "chlorine gas" },
      { text: "oxygen gas" },
      { text: "hydrogen gas" },
    ],
  },
  {
    stem: "Molar conductivity λm of an electrolyte is defined as",
    topic: "Electrochemistry",
    explanation: "Molar conductivity is the conductivity σ divided by the molar concentration c: λm = σ/c. It normalizes conductivity for concentration so different electrolytes can be compared.",
    choices: [
      { text: "the conductivity divided by concentration", isCorrect: true },
      { text: "the conductivity multiplied by concentration" },
      { text: "the resistance per unit length" },
      { text: "the current divided by the voltage" },
    ],
  },
  {
    stem: "For a strong electrolyte, molar conductivity λm varies with concentration according to Kohlrausch's law as",
    topic: "Electrochemistry",
    explanation: "Kohlrausch found λm = λ° - K√c for strong electrolytes, a straight line in √c. Extrapolating to c = 0 gives the limiting molar conductivity λ°.",
    choices: [
      { text: "a linear decrease with √c", isCorrect: true },
      { text: "an exponential rise with c" },
      { text: "independence from concentration" },
      { text: "a linear increase with c²" },
    ],
  },
  {
    stem: "The limiting molar conductivity λm° of an electrolyte equals the sum of independent ionic contributions. This is",
    topic: "Electrochemistry",
    explanation: "Kohlrausch's law of independent migration states that at infinite dilution each ion contributes independently, so λm° = λ°(+) + λ°(-). It lets weak-electrolyte limits be built from ionic values.",
    choices: [
      { text: "Kohlrausch's law of independent ion migration", isCorrect: true },
      { text: "the Debye-Huckel limiting law" },
      { text: "the Nernst distribution law" },
      { text: "Faraday's second law of electrolysis" },
    ],
  },
  {
    stem: "At equilibrium a reaction has [products] far greater than [reactants], giving Kc = 4.5 · 10⁶. The reaction is best described as",
    topic: "Chemical Equilibrium",
    explanation: "A Kc of order 10⁶ means products overwhelmingly dominate at equilibrium, so the forward reaction is essentially complete. Such large constants describe 'product-favored' reactions.",
    choices: [
      { text: "strongly product-favored", isCorrect: true },
      { text: "strongly reactant-favored" },
      { text: "evenly balanced (K near 1)" },
      { text: "non-spontaneous at all T" },
    ],
  },
  {
    stem: "For A(g) ⇌ B(g) with Kc = 1, the equilibrium mixture contains",
    topic: "Chemical Equilibrium",
    explanation: "For this 1:1 reaction Kc = [B]/[A] = 1 means [A] = [B] at equilibrium, so the two are present in equal concentration. K near 1 marks a roughly balanced equilibrium.",
    choices: [
      { text: "equal concentrations of A and B", isCorrect: true },
      { text: "mostly B with little A" },
      { text: "mostly A with little B" },
      { text: "only B and no A at all" },
    ],
  },
  {
    stem: "A weak acid of concentration 0.10 M has Ka = 1.0 · 10⁻⁵. Using [H ⁺] → √(Kac), the pH is approximately",
    topic: "Acid-Base Equilibria",
    explanation: "With [H⁺] → √(1.0·10⁻⁵ · 0.10) = √(1.0·10⁻⁶) = 1.0·10⁻³ M, pH = -log(10⁻³) = 3.0. The approximation assumes little dissociation.",
    choices: [
      { text: "about 3.0", isCorrect: true },
      { text: "about 5.0" },
      { text: "about 1.0" },
      { text: "about 7.0" },
    ],
  },
  {
    stem: "Increasing the concentration of a weak acid increases [H ⁺] but its percent dissociation",
    topic: "Acid-Base Equilibria",
    explanation: "By Ostwald's dilution law the degree of dissociation rises on dilution and falls at higher concentration, even though the absolute [H⁺] increases with concentration.",
    choices: [
      { text: "decreases", isCorrect: true },
      { text: "increases" },
      { text: "stays exactly constant" },
      { text: "becomes zero" },
    ],
  },
  {
    stem: "For the reaction 2 A ⇌ B, doubling [A] at fixed [B] changes Q by what factor?",
    topic: "Chemical Equilibrium",
    explanation: "Q = [B]/[A]². Doubling [A] multiplies the denominator by 2² = 4, so Q falls to one-quarter of its value; the system then shifts forward to restore Q = K.",
    choices: [
      { text: "Q becomes one-quarter as large", isCorrect: true },
      { text: "Q doubles" },
      { text: "Q is unchanged" },
      { text: "Q becomes four times as large" },
    ],
  },
  {
    stem: "The cell reaction Zn + Cu ²⁺ → Zn ²⁺ + Cu has Ecell° = +1.10 V. Its ΔG° (n = 2) is",
    topic: "Electrochemistry",
    explanation: "ΔG° = -nFEcell° = -(2)(96485)(1.10) → -2.12 · 10⁵ J → -212 kJ. The negative value confirms a spontaneous, product-favored cell reaction.",
    choices: [
      { text: "about -212 kJ", isCorrect: true },
      { text: "about +212 kJ" },
      { text: "about -106 kJ" },
      { text: "about -1.10 kJ" },
    ],
  },
  {
    stem: "A cell has Ecell° = +0.30 V with n = 2. Raising the product-ion concentration in the cathode compartment will",
    topic: "Electrochemistry",
    explanation: "By the Nernst equation, raising a product concentration increases Q, which lowers E below E°. Lowering products (or raising reactants) would instead raise the emf.",
    choices: [
      { text: "lower the measured cell potential", isCorrect: true },
      { text: "raise the measured cell potential" },
      { text: "leave the potential unchanged" },
      { text: "reverse the sign of E°" },
    ],
  },
  {
    stem: "Which of these is the correct SI unit of the equilibrium constant Kc for A(g) ⇌ B(g)?",
    topic: "Chemical Equilibrium",
    explanation: "For a 1:1 reaction the concentration units cancel, so Kc is dimensionless. In the rigorous treatment all equilibrium constants are dimensionless because they use activities relative to a standard state.",
    choices: [
      { text: "dimensionless (no units)", isCorrect: true },
      { text: "mol/L" },
      { text: "L/mol" },
      { text: "mol²/L²" },
    ],
  },
  {
    stem: "For an electrolysis, the total charge passed by a current of 2.0 A flowing for 965 s is",
    topic: "Electrochemistry",
    explanation: "Charge Q = It = (2.0 A)(965 s) = 1930 C, which is 1930/96485 → 0.020 mol of electrons (0.020 faraday). This charge fixes the amount deposited by Faraday's law.",
    choices: [
      { text: "1930 C", isCorrect: true },
      { text: "965 C" },
      { text: "482 C" },
      { text: "3860 C" },
    ],
  },
  {
    stem: "Which statement correctly distinguishes Kp from Kc?",
    topic: "Chemical Equilibrium",
    explanation: "Kp is expressed using partial pressures of the gases, while Kc uses molar concentrations; they are related by Kp = Kc(RT)Dn. For Dn = 0 they are numerically equal.",
    choices: [
      { text: "Kp uses partial pressures; Kc uses concentrations", isCorrect: true },
      { text: "Kp uses concentrations; Kc uses pressures" },
      { text: "Kp applies only to liquids" },
      { text: "they can never be numerically equal" },
    ],
  },
  {
    stem: "The equilibrium constant of a reaction depends on which single variable?",
    topic: "Chemical Equilibrium",
    explanation: "K depends only on temperature (through ΔG° = -RT ln K). Changing concentrations, pressures, or adding a catalyst shifts the position of equilibrium but never changes K itself.",
    choices: [
      { text: "temperature", isCorrect: true },
      { text: "total pressure" },
      { text: "catalyst amount" },
      { text: "initial concentrations" },
    ],
  },
  {
    stem: "For a redox reaction to be used in a battery, its cell potential Ecell must be",
    topic: "Electrochemistry",
    explanation: "A battery delivers energy from a spontaneous reaction, which requires Ecell > 0 (equivalently ΔG < 0). A non-spontaneous reaction with Ecell < 0 would need an external supply, as in electrolysis.",
    choices: [
      { text: "positive", isCorrect: true },
      { text: "negative" },
      { text: "exactly zero" },
      { text: "independent of concentration" },
    ],
  },
  {
    stem: "The oxidizing agent in a redox reaction is the species that",
    topic: "Electrochemistry",
    explanation: "The oxidizing agent gains electrons and is itself reduced, causing the other species to be oxidized. The reducing agent is the electron donor and is itself oxidized.",
    choices: [
      { text: "is reduced (gains electrons)", isCorrect: true },
      { text: "is oxidized (loses electrons)" },
      { text: "neither gains nor loses electrons" },
      { text: "always contains oxygen" },
    ],
  },
  {
    stem: "For A + B ⇌ C + D at equilibrium, if more A is added the system will",
    topic: "Chemical Equilibrium",
    explanation: "Adding reactant A makes Q < K, so the reaction shifts forward, consuming some added A and B to form more C and D until Q = K again. K stays the same at fixed temperature.",
    choices: [
      { text: "shift forward to form more products", isCorrect: true },
      { text: "shift backward to form more reactants" },
      { text: "remain unchanged because K is fixed" },
      { text: "stop reacting entirely" },
    ],
  },
  {
    stem: "When a reaction is written as the sum of two steps, its overall equilibrium constant equals",
    topic: "Chemical Equilibrium",
    explanation: "For added (sequential) reactions the overall K is the product of the individual constants, K = K₁ · K₂. This follows because free energies add and K is exponential in -ΔG°/RT.",
    choices: [
      { text: "the product of the individual constants", isCorrect: true },
      { text: "the sum of the individual constants" },
      { text: "the difference of the constants" },
      { text: "the average of the constants" },
    ],
  },
  {
    stem: "A porous barrier or salt bridge is unnecessary in a cell only when",
    topic: "Electrochemistry",
    explanation: "If the two half-reactions can share the same solution without reacting directly or mixing incompatibly, no separator is needed; otherwise a salt bridge keeps the compartments neutral while preventing direct mixing.",
    choices: [
      { text: "the reactants would not react if simply mixed", isCorrect: true },
      { text: "the electrodes are made of the same metal" },
      { text: "the cell potential is exactly zero" },
      { text: "the electrolyte is a molten salt only" },
    ],
  },
  {
    stem: "Corrosion of iron is an electrochemical process in which iron acts as the",
    topic: "Electrochemistry",
    explanation: "In rusting, iron is oxidized (Fe → Fe²⁺ + 2 e⁻), so it is the anode; oxygen is reduced at cathodic regions. Sacrificial anodes of more active metals protect iron by being oxidized preferentially.",
    choices: [
      { text: "anode, being oxidized", isCorrect: true },
      { text: "cathode, being reduced" },
      { text: "salt bridge for ion flow" },
      { text: "inert reference electrode" },
    ],
  },
  {
    stem: "The extent to which a weak electrolyte dissociates, expressed as a fraction, is called its",
    topic: "Acid-Base Equilibria",
    explanation: "The degree (or fraction) of dissociation δ is the fraction of the electrolyte that has ionized. By Ostwald's law δ increases on dilution for a weak electrolyte.",
    choices: [
      { text: "degree of dissociation", isCorrect: true },
      { text: "ionic strength" },
      { text: "molar conductivity" },
      { text: "common-ion coefficient" },
    ],
  },
  {
    stem: "An amphoteric species in acid-base chemistry is one that can",
    topic: "Acid-Base Equilibria",
    explanation: "An amphoteric (amphiprotic) species can act as either an acid or a base, donating or accepting a proton depending on its partner. Water is the classic example, forming H⁺ or OH⁻.",
    choices: [
      { text: "act as either an acid or a base", isCorrect: true },
      { text: "only donate protons rapidly" },
      { text: "only accept protons rapidly" },
      { text: "neither donate nor accept protons" },
    ],
  },
  {
    stem: "For a sparingly soluble salt, comparing the ion product Q to Ksp tells you whether",
    topic: "Solubility Equilibria",
    explanation: "If Q > Ksp the solution is supersaturated and a precipitate forms; if Q < Ksp it is unsaturated and more can dissolve; if Q = Ksp it is exactly saturated. This is the precipitation criterion.",
    choices: [
      { text: "a precipitate will form", isCorrect: true },
      { text: "the salt is a strong electrolyte" },
      { text: "the solution conducts electricity" },
      { text: "the reaction is exothermic" },
    ],
  },
  {
    stem: "The standard state chosen for a gas in defining an equilibrium constant is",
    topic: "Chemical Equilibrium",
    explanation: "The conventional standard state for a gas is the pure gas at 1 bar (behaving ideally). Activities are ratios to this standard state, which is why K is dimensionless.",
    choices: [
      { text: "the pure gas at 1 bar", isCorrect: true },
      { text: "the pure gas at 1 atm and 0 °C" },
      { text: "a 1 molar ideal solution" },
      { text: "the gas at its critical point" },
    ],
  },
  {
    stem: "For the water autoionization 2 H₂O ⇌ H₃O ⁺ + OH ⁻, raising the temperature increases Kw. This tells us the autoionization is",
    topic: "Acid-Base Equilibria",
    explanation: "Because Kw rises with temperature, the reaction is endothermic (by van 't Hoff). Consequently neutral pH falls below 7 above 25 °C even though [H⁺] still equals [OH⁻].",
    choices: [
      { text: "endothermic", isCorrect: true },
      { text: "exothermic" },
      { text: "athermal (zero enthalpy)" },
      { text: "spontaneous only at 0 K" },
    ],
  },
  {
    stem: "A reference electrode such as the saturated calomel electrode is used because it",
    topic: "Electrochemistry",
    explanation: "A reference electrode maintains a fixed, known potential regardless of the sample, so the potential of an indicator electrode can be measured against it. Calomel and Ag/AgCl are common practical references.",
    choices: [
      { text: "provides a stable, known potential", isCorrect: true },
      { text: "has the largest possible potential" },
      { text: "consumes the analyte rapidly" },
      { text: "requires no electrolyte at all" },
    ],
  },
  {
    stem: "The quantity 'n' in ΔG° = -nFEcell° for Cu ²⁺ + 2 e ⁻ → Cu paired with Zn → Zn ²⁺ + 2 e ⁻ equals",
    topic: "Electrochemistry",
    explanation: "Both half-reactions transfer 2 electrons, and they must be balanced to the same number, so n = 2 for the overall cell reaction. n is the moles of electrons per mole of reaction as written.",
    choices: [
      { text: "2", isCorrect: true },
      { text: "1" },
      { text: "4" },
      { text: "6" },
    ],
  },
  {
    stem: "If Ecell° for a reaction is negative, the corresponding equilibrium constant K is",
    topic: "Electrochemistry",
    explanation: "Since ln K = nFEcell°/RT, a negative Ecell° gives ln K < 0, so K < 1: the cell reaction is reactant-favored and non-spontaneous under standard conditions.",
    choices: [
      { text: "less than 1", isCorrect: true },
      { text: "greater than 1" },
      { text: "exactly 1" },
      { text: "negative" },
    ],
  },
  {
    stem: "For a gas-phase equilibrium, expressing amounts as mole fractions gives the constant Kx, which depends on total pressure unless",
    topic: "Chemical Equilibrium",
    explanation: "Kx relates to Kp by Kp = KxPDn, so it is pressure-independent only when Dn = 0. Otherwise changing the total pressure changes Kx even though Kp is fixed at constant T.",
    choices: [
      { text: "the change in gas moles is zero", isCorrect: true },
      { text: "the reaction is exothermic" },
      { text: "a catalyst is present" },
      { text: "the temperature is 298 K" },
    ],
  },
  {
    stem: "Le Chatelier's principle predicts the response of a system at equilibrium to",
    topic: "Le Chatelier's Principle",
    explanation: "The principle states that a system at equilibrium responds to an imposed change (in concentration, pressure, or temperature) by shifting so as to partially oppose that change. It is qualitative, not a substitute for K.",
    choices: [
      { text: "an imposed change in conditions", isCorrect: true },
      { text: "the intrinsic reaction rate" },
      { text: "the choice of catalyst material" },
      { text: "the color of the reactants" },
    ],
  },
  {
    stem: "For the equilibrium CaCO₃(s) ⇌ CaO(s) + CO₂(g), the equilibrium constant Kp equals",
    topic: "Chemical Equilibrium",
    explanation: "The two solids have unit activity and drop out, leaving Kp = p(CO₂). Such heterogeneous equilibria depend only on the gas, so decomposition proceeds until a characteristic CO₂ pressure is reached.",
    choices: [
      { text: "p(CO₂)", isCorrect: true },
      { text: "p(CO₂) · [CaO]/[CaCO₃]" },
      { text: "[CaO][CO₂]/[CaCO₃]" },
      { text: "1/p(CO₂)" },
    ],
  },
  {
    stem: "In an electrolytic cell, the sign of the cathode is",
    topic: "Electrochemistry",
    explanation: "In electrolysis the external source makes the cathode negative (it pushes electrons in to drive reduction) and the anode positive. In a galvanic cell the polarity of the labels is reversed, though oxidation/reduction assignments are the same.",
    choices: [
      { text: "negative, driven by the external supply", isCorrect: true },
      { text: "positive, as in a galvanic cell" },
      { text: "neutral, carrying no charge" },
      { text: "undefined without a salt bridge" },
    ],
  },
  {
    stem: "Two half-reactions have E° = +0.80 V (Ag ⁺/Ag) and E° = +0.34 V (Cu ²⁺/Cu). The standard potential of the silver-copper cell is",
    topic: "Electrochemistry",
    explanation: "Silver has the higher reduction potential, so it is the cathode: Ecell° = 0.80 - 0.34 = 0.46 V. The positive value shows the Ag⁺/Cu cell is spontaneous.",
    choices: [
      { text: "+0.46 V", isCorrect: true },
      { text: "+1.14 V" },
      { text: "-0.46 V" },
      { text: "+0.23 V" },
    ],
  },
  {
    stem: "The primary role of concentration in the Nernst equation is captured by which term?",
    topic: "Electrochemistry",
    explanation: "Concentrations enter only through the reaction quotient Q in the -(RT/nF) ln Q term. When all activities are 1, Q = 1 and ln Q = 0, so E reduces to the standard value E°.",
    choices: [
      { text: "the reaction quotient Q", isCorrect: true },
      { text: "the Faraday constant F" },
      { text: "the electron number n" },
      { text: "the standard potential E°" },
    ],
  },
  {
    stem: "A reaction with ΔH° > 0 and ΔS° > 0 has an equilibrium constant K that, as temperature rises,",
    topic: "Equilibrium & Free Energy",
    explanation: "By van 't Hoff, an endothermic reaction (ΔH° > 0) has K increasing with temperature. The positive entropy also makes ΔG° = ΔH° - TΔS° more negative as T rises, reinforcing the trend.",
    choices: [
      { text: "increases", isCorrect: true },
      { text: "decreases" },
      { text: "stays constant" },
      { text: "becomes negative" },
    ],
  },
  {
    stem: "The difference between a strong and a weak electrolyte is best described by",
    topic: "Acid-Base Equilibria",
    explanation: "A strong electrolyte is essentially fully dissociated in solution, while a weak electrolyte is only partially dissociated, setting up an equilibrium between ions and undissociated molecules.",
    choices: [
      { text: "the extent of dissociation into ions", isCorrect: true },
      { text: "the total mass dissolved" },
      { text: "the color of the solution" },
      { text: "the density of the solvent" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which changes will shift the exothermic equilibrium 2 SO₂(g) + O₂(g) ⇌ 2 SO₃(g) toward more product? Select all that apply.",
    topic: "Le Chatelier's Principle",
    explanation: "Product is favored by removing SO₃, by cooling (heat is a product), and by compressing toward fewer gas moles. Adding a catalyst speeds both directions equally and does not shift the position.",
    choices: [
      { text: "removing SO₃ as it forms", isCorrect: true },
      { text: "lowering the temperature", isCorrect: true },
      { text: "increasing the total pressure", isCorrect: true },
      { text: "adding a catalyst" },
      { text: "adding an inert gas at fixed volume" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about the equilibrium constant K are correct? Select all that apply.",
    topic: "Chemical Equilibrium",
    explanation: "K depends only on temperature, is linked to ΔG° by ΔG° = -RT ln K, and omits pure solids and liquids. It is not changed by a catalyst and does not report the reaction rate.",
    choices: [
      { text: "it depends only on temperature", isCorrect: true },
      { text: "it is related to ΔG° by ΔG° = -RT ln K", isCorrect: true },
      { text: "pure solids and liquids are excluded", isCorrect: true },
      { text: "a catalyst increases its value" },
      { text: "it measures how fast equilibrium is reached" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which of the following are true of a galvanic cell? Select all that apply.",
    topic: "Electrochemistry",
    explanation: "A galvanic cell runs a spontaneous reaction, so Ecell° > 0 and ΔG < 0; oxidation is at the anode and reduction at the cathode. It produces, rather than consumes, electrical energy.",
    choices: [
      { text: "its cell potential is positive", isCorrect: true },
      { text: "its ΔG is negative", isCorrect: true },
      { text: "oxidation occurs at the anode", isCorrect: true },
      { text: "it consumes external electrical energy" },
      { text: "reduction occurs at the anode" },
    ],
  },
  {
    type: "MULTI",
    stem: "According to the Nernst equation, which changes lower a cell's potential below E°? Select all that apply.",
    topic: "Electrochemistry",
    explanation: "E falls when Q rises above 1: increasing product concentrations or decreasing reactant concentrations both do this. Raising reactant concentration or lowering product concentration would raise E instead.",
    choices: [
      { text: "increasing a product concentration", isCorrect: true },
      { text: "decreasing a reactant concentration", isCorrect: true },
      { text: "increasing a reactant concentration" },
      { text: "decreasing a product concentration" },
      { text: "adding an inert electrode of larger area" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which factors change the position of a gaseous equilibrium (as opposed to K itself)? Select all that apply.",
    topic: "Le Chatelier's Principle",
    explanation: "Adding or removing a reactant or product, and changing the volume (partial pressures), shift the position. Only temperature changes K; a catalyst changes neither the position nor K.",
    choices: [
      { text: "adding more of a reactant", isCorrect: true },
      { text: "removing a product", isCorrect: true },
      { text: "compressing the mixture to smaller volume", isCorrect: true },
      { text: "adding a catalyst" },
      { text: "changing the value of the gas constant" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about Kp and Kc are correct? Select all that apply.",
    topic: "Chemical Equilibrium",
    explanation: "Kp uses partial pressures and Kc uses concentrations, related by Kp = Kc(RT)Dn. They are equal when Dn = 0. Neither depends on the initial amounts, only on temperature.",
    choices: [
      { text: "Kp is built from partial pressures", isCorrect: true },
      { text: "they are related by Kp = Kc(RT)Dn", isCorrect: true },
      { text: "they are equal when Δn = 0", isCorrect: true },
      { text: "both depend on the starting amounts" },
      { text: "Kc applies only to liquids" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which species are strong oxidizing agents, having large positive reduction potentials? Select all that apply.",
    topic: "Electrochemistry",
    explanation: "F₂ and Cl₂ have large positive reduction potentials and readily gain electrons, so they are strong oxidizers. Alkali metals such as Li and Na have very negative potentials and are strong reducers.",
    choices: [
      { text: "F₂ (fluorine gas)", isCorrect: true },
      { text: "Cl₂ (chlorine gas)", isCorrect: true },
      { text: "Li metal" },
      { text: "Na metal" },
      { text: "Zn metal" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which are correct consequences of ΔG° = -nFEcell°? Select all that apply.",
    topic: "Electrochemistry",
    explanation: "A positive cell potential gives negative ΔG° (spontaneous); ΔG° = 0 corresponds to Ecell° = 0 (equilibrium). Doubling the coefficients doubles both n and ΔG° but leaves Ecell° unchanged.",
    choices: [
      { text: "positive Ecell° means negative ΔG°", isCorrect: true },
      { text: "Ecell° = 0 corresponds to equilibrium", isCorrect: true },
      { text: "Ecell is an intensive property, unchanged by scaling", isCorrect: true },
      { text: "Δ° equals the cell potential times R" },
      { text: "F is the number of electrons transferred" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which statements about buffers are correct? Select all that apply.",
    topic: "Acid-Base Equilibria",
    explanation: "A buffer contains a weak acid and its conjugate base, resists pH change on adding small amounts of acid or base, and works best when pH → pKa. It does not have infinite capacity.",
    choices: [
      { text: "it contains a weak acid and its conjugate base", isCorrect: true },
      { text: "it resists pH change from small additions", isCorrect: true },
      { text: "it is most effective near pH = pKa", isCorrect: true },
      { text: "it can neutralize unlimited added acid" },
      { text: "it fixes the pH at exactly 7" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which changes increase the mass of metal deposited in an electrolysis? Select all that apply.",
    topic: "Electrochemistry",
    explanation: "By Faraday's law the mass rises with the charge passed, so a larger current or a longer time both help. Fewer electrons per ion (smaller n) also gives more moles per faraday. Voltage above the threshold does not by itself set the mass.",
    choices: [
      { text: "increasing the current", isCorrect: true },
      { text: "running the cell for a longer time", isCorrect: true },
      { text: "using an ion needing fewer electrons per atom", isCorrect: true },
      { text: "raising the applied voltage well above threshold" },
      { text: "enlarging the salt bridge" },
    ],
  },
  {
    type: "MULTI",
    stem: "Which of the following leave the equilibrium constant K unchanged? Select all that apply.",
    topic: "Chemical Equilibrium",
    explanation: "K is fixed at constant temperature, so changing concentrations, total pressure (by volume), or adding a catalyst do not change K. Only a change in temperature alters K.",
    choices: [
      { text: "adding more reactant at constant T", isCorrect: true },
      { text: "compressing the mixture at constant T", isCorrect: true },
      { text: "adding a catalyst", isCorrect: true },
      { text: "raising the temperature" },
      { text: "cooling the mixture" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "At equilibrium the forward and reverse reactions occur at equal rates, so concentrations remain constant.",
    topic: "Chemical Equilibrium",
    explanation: "Dynamic equilibrium means the opposing rates are equal, not zero; the reactions continue but net concentrations stay constant. This is the defining feature of chemical equilibrium.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "A catalyst increases the value of the equilibrium constant K.",
    topic: "Le Chatelier's Principle",
    explanation: "False. A catalyst speeds the approach to equilibrium equally in both directions but leaves K and the equilibrium concentrations unchanged; it is a kinetic, not thermodynamic, agent.",
    choices: [
      { text: "True" },
      { text: "False", isCorrect: true },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "In any electrochemical cell, reduction takes place at the cathode.",
    topic: "Electrochemistry",
    explanation: "By definition reduction (gain of electrons) occurs at the cathode and oxidation at the anode, in both galvanic and electrolytic cells. Only the electrode polarity signs differ between the two.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "A positive standard cell potential corresponds to a positive standard reaction free energy.",
    topic: "Electrochemistry",
    explanation: "False. Because ΔG° = -nFEcell°, a positive cell potential gives a negative ΔG°, indicating a spontaneous reaction. The signs are opposite.",
    choices: [
      { text: "True" },
      { text: "False", isCorrect: true },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "The equilibrium constant depends on temperature but not on the initial concentrations of the reactants.",
    topic: "Chemical Equilibrium",
    explanation: "K is set by temperature alone (through ΔG° = -RT ln K); different starting concentrations reach the same K. Initial amounts affect the position reached, not the constant.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "Adding an inert gas at constant volume shifts a gaseous equilibrium toward fewer moles of gas.",
    topic: "Le Chatelier's Principle",
    explanation: "False. At constant volume the partial pressures of the reacting gases are unchanged, so Q is unchanged and there is no shift. Only a volume (pressure) change on the reacting species shifts the equilibrium.",
    choices: [
      { text: "True" },
      { text: "False", isCorrect: true },
    ],
  },
  {
    type: "TRUE_FALSE",
    stem: "According to the Nernst equation, a cell's measured potential equals its standard potential when the reaction quotient Q equals 1.",
    topic: "Electrochemistry",
    explanation: "When Q = 1, ln Q = 0, so the correction term vanishes and E = E°. This is the condition of standard-state activities for all species.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
];
