/**
 * PHYSIOLOGY — PRACTICE SET 5
 * Gastrointestinal Physiology
 *
 * Guyton & Hall / Ganong depth. Gastrointestinal motility and smooth muscle, the
 * enteric nervous system, the gut hormones, salivary, gastric, pancreatic and
 * biliary secretion, and the digestion and absorption of carbohydrates, proteins,
 * fats, water, electrolytes and vitamins. 100 questions.
 *
 * Options are length-matched (the correct answer is not perceptibly the longest)
 * and every distractor is a defensible near-miss. Positions randomized by engine.
 */

import type { Q } from "../_lib/qbank";

export const PHYSIOLOGY_SET_5: Q[] = [
  {
    stem: "The basic electrical rhythm of gastrointestinal smooth muscle, the slow waves, is generated by the:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "The interstitial cells of Cajal act as the pacemakers of the gut, generating the rhythmic slow waves that spread to the smooth muscle; these cells set the maximum frequency of contractions in each region of the digestive tract.",
    choices: [
      { text: "interstitial cells of Cajal", isCorrect: true },
      { text: "neurons of the myenteric plexus" },
      { text: "parietal cells of the stomach" },
      { text: "enterochromaffin cells of the gut" },
    ],
  },
  {
    stem: "Slow waves by themselves do not produce contraction of gut smooth muscle unless they:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "Slow waves are subthreshold oscillations that only trigger contraction when they depolarize far enough to fire spike potentials; neural and hormonal signals shift the baseline so that more or fewer slow waves reach the threshold for spikes.",
    choices: [
      { text: "reach threshold and fire spike potentials", isCorrect: true },
      { text: "are blocked by the myenteric plexus" },
      { text: "occur during the fasting state only" },
      { text: "are triggered by parietal cell activity" },
    ],
  },
  {
    stem: "The frequency of slow waves differs along the gut, being slowest in the:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "The stomach's slow-wave frequency is about three per minute while the duodenum's is around twelve; this regional gradient helps move contents aborally, since each segment can contract only up to its own pacemaker frequency.",
    choices: [
      { text: "stomach at about three per minute", isCorrect: true },
      { text: "duodenum at about twelve per minute" },
      { text: "jejunum at about eleven per minute" },
      { text: "ileum at about nine per minute" },
    ],
  },
  {
    stem: "In peristalsis, a bolus is propelled aborally because the circular muscle:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "Peristalsis is a coordinated reflex in which the circular muscle contracts just behind the bolus while it relaxes just ahead; this moving zone of contraction and receptive relaxation drives contents along the tract in the aboral direction.",
    choices: [
      { text: "contracts behind and relaxes ahead of it", isCorrect: true },
      { text: "contracts ahead and relaxes behind it" },
      { text: "contracts along its whole length at once" },
      { text: "relaxes both behind and ahead of it" },
    ],
  },
  {
    stem: "Segmentation contractions of the small intestine serve mainly to:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "Segmentation is a mixing motion in which non-adjacent segments contract and relax alternately, chopping and blending the chyme with digestive juices and repeatedly exposing it to the absorptive surface, without producing much net forward movement.",
    choices: [
      { text: "mix the chyme with digestive juices", isCorrect: true },
      { text: "propel chyme rapidly toward the colon" },
      { text: "close the intestinal sphincters tightly" },
      { text: "empty the colon during defecation" },
    ],
  },
  {
    stem: "Between meals, a wave of activity called the migrating motor complex sweeps residue through the gut, and it is associated with the hormone:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "During fasting the migrating motor complex periodically sweeps undigested residue and bacteria toward the colon, acting as a housekeeper; its cycles are linked to peaks of the hormone motilin, and they cease once feeding resumes.",
    choices: [
      { text: "motilin", isCorrect: true },
      { text: "secretin" },
      { text: "gastrin" },
      { text: "cholecystokinin" },
    ],
  },
  {
    stem: "Gastrointestinal smooth muscle contracts as a coordinated unit because its cells are electrically coupled by:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "Gap junctions connect adjacent smooth-muscle cells into a functional syncytium, so a slow wave or action potential arising in one region spreads readily to its neighbors; this lets whole segments of the gut wall contract together as a sheet.",
    choices: [
      { text: "gap junctions between the cells", isCorrect: true },
      { text: "desmosomes anchoring the cells" },
      { text: "tight junctions sealing the cells" },
      { text: "motor end plates on each cell" },
    ],
  },
  {
    stem: "Sphincters of the gastrointestinal tract, such as the pyloric sphincter, are characterized by:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "Sphincters maintain a sustained, tonic contraction that keeps them closed between the passage of contents; they relax at the appropriate moment under neural and hormonal control, regulating the flow of material from one segment to the next.",
    choices: [
      { text: "a sustained tonic contraction", isCorrect: true },
      { text: "continuous rhythmic peristalsis" },
      { text: "a complete absence of muscle tone" },
      { text: "purely voluntary skeletal control" },
    ],
  },
  {
    stem: "True or False: Gastrointestinal smooth muscle behaves as a functional syncytium, with gap junctions allowing electrical activity to spread from cell to cell.",
    type: "TRUE_FALSE",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "True. Because the cells are joined by gap junctions, depolarizations propagate through the muscle layer without needing a nerve to each fiber; this electrical coupling underlies the coordinated slow-wave activity and contractions of the gut wall.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "Which statements about gastrointestinal slow waves are correct? Select all that apply.",
    type: "MULTI",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "Slow waves are generated by the interstitial cells of Cajal, set the maximum contraction frequency of each region, cause contraction only when they reach threshold and add spike potentials, and vary in frequency along the tract; they are not made by parietal cells, and not every slow wave yields a contraction.",
    choices: [
      { text: "they are generated by interstitial cells of Cajal", isCorrect: true },
      { text: "they set the maximum contraction frequency", isCorrect: true },
      { text: "they need spike potentials to cause contraction", isCorrect: true },
      { text: "their frequency varies along the gut", isCorrect: true },
      { text: "they are generated by the parietal cells" },
      { text: "each slow wave always causes a contraction" },
    ],
  },
  {
    stem: "The two smooth-muscle layers of the gut wall differ in orientation, with contraction of the longitudinal layer acting to:",
    topic: "GI Motility & Smooth Muscle",
    explanation:
      "The inner circular layer narrows the lumen when it contracts, while the outer longitudinal layer shortens the segment; the alternating and coordinated action of the two layers produces both the mixing and the propulsive movements of the gut.",
    choices: [
      { text: "shorten the length of the segment", isCorrect: true },
      { text: "narrow the diameter of the lumen" },
      { text: "close the nearby sphincter tightly" },
      { text: "generate the pacemaker slow waves" },
    ],
  },
  {
    stem: "The myenteric (Auerbach's) plexus of the enteric nervous system primarily controls:",
    topic: "Enteric Nervous System",
    explanation:
      "The myenteric plexus lies between the circular and longitudinal muscle layers and mainly governs gut motility, coordinating the tone and rhythm of contractions; the submucosal plexus, by contrast, chiefly regulates secretion and local blood flow.",
    choices: [
      { text: "the motility of the gut wall", isCorrect: true },
      { text: "the secretion of the glands" },
      { text: "the local intestinal blood flow" },
      { text: "the sensation of gut pain" },
    ],
  },
  {
    stem: "The submucosal (Meissner's) plexus is mainly concerned with the control of:",
    topic: "Enteric Nervous System",
    explanation:
      "The submucosal plexus sits in the submucosa near the glands and vessels and chiefly regulates glandular secretion and local blood flow, and it senses the luminal environment; motility is handled mostly by the myenteric plexus deeper in the wall.",
    choices: [
      { text: "glandular secretion and blood flow", isCorrect: true },
      { text: "the rhythm of peristaltic waves" },
      { text: "the tone of the two muscle layers" },
      { text: "the frequency of the slow waves" },
    ],
  },
  {
    stem: "True or False: The enteric nervous system can coordinate reflexes within the gut wall even when its connections to the central nervous system are cut.",
    type: "TRUE_FALSE",
    topic: "Enteric Nervous System",
    explanation:
      "True. With its own sensory neurons, interneurons, and motor neurons, the enteric nervous system functions as a semi-autonomous integrative network, often called the gut's little brain; central input modulates but is not required for many local reflexes.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "Parasympathetic input to the gut, carried largely by the vagus nerve, generally acts to:",
    topic: "Enteric Nervous System",
    explanation:
      "Parasympathetic activity stimulates digestive function, increasing motility and glandular secretion and relaxing sphincters to allow flow; sympathetic activity opposes this, slowing motility, contracting sphincters, and reducing blood flow to the gut.",
    choices: [
      { text: "increase gut motility and secretion", isCorrect: true },
      { text: "decrease gut motility and secretion" },
      { text: "contract all the gut sphincters" },
      { text: "reduce the intestinal blood flow" },
    ],
  },
  {
    stem: "Sympathetic stimulation of the gastrointestinal tract characteristically:",
    topic: "Enteric Nervous System",
    explanation:
      "The sympathetic outflow inhibits the enteric neurons that drive motility and secretion, contracts the sphincters, and constricts the gut vasculature; this dampening of digestive activity is part of the diversion of resources during stress.",
    choices: [
      { text: "inhibits motility and contracts sphincters", isCorrect: true },
      { text: "stimulates motility and relaxes sphincters" },
      { text: "increases glandular secretion strongly" },
      { text: "dilates the intestinal blood vessels" },
    ],
  },
  {
    stem: "Relaxation of gastrointestinal smooth muscle, as when a sphincter opens, is mediated by inhibitory enteric transmitters such as:",
    topic: "Enteric Nervous System",
    explanation:
      "Enteric inhibitory motor neurons release nitric oxide and vasoactive intestinal peptide to relax smooth muscle, allowing receptive relaxation and sphincter opening; loss of these neurons, as in achalasia, leaves the muscle unable to relax normally.",
    choices: [
      { text: "nitric oxide and vasoactive intestinal peptide", isCorrect: true },
      { text: "acetylcholine and substance P" },
      { text: "norepinephrine and neuropeptide Y" },
      { text: "histamine and serotonin together" },
    ],
  },
  {
    stem: "The vagovagal reflex that relaxes the stomach to receive a meal without a large rise in pressure is called:",
    topic: "Enteric Nervous System",
    explanation:
      "As food arrives, vagal afferents trigger vagal efferents that relax the gastric smooth muscle, letting the stomach expand to accommodate the meal with little pressure change; this receptive relaxation depends on inhibitory nitric oxide and peptide signals.",
    choices: [
      { text: "receptive relaxation of the stomach", isCorrect: true },
      { text: "the gastrocolic propulsive reflex" },
      { text: "the enterogastric inhibitory reflex" },
      { text: "the migrating motor complex" },
    ],
  },
  {
    stem: "Distension or arrival of a meal in the stomach can trigger mass movements in the colon through the:",
    topic: "Enteric Nervous System",
    explanation:
      "The gastrocolic reflex links a meal in the stomach to increased colonic motility, often producing an urge to defecate after eating; it is mediated partly by the autonomic nervous system and partly by gut hormones released with feeding.",
    choices: [
      { text: "gastrocolic reflex", isCorrect: true },
      { text: "enterogastric reflex" },
      { text: "cephalic vagal reflex" },
      { text: "intestino-intestinal reflex" },
    ],
  },
  {
    stem: "A rise in acidity or fat in the duodenum slows gastric emptying through the:",
    topic: "Enteric Nervous System",
    explanation:
      "The enterogastric reflex, together with hormones such as cholecystokinin and secretin, feeds back from the duodenum to inhibit gastric emptying when the duodenal load of acid, fat, or hypertonic chyme is high, protecting the intestine from overload.",
    choices: [
      { text: "enterogastric inhibitory reflex", isCorrect: true },
      { text: "gastrocolic excitatory reflex" },
      { text: "cephalic phase vagal reflex" },
      { text: "defecation spinal reflex" },
    ],
  },
  {
    stem: "Which effects follow parasympathetic (vagal) stimulation of the gut? Select all that apply.",
    type: "MULTI",
    topic: "Enteric Nervous System",
    explanation:
      "Vagal activity turns up digestion: it increases gastric acid and pancreatic secretion, enhances motility, and relaxes the stomach and sphincters to admit food; contracting the sphincters and cutting intestinal blood flow are sympathetic, not vagal, effects.",
    choices: [
      { text: "increased gastric acid secretion", isCorrect: true },
      { text: "increased gut motility", isCorrect: true },
      { text: "relaxation of the stomach for a meal", isCorrect: true },
      { text: "increased pancreatic secretion", isCorrect: true },
      { text: "tight contraction of the sphincters" },
      { text: "reduced intestinal blood flow" },
    ],
  },
  {
    stem: "Local reflexes entirely within the gut wall, not requiring the brain or spinal cord, are examples of:",
    topic: "Enteric Nervous System",
    explanation:
      "Intrinsic reflexes are integrated wholly within the enteric plexuses, coordinating secretion and motility over short distances; extrinsic reflexes, in contrast, travel to the central nervous system and back and adjust the gut to the needs of the whole body.",
    choices: [
      { text: "intrinsic enteric reflexes", isCorrect: true },
      { text: "extrinsic autonomic reflexes" },
      { text: "somatic motor reflexes" },
      { text: "central baroreceptor reflexes" },
    ],
  },
  {
    stem: "The pharyngeal phase of swallowing is best described as:",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "Once a bolus is pushed into the pharynx, sensory receptors trigger a programmed, involuntary sequence coordinated by the swallowing center in the medulla; unlike the initial oral phase, this pharyngeal phase cannot be consciously controlled once begun.",
    choices: [
      { text: "involuntary and reflexively controlled", isCorrect: true },
      { text: "entirely voluntary and conscious" },
      { text: "driven by the enteric plexus alone" },
      { text: "independent of the medulla oblongata" },
    ],
  },
  {
    stem: "A secondary peristaltic wave in the esophagus is triggered by:",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "If a primary wave fails to clear the esophagus, the distension caused by retained food itself sets off a secondary peristaltic wave; this local reflex, mediated by the enteric and vagal circuitry, helps strip the esophagus clean without another swallow.",
    choices: [
      { text: "distension by food left in the esophagus", isCorrect: true },
      { text: "voluntary initiation of another swallow" },
      { text: "relaxation of the upper sphincter" },
      { text: "a fall in the esophageal pressure" },
    ],
  },
  {
    stem: "The lower esophageal sphincter relaxes to admit a swallowed bolus into the stomach through the action of:",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "As the peristaltic wave approaches, inhibitory enteric neurons release nitric oxide and vasoactive intestinal peptide to relax the normally contracted lower esophageal sphincter; after the bolus passes, the sphincter regains its tone to prevent reflux.",
    choices: [
      { text: "inhibitory nitric oxide and peptide signals", isCorrect: true },
      { text: "excitatory acetylcholine release" },
      { text: "circulating epinephrine in the blood" },
      { text: "a reflex rise in sphincter tone" },
    ],
  },
  {
    stem: "Achalasia, with failure of the lower esophageal sphincter to relax and loss of esophageal peristalsis, results from degeneration of the:",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "Achalasia arises from loss of the inhibitory myenteric neurons that normally relax the sphincter and coordinate peristalsis; without them the sphincter stays contracted and the body of the esophagus cannot propel food, so the esophagus dilates above.",
    choices: [
      { text: "inhibitory myenteric neurons", isCorrect: true },
      { text: "excitatory vagal motor fibers" },
      { text: "interstitial cells of Cajal" },
      { text: "striated muscle of the pharynx" },
    ],
  },
  {
    stem: "During the pharyngeal phase, the airway is protected from aspiration chiefly because:",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "Swallowing briefly halts breathing and elevates the larynx while the epiglottis folds over the laryngeal inlet, directing the bolus toward the esophagus; this reflex closure of the airway prevents food or liquid from entering the trachea.",
    choices: [
      { text: "the epiglottis covers the laryngeal inlet", isCorrect: true },
      { text: "the lower sphincter contracts firmly" },
      { text: "the stomach relaxes to receive food" },
      { text: "the tongue seals the nasopharynx off" },
    ],
  },
  {
    stem: "True or False: The lower esophageal sphincter is normally contracted at rest and relaxes with swallowing to let the bolus pass into the stomach.",
    type: "TRUE_FALSE",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "True. Its resting tone forms a barrier against reflux of gastric contents, and it opens only transiently as a swallow arrives; a chronically weak or inappropriately relaxing sphincter allows the acid reflux that characterizes reflux disease.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "Which events occur during the pharyngeal phase of swallowing? Select all that apply.",
    type: "MULTI",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "The pharyngeal phase seals off the airway and nasopharynx and opens the route to the esophagus: the soft palate elevates, the epiglottis covers the larynx, breathing pauses, and the upper esophageal sphincter relaxes; the lower sphincter does not clamp shut, and the phase is involuntary rather than voluntary.",
    choices: [
      { text: "the soft palate elevates to seal the nasopharynx", isCorrect: true },
      { text: "the epiglottis covers the laryngeal opening", isCorrect: true },
      { text: "breathing is briefly inhibited", isCorrect: true },
      { text: "the upper esophageal sphincter relaxes", isCorrect: true },
      { text: "the lower esophageal sphincter clamps shut" },
      { text: "voluntary effort drives the whole phase" },
    ],
  },
  {
    stem: "Reflux disease commonly results when the lower esophageal sphincter is:",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "When the sphincter's resting tone is too low or it relaxes inappropriately, gastric acid can move up into the esophagus, whose lining is poorly protected against it; the resulting mucosal injury produces the symptoms of gastroesophageal reflux disease.",
    choices: [
      { text: "weak or inappropriately relaxed", isCorrect: true },
      { text: "excessively tight and contracted" },
      { text: "replaced by striated muscle" },
      { text: "missing its enteric neurons" },
    ],
  },
  {
    stem: "A primary peristaltic wave of the esophagus is:",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "The primary wave is a continuation of the pharyngeal swallow, sweeping the length of the esophagus and driving the bolus toward the stomach; it is initiated by the act of swallowing rather than by local distension, which triggers secondary waves.",
    choices: [
      { text: "a continuation of the swallow itself", isCorrect: true },
      { text: "triggered by esophageal distension" },
      { text: "confined to the upper sphincter" },
      { text: "independent of the swallowing act" },
    ],
  },
  {
    stem: "As a bolus enters the stomach during swallowing, the stomach undergoes:",
    topic: "Swallowing & Esophageal Motility",
    explanation:
      "The arrival of food is anticipated by a vagally mediated receptive relaxation, so the proximal stomach expands to hold the meal with little rise in intragastric pressure; this accommodation allows a large meal to be stored before it is processed.",
    choices: [
      { text: "a vagally mediated receptive relaxation", isCorrect: true },
      { text: "a strong retropulsive contraction" },
      { text: "closure of the pyloric sphincter alone" },
      { text: "a burst of migrating motor activity" },
    ],
  },
  {
    stem: "The parietal cells of the gastric mucosa secrete hydrochloric acid and:",
    topic: "Gastric Secretion",
    explanation:
      "Parietal cells produce both the acid that denatures proteins and activates pepsin and the intrinsic factor needed for vitamin B-twelve absorption in the ileum; their loss therefore causes both low acid output and a risk of B-twelve deficiency.",
    choices: [
      { text: "intrinsic factor for B-twelve", isCorrect: true },
      { text: "pepsinogen for digestion" },
      { text: "gastrin for acid control" },
      { text: "protective surface mucus" },
    ],
  },
  {
    stem: "The chief cells of the gastric glands secrete:",
    topic: "Gastric Secretion",
    explanation:
      "Chief cells release pepsinogen, the inactive precursor that gastric acid converts to the protein-splitting enzyme pepsin; because it is stored and secreted as a zymogen, the enzyme does not digest the cells that make it.",
    choices: [
      { text: "pepsinogen, a proenzyme", isCorrect: true },
      { text: "hydrochloric acid" },
      { text: "intrinsic factor" },
      { text: "the hormone gastrin" },
    ],
  },
  {
    stem: "Gastrin, the hormone that drives gastric acid secretion, is released from the:",
    topic: "Gastric Secretion",
    explanation:
      "The G cells of the gastric antrum secrete gastrin into the blood in response to peptides, distension, and vagal signals; gastrin then stimulates acid output both directly and by releasing histamine from nearby enterochromaffin-like cells.",
    choices: [
      { text: "G cells of the antrum", isCorrect: true },
      { text: "parietal cells of the body" },
      { text: "chief cells of the glands" },
      { text: "D cells of the antrum" },
    ],
  },
  {
    stem: "The parietal cell secretes acid across its apical membrane by means of the:",
    topic: "Gastric Secretion",
    explanation:
      "The hydrogen-potassium ATPase, the proton pump, exchanges intracellular hydrogen ions for potassium, driving hydrogen into the lumen against a steep gradient; drugs that block this pump are the most powerful suppressors of acid secretion.",
    choices: [
      { text: "hydrogen-potassium ATPase pump", isCorrect: true },
      { text: "sodium-potassium ATPase pump" },
      { text: "sodium-hydrogen exchanger" },
      { text: "chloride-bicarbonate exchanger" },
    ],
  },
  {
    stem: "The three physiological stimulants that act directly on the parietal cell to promote acid secretion are acetylcholine, gastrin, and:",
    topic: "Gastric Secretion",
    explanation:
      "Acetylcholine from vagal fibers, gastrin from G cells, and histamine from enterochromaffin-like cells together stimulate the parietal cell; histamine strongly potentiates the others, which is why histamine-receptor blockers markedly reduce acid output.",
    choices: [
      { text: "histamine from local cells", isCorrect: true },
      { text: "secretin from the duodenum" },
      { text: "somatostatin from D cells" },
      { text: "cholecystokinin from the gut" },
    ],
  },
  {
    stem: "When the pH of the gastric antrum falls too low, acid secretion is reined in because the acid stimulates release of:",
    topic: "Gastric Secretion",
    explanation:
      "A low antral pH triggers D cells to release somatostatin, which inhibits gastrin release and acid secretion; this negative feedback prevents the stomach from becoming excessively acidic once the buffering effect of a meal has passed.",
    choices: [
      { text: "somatostatin from D cells", isCorrect: true },
      { text: "gastrin from the G cells" },
      { text: "histamine from mast cells" },
      { text: "intrinsic factor from parietal cells" },
    ],
  },
  {
    stem: "The cephalic phase of gastric acid secretion is triggered by:",
    topic: "Gastric Secretion",
    explanation:
      "Before food even reaches the stomach, the sight, smell, taste, and thought of food drive vagal output that stimulates acid and enzyme secretion; this cephalic phase prepares the stomach and accounts for a substantial share of the meal's acid response.",
    choices: [
      { text: "the sight, smell, and thought of food", isCorrect: true },
      { text: "distension of the stomach wall" },
      { text: "chyme arriving in the duodenum" },
      { text: "a fall in the antral pH" },
    ],
  },
  {
    stem: "Pepsinogen secreted by the chief cells is converted to active pepsin by:",
    topic: "Gastric Secretion",
    explanation:
      "Gastric acid cleaves pepsinogen to pepsin, and pepsin then activates more pepsinogen in an autocatalytic loop; because pepsin works best in an acidic environment, the same acid both activates it and provides its optimal working pH.",
    choices: [
      { text: "the acidic gastric juice", isCorrect: true },
      { text: "pancreatic enteropeptidase" },
      { text: "intrinsic factor binding" },
      { text: "bile salts in the lumen" },
    ],
  },
  {
    stem: "Intrinsic factor secreted by the stomach is essential because it is required for the absorption of:",
    topic: "Gastric Secretion",
    explanation:
      "Intrinsic factor binds vitamin B-twelve and is needed for its uptake by specific receptors in the terminal ileum; loss of intrinsic factor, as in pernicious anemia, causes B-twelve deficiency despite adequate dietary intake of the vitamin.",
    choices: [
      { text: "vitamin B-twelve in the ileum", isCorrect: true },
      { text: "dietary iron in the duodenum" },
      { text: "calcium in the jejunum" },
      { text: "folate in the small intestine" },
    ],
  },
  {
    stem: "The gastric mucosa protects itself from its own acid mainly by means of a:",
    topic: "Gastric Secretion",
    explanation:
      "Surface epithelial cells secrete a layer of mucus and bicarbonate that keeps the immediate cell surface near neutral pH despite the acidic lumen; breakdown of this mucus-bicarbonate barrier exposes the mucosa to acid and pepsin and can cause ulceration.",
    choices: [
      { text: "mucus and bicarbonate barrier", isCorrect: true },
      { text: "thick layer of keratin" },
      { text: "continuous acid-proof membrane" },
      { text: "coating of digestive enzymes" },
    ],
  },
  {
    stem: "Which gastric cell types and their secretions are correctly paired? Select all that apply.",
    type: "MULTI",
    topic: "Gastric Secretion",
    explanation:
      "The parietal cells make hydrochloric acid, the chief cells make pepsinogen, the G cells make gastrin, and the enterochromaffin-like cells make histamine; pairing the parietal cell with pepsinogen or the chief cell with intrinsic factor is incorrect.",
    choices: [
      { text: "parietal cells secrete hydrochloric acid", isCorrect: true },
      { text: "chief cells secrete pepsinogen", isCorrect: true },
      { text: "G cells secrete the hormone gastrin", isCorrect: true },
      { text: "ECL cells secrete histamine", isCorrect: true },
      { text: "parietal cells secrete pepsinogen" },
      { text: "chief cells secrete intrinsic factor" },
    ],
  },
  {
    stem: "True or False: Histamine from enterochromaffin-like cells amplifies the acid response to gastrin and acetylcholine, which is why histamine-receptor blockers reduce acid secretion.",
    type: "TRUE_FALSE",
    topic: "Gastric Secretion",
    explanation:
      "True. Histamine acting on parietal-cell H-two receptors potentiates the effects of the other two stimulants, so much of gastrin's and acetylcholine's action is histamine-dependent; blocking the H-two receptor therefore lowers acid output substantially.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "Mixing in the stomach involves strong antral contractions that squirt chyme back toward the body of the stomach through a nearly closed pylorus, a process called:",
    topic: "Gastric Motility & Emptying",
    explanation:
      "As a peristaltic wave reaches the narrowed pylorus, only a little chyme passes while most is forced backward, a retropulsion that grinds and mixes the contents; this repeated churning reduces solids to particles small enough to empty.",
    choices: [
      { text: "retropulsion of the chyme", isCorrect: true },
      { text: "receptive relaxation" },
      { text: "the migrating motor complex" },
      { text: "segmentation of the antrum" },
    ],
  },
  {
    stem: "Gastric emptying is reflexly slowed by signals from the duodenum when the arriving chyme is:",
    topic: "Gastric Motility & Emptying",
    explanation:
      "The duodenum feeds back to restrain emptying when the chyme is too acidic, fatty, or hypertonic, so that its digestive and neutralizing capacity is not overwhelmed; this matching protects the small intestine and optimizes digestion.",
    choices: [
      { text: "acidic, fatty, or hypertonic", isCorrect: true },
      { text: "alkaline and isotonic only" },
      { text: "purely liquid and neutral" },
      { text: "low in fat and protein" },
    ],
  },
  {
    stem: "Compared with solids, liquids empty from the stomach:",
    topic: "Gastric Motility & Emptying",
    explanation:
      "Liquids pass the pylorus quickly, whereas solids must first be ground by antral contractions into small particles before they can empty; this is why a fatty solid meal leaves the stomach far more slowly than a drink of water.",
    choices: [
      { text: "faster, needing no grinding", isCorrect: true },
      { text: "slower, needing more grinding" },
      { text: "at exactly the same rate" },
      { text: "only during the fasting state" },
    ],
  },
  {
    stem: "The hormone cholecystokinin, released when fat enters the duodenum, affects the stomach by:",
    topic: "Gastric Motility & Emptying",
    explanation:
      "Cholecystokinin slows gastric emptying so that fat is delivered to the small intestine no faster than it can be digested and absorbed; at the same time it stimulates the pancreas and gallbladder to supply the enzymes and bile that fat requires.",
    choices: [
      { text: "slowing the rate of gastric emptying", isCorrect: true },
      { text: "speeding the rate of gastric emptying" },
      { text: "increasing the gastric acid output" },
      { text: "relaxing the lower esophageal sphincter" },
    ],
  },
  {
    stem: "Between meals, indigestible residue is cleared from the stomach and small intestine by the:",
    topic: "Gastric Motility & Emptying",
    explanation:
      "The migrating motor complex is a cyclic front of activity in the fasting gut that sweeps residue, bacteria, and debris toward the colon; it keeps the upper tract clean and is interrupted as soon as the next meal is eaten.",
    choices: [
      { text: "migrating motor complex", isCorrect: true },
      { text: "gastrocolic reflex" },
      { text: "receptive relaxation" },
      { text: "retropulsion process" },
    ],
  },
  {
    stem: "The pyloric sphincter regulates gastric emptying by:",
    topic: "Gastric Motility & Emptying",
    explanation:
      "The pylorus stays largely closed during antral contractions so that only small, well-mixed particles and liquids escape into the duodenum; its degree of opening is adjusted by neural and hormonal feedback to control the emptying rate.",
    choices: [
      { text: "allowing only small particles to pass", isCorrect: true },
      { text: "letting large solids pass first" },
      { text: "staying fully open at all times" },
      { text: "preventing any emptying at all" },
    ],
  },
  {
    stem: "The overall rate of gastric emptying is normally matched to the:",
    topic: "Gastric Motility & Emptying",
    explanation:
      "Emptying is regulated so that chyme is delivered to the duodenum only as fast as the small intestine can process and neutralize it; feedback from duodenal acid, fat, and osmolarity continually tunes the emptying rate to intestinal capacity.",
    choices: [
      { text: "processing capacity of the duodenum", isCorrect: true },
      { text: "total volume of the last meal" },
      { text: "acidity of the gastric juice" },
      { text: "frequency of the antral slow waves" },
    ],
  },
  {
    stem: "The act of vomiting is coordinated by a center located in the:",
    topic: "Gastric Motility & Emptying",
    explanation:
      "A vomiting center in the medulla integrates inputs from the gut, the vestibular system, and the chemoreceptor trigger zone, then orchestrates the reflex; the sequence reverses upper gut motility and uses abdominal muscles to expel gastric contents.",
    choices: [
      { text: "medulla of the brainstem", isCorrect: true },
      { text: "wall of the gastric antrum" },
      { text: "myenteric plexus of the gut" },
      { text: "cortex of the frontal lobe" },
    ],
  },
  {
    stem: "Which factors slow the rate of gastric emptying? Select all that apply.",
    type: "MULTI",
    topic: "Gastric Motility & Emptying",
    explanation:
      "Emptying is delayed by a high fat content, a high acidity, and hypertonic chyme in the duodenum, and by the release of cholecystokinin; a large volume of isotonic liquid or a low fat load in the duodenum instead allow faster emptying.",
    choices: [
      { text: "a high fat content of the chyme", isCorrect: true },
      { text: "a high acidity in the duodenum", isCorrect: true },
      { text: "hypertonic contents in the duodenum", isCorrect: true },
      { text: "release of cholecystokinin", isCorrect: true },
      { text: "a large volume of isotonic liquid" },
      { text: "a low duodenal fat load" },
    ],
  },
  {
    stem: "True or False: Liquids generally leave the stomach faster than solids, which must first be ground into small particles before passing the pylorus.",
    type: "TRUE_FALSE",
    topic: "Gastric Motility & Emptying",
    explanation:
      "True. The antral pump reduces solids to a fine suspension before they can escape the nearly closed pylorus, whereas liquids slip through readily; this difference explains why the composition of a meal strongly influences its emptying time.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "The duct cells of the exocrine pancreas secrete a watery fluid that is especially rich in:",
    topic: "Pancreatic Secretion",
    explanation:
      "The pancreatic duct cells secrete a bicarbonate-rich alkaline fluid that neutralizes the acid entering the duodenum from the stomach; this protects the mucosa and provides the near-neutral pH at which the pancreatic enzymes work best.",
    choices: [
      { text: "bicarbonate to neutralize acid", isCorrect: true },
      { text: "digestive proteolytic enzymes" },
      { text: "bile salts for fat handling" },
      { text: "intrinsic factor for B-twelve" },
    ],
  },
  {
    stem: "Secretin, released from the duodenum in response to acid, stimulates the pancreas to secrete:",
    topic: "Pancreatic Secretion",
    explanation:
      "Acid in the duodenum releases secretin, which acts mainly on the duct cells to pour out a bicarbonate-rich fluid; this raises duodenal pH toward neutral, both protecting the mucosa and creating the optimal environment for digestive enzymes.",
    choices: [
      { text: "a bicarbonate-rich watery fluid", isCorrect: true },
      { text: "a concentrated enzyme-rich fluid" },
      { text: "a bile-salt-rich secretion" },
      { text: "a mucus-rich protective fluid" },
    ],
  },
  {
    stem: "Cholecystokinin, released when fat and protein reach the duodenum, stimulates the pancreas to secrete:",
    topic: "Pancreatic Secretion",
    explanation:
      "Cholecystokinin acts on the acinar cells to release the digestive enzymes, and it also contracts the gallbladder; its output rises with a fatty, protein-rich meal, matching enzyme and bile delivery to the food that needs them.",
    choices: [
      { text: "enzymes from the acinar cells", isCorrect: true },
      { text: "bicarbonate from the duct cells" },
      { text: "acid from the gastric glands" },
      { text: "mucus from the surface cells" },
    ],
  },
  {
    stem: "Pancreatic proteases are secreted as inactive zymogens, and trypsinogen is converted to active trypsin in the gut by:",
    topic: "Pancreatic Secretion",
    explanation:
      "The brush-border enzyme enteropeptidase, also called enterokinase, activates trypsinogen to trypsin in the duodenum; trypsin then activates the remaining zymogens, so this single step launches the whole cascade of pancreatic protein digestion.",
    choices: [
      { text: "brush-border enteropeptidase", isCorrect: true },
      { text: "gastric hydrochloric acid" },
      { text: "pancreatic amylase enzyme" },
      { text: "bile salts in the lumen" },
    ],
  },
  {
    stem: "Once formed in the duodenum, active trypsin serves to:",
    topic: "Pancreatic Secretion",
    explanation:
      "Beyond digesting protein itself, trypsin activates the other pancreatic zymogens, including chymotrypsinogen and procarboxypeptidase; this amplifying role means that regulating trypsinogen activation controls activation of the whole proteolytic set.",
    choices: [
      { text: "activate the other pancreatic zymogens", isCorrect: true },
      { text: "inactivate the pancreatic enzymes" },
      { text: "secrete bicarbonate into the duct" },
      { text: "bind vitamin B-twelve for uptake" },
    ],
  },
  {
    stem: "The bicarbonate in pancreatic juice is physiologically important because it:",
    topic: "Pancreatic Secretion",
    explanation:
      "Neutralizing the acidic chyme raises the duodenal pH toward neutral, both protecting the intestinal mucosa from acid injury and providing the near-neutral environment in which pancreatic and brush-border enzymes achieve their optimal activity.",
    choices: [
      { text: "neutralizes acid entering the duodenum", isCorrect: true },
      { text: "digests the dietary fat directly" },
      { text: "activates the gastric pepsinogen" },
      { text: "emulsifies the fat into droplets" },
    ],
  },
  {
    stem: "The pancreas protects itself from being digested by its own proteases mainly because the enzymes are:",
    topic: "Pancreatic Secretion",
    explanation:
      "The proteases are made and stored as inactive zymogens and are only activated after they reach the gut; a trypsin inhibitor within the acinar cells provides a further safeguard, and failure of these protections underlies acute pancreatitis.",
    choices: [
      { text: "stored and secreted as inactive zymogens", isCorrect: true },
      { text: "secreted already in their active form" },
      { text: "kept apart from all cell membranes" },
      { text: "digested by bile salts in the duct" },
    ],
  },
  {
    stem: "A deficiency of pancreatic enzyme secretion characteristically leads to:",
    topic: "Pancreatic Secretion",
    explanation:
      "Without adequate pancreatic lipase and other enzymes, fat and other nutrients are poorly digested and absorbed; the result is steatorrhea, the passage of pale, greasy, foul stools, along with weight loss and deficiency of fat-soluble vitamins.",
    choices: [
      { text: "fatty malabsorptive stools", isCorrect: true },
      { text: "excessive gastric acid output" },
      { text: "obstruction of the bile duct" },
      { text: "overactivity of the gallbladder" },
    ],
  },
  {
    stem: "The cephalic and gastric phases contribute to pancreatic secretion largely through the action of the:",
    topic: "Pancreatic Secretion",
    explanation:
      "Vagal stimulation during the cephalic and gastric phases primes the pancreas to secrete even before nutrients reach the intestine; the largest secretory response, however, comes in the intestinal phase from secretin and cholecystokinin.",
    choices: [
      { text: "vagus nerve on the pancreas", isCorrect: true },
      { text: "splanchnic sympathetic nerves" },
      { text: "secretin from the duodenum" },
      { text: "somatostatin from the islets" },
    ],
  },
  {
    stem: "Which actions are triggered by cholecystokinin? Select all that apply.",
    type: "MULTI",
    topic: "Pancreatic Secretion",
    explanation:
      "Cholecystokinin secretes pancreatic enzymes, contracts the gallbladder, relaxes the sphincter of Oddi, and slows gastric emptying, coordinating the delivery of enzymes and bile with the pace of feeding; it does not drive gastric acid or ductal bicarbonate output.",
    choices: [
      { text: "secretion of pancreatic enzymes", isCorrect: true },
      { text: "contraction of the gallbladder", isCorrect: true },
      { text: "relaxation of the sphincter of Oddi", isCorrect: true },
      { text: "slowing of the gastric emptying", isCorrect: true },
      { text: "secretion of gastric acid" },
      { text: "secretion of ductal bicarbonate" },
    ],
  },
  {
    stem: "True or False: Secretin stimulates a bicarbonate-rich pancreatic secretion that helps neutralize the gastric acid entering the duodenum.",
    type: "TRUE_FALSE",
    topic: "Pancreatic Secretion",
    explanation:
      "True. Secretin is released in response to duodenal acid and acts on the pancreatic ducts to raise bicarbonate output; the resulting alkaline juice buffers the acid, protecting the mucosa and optimizing the pH for intestinal digestion.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "Bile salts aid the digestion and absorption of dietary fat mainly by:",
    topic: "Bile & Liver Secretion",
    explanation:
      "Bile salts are amphipathic molecules that emulsify large fat globules into tiny droplets and then form mixed micelles with the products of lipolysis; the micelles ferry these poorly soluble products to the enterocyte surface for absorption.",
    choices: [
      { text: "emulsifying fat and forming micelles", isCorrect: true },
      { text: "splitting triglycerides into fatty acids" },
      { text: "neutralizing the acid in the duodenum" },
      { text: "transporting glucose into the enterocyte" },
    ],
  },
  {
    stem: "The bile salts are synthesized in the liver from:",
    topic: "Bile & Liver Secretion",
    explanation:
      "Hepatocytes make the primary bile acids from cholesterol, and this pathway is a major route for disposing of cholesterol from the body; the bile acids are then conjugated to improve their solubility before secretion into the bile.",
    choices: [
      { text: "cholesterol in the hepatocytes", isCorrect: true },
      { text: "dietary triglyceride fat" },
      { text: "circulating amino acids" },
      { text: "stored hepatic glycogen" },
    ],
  },
  {
    stem: "After they have done their work in the intestine, most bile salts are reabsorbed and returned to the liver from the:",
    topic: "Bile & Liver Secretion",
    explanation:
      "Specific transporters in the terminal ileum reclaim the bile salts, which return to the liver in the portal blood to be secreted again; this enterohepatic circulation recycles the pool many times per meal, so little new synthesis is needed.",
    choices: [
      { text: "terminal ileum by active uptake", isCorrect: true },
      { text: "stomach across its acid mucosa" },
      { text: "proximal duodenum by diffusion" },
      { text: "colon along with the water" },
    ],
  },
  {
    stem: "The gallbladder contributes to fat digestion by storing bile and then, under the influence of cholecystokinin:",
    topic: "Bile & Liver Secretion",
    explanation:
      "Between meals bile is diverted into the gallbladder, which concentrates it by absorbing water and salts; when fat reaches the duodenum, cholecystokinin contracts the gallbladder and relaxes the sphincter of Oddi, delivering a bolus of bile to the gut.",
    choices: [
      { text: "contracting to release the stored bile", isCorrect: true },
      { text: "secreting its own digestive enzymes" },
      { text: "neutralizing the gastric acid load" },
      { text: "synthesizing new bile salts rapidly" },
    ],
  },
  {
    stem: "Bilirubin is made water-soluble for excretion in the bile by conjugation in the liver with:",
    topic: "Bile & Liver Secretion",
    explanation:
      "Hepatocytes conjugate the fat-soluble bilirubin with glucuronic acid, forming a water-soluble product that can be secreted into the bile; a failure of this step, or of bile flow, causes the conjugated or unconjugated forms to accumulate as jaundice.",
    choices: [
      { text: "glucuronic acid", isCorrect: true },
      { text: "a bile salt molecule" },
      { text: "free cholesterol" },
      { text: "a plasma albumin" },
    ],
  },
  {
    stem: "The brown color of normal feces is produced by:",
    topic: "Bile & Liver Secretion",
    explanation:
      "In the gut, bacteria convert conjugated bilirubin into urobilinogen and then into pigmented stercobilin, which gives stool its brown color; obstruction of bile flow removes these pigments and leaves the stool pale and clay-colored.",
    choices: [
      { text: "bacterial breakdown products of bilirubin", isCorrect: true },
      { text: "undigested dietary iron pigments" },
      { text: "secreted pancreatic enzymes" },
      { text: "bile salts lost in the stool" },
    ],
  },
  {
    stem: "Surgical loss of the terminal ileum impairs fat absorption because it interrupts the:",
    topic: "Bile & Liver Secretion",
    explanation:
      "Removing the ileum prevents reclamation of bile salts, so the enterohepatic pool is depleted faster than the liver can replace it; the resulting shortage of bile salts impairs micelle formation and leads to fat malabsorption and steatorrhea.",
    choices: [
      { text: "recycling of the bile salts", isCorrect: true },
      { text: "secretion of pancreatic enzymes" },
      { text: "emptying of the gallbladder" },
      { text: "conjugation of the bilirubin" },
    ],
  },
  {
    stem: "Which of the following are functions of bile? Select all that apply.",
    type: "MULTI",
    topic: "Bile & Liver Secretion",
    explanation:
      "Bile emulsifies dietary fat, forms the micelles that carry lipid products to the mucosa, and serves as the route for excreting bilirubin and excess cholesterol from the body; it does not itself digest protein, nor does it absorb glucose.",
    choices: [
      { text: "emulsification of the dietary fat", isCorrect: true },
      { text: "formation of the mixed micelles", isCorrect: true },
      { text: "excretion of bilirubin pigment", isCorrect: true },
      { text: "excretion of excess cholesterol", isCorrect: true },
      { text: "enzymatic digestion of protein" },
      { text: "direct absorption of glucose" },
    ],
  },
  {
    stem: "Gastrin, secreted by the antral G cells, acts chiefly to:",
    topic: "GI Hormones",
    explanation:
      "Gastrin stimulates gastric acid secretion, both directly on the parietal cell and by releasing histamine, and it promotes growth of the gastric mucosa; its release is driven by peptides and distension and is switched off by a low antral pH.",
    choices: [
      { text: "stimulate gastric acid secretion", isCorrect: true },
      { text: "stimulate pancreatic bicarbonate" },
      { text: "contract the gallbladder wall" },
      { text: "inhibit all gastric secretion" },
    ],
  },
  {
    stem: "Secretin, historically the first hormone ever discovered, is released by duodenal acid and acts mainly to:",
    topic: "GI Hormones",
    explanation:
      "Secretin from the duodenal S cells stimulates the pancreatic ducts and biliary tree to secrete bicarbonate-rich fluid, neutralizing the acid that triggered its release; it thereby protects the duodenum and sets the pH for enzyme action.",
    choices: [
      { text: "stimulate bicarbonate secretion", isCorrect: true },
      { text: "stimulate gastric acid output" },
      { text: "contract the gallbladder wall" },
      { text: "trigger the migrating complex" },
    ],
  },
  {
    stem: "Cholecystokinin, released by fat and protein in the duodenum, has the primary action of:",
    topic: "GI Hormones",
    explanation:
      "Cholecystokinin stimulates pancreatic enzyme secretion and gallbladder contraction and slows gastric emptying, coordinating the arrival of enzymes and bile with a fatty, protein-rich meal; its very name reflects its action on the gallbladder.",
    choices: [
      { text: "stimulating enzyme and bile delivery", isCorrect: true },
      { text: "stimulating gastric acid output" },
      { text: "promoting rapid gastric emptying" },
      { text: "inhibiting the pancreatic enzymes" },
    ],
  },
  {
    stem: "The gut hormone that stimulates insulin release in anticipation of an absorbed glucose load, acting as an incretin, is:",
    topic: "GI Hormones",
    explanation:
      "Glucose-dependent insulinotropic peptide is released from the upper small intestine as nutrients are absorbed and primes the pancreatic beta cells to release insulin; this incretin effect is why oral glucose evokes more insulin than the same dose given intravenously.",
    choices: [
      { text: "glucose-dependent insulinotropic peptide", isCorrect: true },
      { text: "secretin from the duodenum" },
      { text: "motilin from the small intestine" },
      { text: "somatostatin from the islets" },
    ],
  },
  {
    stem: "The hormone motilin, released cyclically during fasting, is associated with the:",
    topic: "GI Hormones",
    explanation:
      "Peaks of motilin during the fasting state are linked to the onset of the migrating motor complex, the housekeeping wave that clears residue from the upper gut; feeding suppresses motilin and interrupts these cycles until the next fast.",
    choices: [
      { text: "migrating motor complex of fasting", isCorrect: true },
      { text: "emptying of the gallbladder" },
      { text: "secretion of gastric acid" },
      { text: "absorption of dietary glucose" },
    ],
  },
  {
    stem: "Somatostatin, released by D cells throughout the gut, is best described as a hormone that:",
    topic: "GI Hormones",
    explanation:
      "Somatostatin broadly inhibits gastrointestinal function, suppressing the release of many gut hormones and reducing acid and enzyme secretion and motility; because of this widespread damping action it is often called the off switch of the gut.",
    choices: [
      { text: "broadly inhibits gut secretion", isCorrect: true },
      { text: "broadly stimulates gut secretion" },
      { text: "acts only on the gallbladder" },
      { text: "stimulates only insulin release" },
    ],
  },
  {
    stem: "Which pairings of a gut hormone with its main stimulus for release are correct? Select all that apply.",
    type: "MULTI",
    topic: "GI Hormones",
    explanation:
      "Gastrin is released by peptides and gastric distension, secretin by duodenal acid, cholecystokinin by fat and protein, and glucose-dependent insulinotropic peptide by absorbed glucose and fat; secretin is not released by luminal glucose alone, nor gastrin by duodenal fat.",
    choices: [
      { text: "gastrin by peptides and distension", isCorrect: true },
      { text: "secretin by duodenal acid", isCorrect: true },
      { text: "cholecystokinin by fat and protein", isCorrect: true },
      { text: "GIP by absorbed glucose and fat", isCorrect: true },
      { text: "secretin by luminal glucose alone" },
      { text: "gastrin by duodenal fat load" },
    ],
  },
  {
    stem: "Glucose and galactose are absorbed across the apical membrane of the enterocyte by:",
    topic: "Carbohydrate & Protein Absorption",
    explanation:
      "These sugars enter the enterocyte against their gradient by a sodium-glucose cotransporter that harnesses the inward sodium gradient; the sodium is then pumped out basolaterally, so the whole process ultimately depends on the sodium-potassium pump.",
    choices: [
      { text: "sodium-coupled cotransport", isCorrect: true },
      { text: "simple passive diffusion" },
      { text: "facilitated diffusion by GLUT5" },
      { text: "receptor-mediated endocytosis" },
    ],
  },
  {
    stem: "Fructose, unlike glucose, is absorbed from the intestinal lumen by:",
    topic: "Carbohydrate & Protein Absorption",
    explanation:
      "Fructose crosses the apical membrane by facilitated diffusion through the GLUT-five transporter, moving down its concentration gradient without needing sodium; this sodium-independent uptake is slower and is why large fructose loads are incompletely absorbed.",
    choices: [
      { text: "facilitated diffusion via GLUT-five", isCorrect: true },
      { text: "sodium-coupled active transport" },
      { text: "digestion into two glucose units" },
      { text: "active transport using ATP directly" },
    ],
  },
  {
    stem: "Dietary starch is first digested by salivary and pancreatic amylase into:",
    topic: "Carbohydrate & Protein Absorption",
    explanation:
      "Amylase cleaves starch into disaccharides and short oligosaccharides such as maltose, which the brush-border enzymes then split into monosaccharides; only these monosaccharides can be absorbed, so both steps are needed to use dietary starch.",
    choices: [
      { text: "disaccharides and oligosaccharides", isCorrect: true },
      { text: "free glucose monomers directly" },
      { text: "amino acids and small peptides" },
      { text: "fatty acids and monoglycerides" },
    ],
  },
  {
    stem: "Protein is absorbed across the enterocyte both as free amino acids and as:",
    topic: "Carbohydrate & Protein Absorption",
    explanation:
      "In addition to free amino acids taken up by specific carriers, the enterocyte absorbs small di- and tripeptides through a proton-coupled peptide transporter; these are then broken down to amino acids inside the cell before entering the portal blood.",
    choices: [
      { text: "small di- and tripeptides", isCorrect: true },
      { text: "intact whole proteins" },
      { text: "long polypeptide chains" },
      { text: "emulsified fat droplets" },
    ],
  },
  {
    stem: "A deficiency of the brush-border enzyme lactase leads to:",
    topic: "Carbohydrate & Protein Absorption",
    explanation:
      "Without lactase, dietary lactose is not split into absorbable monosaccharides, so it remains in the lumen, drawing in water osmotically and being fermented by colonic bacteria; the result is the bloating, gas, and diarrhea of lactose intolerance.",
    choices: [
      { text: "undigested lactose causing diarrhea", isCorrect: true },
      { text: "excess absorption of glucose" },
      { text: "impaired absorption of protein" },
      { text: "malabsorption of dietary fat" },
    ],
  },
  {
    stem: "Which statements about carbohydrate handling in the gut are correct? Select all that apply.",
    type: "MULTI",
    topic: "Carbohydrate & Protein Absorption",
    explanation:
      "Only monosaccharides are absorbed, glucose and galactose by sodium-coupled transport and fructose by facilitated diffusion, and brush-border enzymes complete the digestion of disaccharides; disaccharides are not absorbed intact, and starch must be digested before uptake.",
    choices: [
      { text: "only monosaccharides can be absorbed", isCorrect: true },
      { text: "glucose uses sodium-coupled transport", isCorrect: true },
      { text: "fructose uses facilitated diffusion", isCorrect: true },
      { text: "brush-border enzymes split disaccharides", isCorrect: true },
      { text: "disaccharides are absorbed intact" },
      { text: "starch is absorbed without digestion" },
    ],
  },
  {
    stem: "Dietary triglyceride is digested in the small intestine chiefly by pancreatic:",
    topic: "Lipid Digestion & Absorption",
    explanation:
      "Pancreatic lipase, aided by colipase and the emulsifying action of bile salts, splits triglycerides into free fatty acids and monoglycerides; these products then enter mixed micelles that carry them to the absorptive surface of the enterocyte.",
    choices: [
      { text: "lipase into fatty acids and monoglycerides", isCorrect: true },
      { text: "amylase into simple monosaccharides" },
      { text: "trypsin into free amino acids" },
      { text: "bile salts into glycerol and water" },
    ],
  },
  {
    stem: "Within the enterocyte, absorbed long-chain fatty acids are re-esterified into triglyceride and packaged into:",
    topic: "Lipid Digestion & Absorption",
    explanation:
      "The enterocyte reassembles triglyceride and coats it with protein and phospholipid to form chylomicrons; these lipoprotein particles are too large for the blood capillaries and instead enter the lymphatic vessels of the villus.",
    choices: [
      { text: "chylomicrons for transport", isCorrect: true },
      { text: "free glucose molecules" },
      { text: "small water-soluble peptides" },
      { text: "bile salt micelles" },
    ],
  },
  {
    stem: "Chylomicrons formed in the enterocyte leave the cell and enter the:",
    topic: "Lipid Digestion & Absorption",
    explanation:
      "Because of their size, chylomicrons cannot cross the blood capillary wall and instead pass into the central lacteal, a lymphatic vessel of the villus; they reach the bloodstream only later, by way of the thoracic duct.",
    choices: [
      { text: "lymphatic lacteals of the villus", isCorrect: true },
      { text: "portal venous blood directly" },
      { text: "gastric arterial supply" },
      { text: "bile canaliculi of the liver" },
    ],
  },
  {
    stem: "Unlike long-chain fats, short- and medium-chain fatty acids are absorbed and then:",
    topic: "Lipid Digestion & Absorption",
    explanation:
      "Short- and medium-chain fatty acids are water-soluble enough to pass directly into the portal blood without being packaged into chylomicrons; this simpler route makes them useful nutritionally when lymphatic fat transport or micelle formation is impaired.",
    choices: [
      { text: "pass directly into the portal blood", isCorrect: true },
      { text: "packaged into large chylomicrons" },
      { text: "carried away in the lymphatic vessels" },
      { text: "stored within the enterocyte fat" },
    ],
  },
  {
    stem: "The absorption of the fat-soluble vitamins A, D, E, and K depends on:",
    topic: "Lipid Digestion & Absorption",
    explanation:
      "Because they dissolve in fat, these vitamins are carried in micelles and absorbed along with dietary fat; any condition that impairs fat digestion or bile-salt delivery therefore also causes deficiency of the fat-soluble vitamins.",
    choices: [
      { text: "normal fat digestion and micelles", isCorrect: true },
      { text: "a sodium-coupled transporter" },
      { text: "intrinsic factor from the stomach" },
      { text: "bacterial synthesis in the colon" },
    ],
  },
  {
    stem: "Which statements about fat absorption are correct? Select all that apply.",
    type: "MULTI",
    topic: "Lipid Digestion & Absorption",
    explanation:
      "Bile salts form micelles that ferry lipid products to the enterocyte, long-chain fats are re-esterified and packaged into chylomicrons that enter the lymph, and short-chain fats pass directly into the portal blood; chylomicrons do not enter the portal vein, and bile salts are reabsorbed in the ileum, not the duodenum.",
    choices: [
      { text: "bile salts form micelles that carry lipids", isCorrect: true },
      { text: "long-chain fats are packaged into chylomicrons", isCorrect: true },
      { text: "chylomicrons enter the lymphatic vessels", isCorrect: true },
      { text: "short-chain fats enter the portal blood", isCorrect: true },
      { text: "chylomicrons enter the portal vein directly" },
      { text: "bile salts are reabsorbed in the duodenum" },
    ],
  },
  {
    stem: "True or False: Whereas most absorbed fat enters the lymph as chylomicrons, short- and medium-chain fatty acids pass directly into the portal blood.",
    type: "TRUE_FALSE",
    topic: "Lipid Digestion & Absorption",
    explanation:
      "True. The size and insolubility of long-chain triglyceride force it into chylomicrons and the lymphatics, but shorter fatty acids are soluble enough to enter the portal circulation directly, giving them a faster and simpler absorptive route.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "A gastrin-secreting tumor that drives massive acid output and severe, recurrent peptic ulcers is known as:",
    topic: "Clinical Application",
    explanation:
      "In Zollinger-Ellison syndrome a gastrinoma secretes gastrin unchecked by the normal pH feedback, so acid output is extreme and ulcers recur and appear in unusual sites; the excess acid can also inactivate pancreatic enzymes and cause diarrhea.",
    choices: [
      { text: "Zollinger-Ellison syndrome", isCorrect: true },
      { text: "pernicious anemia" },
      { text: "celiac disease" },
      { text: "achalasia of the cardia" },
    ],
  },
  {
    stem: "The diarrhea of lactose intolerance is fundamentally caused by:",
    topic: "Clinical Application",
    explanation:
      "Undigested lactose is osmotically active, holding water in the lumen, and colonic bacteria ferment it to gas and short-chain acids; the combination produces the osmotic diarrhea, bloating, and flatulence that follow dairy ingestion in lactase-deficient people.",
    choices: [
      { text: "an osmotic load of undigested lactose", isCorrect: true },
      { text: "secretion of excess gastric acid" },
      { text: "loss of intrinsic factor" },
      { text: "infection of the small bowel" },
    ],
  },
  {
    stem: "After extensive ileal resection, diarrhea and fat malabsorption arise partly because bile salts are:",
    topic: "Clinical Application",
    explanation:
      "Loss of the ileal reabsorptive site depletes the bile-salt pool, impairing micelle formation and fat absorption; the unabsorbed bile salts and fatty acids also reach the colon, where they stimulate secretion and produce a watery diarrhea.",
    choices: [
      { text: "not reabsorbed and the pool is depleted", isCorrect: true },
      { text: "secreted in far greater amounts" },
      { text: "converted directly into cholesterol" },
      { text: "prevented from reaching the intestine" },
    ],
  },
  {
    stem: "Cholera toxin produces a profuse watery diarrhea chiefly by driving intestinal:",
    topic: "Clinical Application",
    explanation:
      "The toxin locks adenylyl cyclase on, raising cyclic AMP in the enterocyte and opening chloride channels; the resulting secretion of chloride, with sodium and water following, floods the lumen far beyond the colon's capacity to reabsorb, causing secretory diarrhea.",
    choices: [
      { text: "chloride and water secretion", isCorrect: true },
      { text: "chloride and water reabsorption" },
      { text: "protein and fat digestion" },
      { text: "mucosal bacterial invasion" },
    ],
  },
  {
    stem: "Loss of intrinsic factor, as in autoimmune gastritis, produces a deficiency of vitamin B-twelve and the condition called:",
    topic: "Clinical Application",
    explanation:
      "Without intrinsic factor, dietary vitamin B-twelve cannot be absorbed in the ileum, and the resulting deficiency impairs red-cell production; this pernicious anemia develops slowly because the body's large B-twelve stores are depleted only gradually.",
    choices: [
      { text: "pernicious anemia", isCorrect: true },
      { text: "iron-deficiency anemia" },
      { text: "Zollinger-Ellison syndrome" },
      { text: "lactose intolerance" },
    ],
  },
  {
    stem: "Steatorrhea, the passage of pale greasy stools, is a direct sign of:",
    topic: "Clinical Application",
    explanation:
      "Steatorrhea reflects unabsorbed fat in the stool and points to a failure of fat digestion or absorption, whether from a lack of pancreatic lipase, insufficient bile salts, or mucosal disease; it is typically accompanied by deficiency of fat-soluble vitamins.",
    choices: [
      { text: "malabsorption of dietary fat", isCorrect: true },
      { text: "excess secretion of gastric acid" },
      { text: "overproduction of bile salts" },
      { text: "rapid absorption of glucose" },
    ],
  },
  {
    stem: "Which findings would you expect in a patient with fat malabsorption? Select all that apply.",
    type: "MULTI",
    topic: "Clinical Application",
    explanation:
      "Fat malabsorption produces greasy, foul-smelling stools, deficiency of the fat-soluble vitamins, weight loss despite adequate intake, and a bleeding tendency from vitamin K deficiency; it does not cause excess vitamin A absorption or a gain in muscle mass.",
    choices: [
      { text: "greasy, foul-smelling stools", isCorrect: true },
      { text: "deficiency of fat-soluble vitamins", isCorrect: true },
      { text: "weight loss despite adequate intake", isCorrect: true },
      { text: "a bleeding tendency from low vitamin K", isCorrect: true },
      { text: "excess absorption of vitamin A" },
      { text: "a marked gain in muscle mass" },
    ],
  },
];
