/**
 * PHYSIOLOGY — PRACTICE SET 1
 * Cell Physiology, Membrane Transport & Excitable Tissue
 *
 * Guyton & Hall / Ganong depth. Membrane transport and the sodium-potassium
 * pump, resting and action potentials, nerve conduction, synaptic transmission,
 * skeletal/smooth/cardiac excitation-contraction coupling, and signal
 * transduction. 100 questions.
 *
 * Options are authored at length parity — the correct answer is not the longest
 * option, so length carries no signal — and every distractor is a defensible
 * near-miss. Positions are randomized at seed time by the engine.
 */

import type { Q } from "../_lib/qbank";

export const PHYSIOLOGY_SET_1: Q[] = [
  {
    stem: "The Na+/K+-ATPase is described as electrogenic. The feature that makes it contribute directly to the membrane potential is that per cycle it moves:",
    topic: "Membrane Transport",
    explanation:
      "The pump extrudes three sodium ions for every two potassium ions imported, so each cycle nets one positive charge outward; this small direct contribution adds a few millivolts to the negative resting potential beyond its role in setting gradients.",
    choices: [
      { text: "three sodium ions out for every two potassium ions in", isCorrect: true },
      { text: "two sodium ions out for every three potassium ions in" },
      { text: "three potassium ions out for every two sodium ions in" },
      { text: "one sodium ion out for every one potassium ion in" },
      { text: "two sodium ions out for every two calcium ions in" },
    ],
  },
  {
    stem: "A cell is poisoned so that ATP is fully depleted while ion channels stay intact. Over the next many minutes the resting membrane potential will:",
    topic: "Membrane Transport",
    explanation:
      "With the pump stopped, sodium and potassium gradients run down as ions leak through channels; the potential drifts toward zero as the concentration differences dissipate. The change is gradual because the gradients are large and leak is slow, not instant.",
    choices: [
      { text: "collapse toward zero almost instantly as channels open wide" },
      { text: "drift slowly toward zero as the ionic gradients dissipate", isCorrect: true },
      { text: "become sharply more negative as potassium is retained" },
      { text: "stay fixed indefinitely because channels set the potential" },
      { text: "oscillate rhythmically between depolarized and hyperpolarized" },
    ],
  },
  {
    stem: "Secondary active transport of glucose in the intestinal epithelium is powered not by ATP directly but by the:",
    topic: "Membrane Transport",
    explanation:
      "The SGLT cotransporter uses the inward sodium electrochemical gradient, itself maintained by the basolateral pump, to drive glucose uphill; this indirect coupling is what defines secondary active transport, distinguishing it from primary pumps.",
    choices: [
      { text: "hydrolysis of ATP bound to the glucose carrier itself" },
      { text: "inward electrochemical gradient for sodium ions", isCorrect: true },
      { text: "outward electrochemical gradient for potassium ions" },
      { text: "electrical gradient produced by chloride channels" },
      { text: "osmotic gradient generated by water movement" },
    ],
  },
  {
    stem: "Which transport processes move a solute against its electrochemical gradient? Select all that apply.",
    type: "MULTI",
    topic: "Membrane Transport",
    explanation:
      "Primary active transport (the Na+/K+-ATPase), secondary active transport (Na+-glucose cotransport), and the Ca2+-ATPase all move solute uphill. Simple diffusion and facilitated diffusion through a channel only move solute down its gradient.",
    choices: [
      { text: "the sodium-potassium ATPase moving sodium outward", isCorrect: true },
      { text: "sodium-glucose cotransport moving glucose inward", isCorrect: true },
      { text: "the calcium ATPase pumping calcium out of the cytosol", isCorrect: true },
      { text: "simple diffusion of oxygen across the lipid bilayer" },
      { text: "facilitated diffusion of glucose through a GLUT carrier" },
    ],
  },
  {
    stem: "Facilitated diffusion differs from simple diffusion chiefly in that facilitated diffusion:",
    topic: "Membrane Transport",
    explanation:
      "Facilitated diffusion uses a specific carrier or channel and therefore saturates once carriers are occupied, giving a maximum rate; simple diffusion rises linearly with the gradient without a ceiling. Both are passive and need no ATP.",
    choices: [
      { text: "requires ATP hydrolysis to move solute across the membrane" },
      { text: "saturates at high concentration because carriers are limited", isCorrect: true },
      { text: "moves solute against the prevailing concentration gradient" },
      { text: "rises without limit as the concentration gradient increases" },
      { text: "depends only on the lipid solubility of the solute" },
    ],
  },
  {
    stem: "Osmotic movement of water across a cell membrane is best predicted by the effective osmolality, which counts only:",
    topic: "Membrane Transport",
    explanation:
      "Tonicity depends on solutes that cannot freely cross the membrane and therefore hold water; freely permeant solutes such as urea distribute across and exert no sustained osmotic force. So effective osmolality counts only the impermeant solutes.",
    choices: [
      { text: "every dissolved particle regardless of its permeability" },
      { text: "solutes that cannot readily cross the cell membrane", isCorrect: true },
      { text: "solutes that cross the membrane most readily of all" },
      { text: "only the sodium ions present in the solution" },
      { text: "the total number of ions but not neutral molecules" },
    ],
  },
  {
    stem: "A carrier that moves two different solutes in opposite directions across the membrane is termed a(n):",
    topic: "Membrane Transport",
    explanation:
      "An antiporter (exchanger) couples the movement of one solute in with another out, as the sodium-calcium exchanger does; a symporter moves solutes the same way, and a uniporter carries a single solute. The naming reflects direction, not energy source.",
    choices: [
      { text: "symporter moving both solutes in the same direction" },
      { text: "antiporter moving the two solutes in opposite directions", isCorrect: true },
      { text: "uniporter carrying a single solute down its gradient" },
      { text: "channel allowing free bidirectional ion movement" },
      { text: "primary pump hydrolyzing ATP for each solute" },
    ],
  },
  {
    stem: "Aquaporins increase membrane water permeability. In the renal collecting duct their insertion into the apical membrane is acutely controlled by:",
    topic: "Membrane Transport",
    explanation:
      "Antidiuretic hormone signals through cAMP to shuttle aquaporin-2 into the apical membrane, raising water permeability and concentrating the urine; withdrawal of the hormone removes the channels. Aldosterone instead governs sodium channels, not water pores.",
    choices: [
      { text: "aldosterone acting on basolateral sodium pumps" },
      { text: "antidiuretic hormone acting through cyclic AMP", isCorrect: true },
      { text: "atrial natriuretic peptide raising cyclic GMP" },
      { text: "parathyroid hormone mobilizing intracellular calcium" },
      { text: "angiotensin II constricting the efferent arteriole" },
    ],
  },
  {
    stem: "The resting membrane potential of a typical neuron sits close to the equilibrium potential for potassium mainly because at rest the membrane is:",
    topic: "Resting Membrane Potential",
    explanation:
      "At rest the membrane's permeability to potassium far exceeds that to sodium through open leak channels, so the potential lies near the potassium equilibrium value; the small sodium permeability pulls it slightly positive of that value.",
    choices: [
      { text: "far more permeable to sodium than to potassium ions" },
      { text: "far more permeable to potassium than to sodium ions", isCorrect: true },
      { text: "equally permeable to sodium and to potassium ions" },
      { text: "impermeable to potassium yet permeable to chloride" },
      { text: "permeable only to calcium through voltage-gated pores" },
    ],
  },
  {
    stem: "Using the Nernst equation at body temperature, raising extracellular potassium from 4 to 8 mmol/L shifts the potassium equilibrium potential in which direction, and with what effect on excitability?",
    topic: "Resting Membrane Potential",
    explanation:
      "Higher external potassium raises (makes less negative) the potassium equilibrium potential, depolarizing the resting membrane; modest elevation increases excitability, while severe elevation inactivates sodium channels and can render tissue unexcitable.",
    choices: [
      { text: "less negative, depolarizing the cell and altering excitability", isCorrect: true },
      { text: "more negative, hyperpolarizing the cell and reducing firing" },
      { text: "unchanged, because potassium sets no equilibrium value" },
      { text: "less negative, but with no effect on membrane excitability" },
      { text: "more negative, and increasing the tendency to fire" },
    ],
  },
  {
    stem: "The Goldman-Hodgkin-Katz equation improves on a single-ion Nernst calculation because it:",
    topic: "Resting Membrane Potential",
    explanation:
      "The GHK equation weights each permeant ion by its relative permeability, so it predicts the actual resting potential set by potassium, sodium, and chloride together; a single Nernst value describes only one ion in isolation.",
    choices: [
      { text: "assumes the membrane is permeable to a single ion only" },
      { text: "weights several ions by their relative membrane permeabilities", isCorrect: true },
      { text: "ignores permeability and uses concentrations alone" },
      { text: "applies solely to the peak of the action potential" },
      { text: "predicts the current through one open channel" },
    ],
  },
  {
    stem: "Chloride is often near electrochemical equilibrium at rest in many neurons. A consequence is that opening chloride channels tends to:",
    topic: "Resting Membrane Potential",
    explanation:
      "Because the chloride equilibrium potential lies near rest, opening chloride channels clamps the membrane toward that value and resists depolarization, contributing to inhibition even without a large hyperpolarization.",
    choices: [
      { text: "strongly depolarize the cell toward the sodium potential" },
      { text: "stabilize the membrane near the resting potential value", isCorrect: true },
      { text: "drive a large sustained hyperpolarization every time" },
      { text: "trigger an action potential by reaching threshold" },
      { text: "have no effect on membrane potential whatsoever" },
    ],
  },
  {
    stem: "Why does the Na+/K+-ATPase contribute only a few millivolts directly to the resting potential despite being essential to it?",
    topic: "Resting Membrane Potential",
    explanation:
      "The pump's direct electrogenic effect is small because it moves relatively few net charges per second; its essential role is indirect, maintaining the concentration gradients that potassium diffusion then uses to set most of the potential.",
    choices: [
      { text: "because it moves equal charges in and out each cycle" },
      { text: "its small net charge movement mostly maintains gradients", isCorrect: true },
      { text: "because it is electrically silent and moves no net charge" },
      { text: "since it depolarizes and hyperpolarizes in equal measure" },
      { text: "as it operates only during the action potential upstroke" },
    ],
  },
  {
    stem: "During the rapid upstroke of a neuronal action potential the membrane potential approaches the sodium equilibrium potential because:",
    topic: "Action Potentials (Nerve)",
    explanation:
      "Voltage-gated sodium channels open, briefly making sodium permeability dominant, so the potential swings toward the sodium equilibrium value; it never quite reaches it because sodium channels begin to inactivate and potassium channels open.",
    choices: [
      { text: "potassium channels open and dominate the membrane" },
      { text: "sodium permeability transiently dominates the membrane", isCorrect: true },
      { text: "chloride floods inward carrying negative charge" },
      { text: "the sodium-potassium pump reverses its direction" },
      { text: "calcium channels set the peak of the spike" },
    ],
  },
  {
    stem: "The absolute refractory period of a nerve fiber is explained at the channel level by:",
    topic: "Action Potentials (Nerve)",
    explanation:
      "During the absolute refractory period voltage-gated sodium channels are inactivated and cannot reopen regardless of stimulus strength, so no second action potential can be triggered until they recover from inactivation.",
    choices: [
      { text: "voltage-gated sodium channels being in an inactivated state", isCorrect: true },
      { text: "potassium channels remaining closed after repolarization" },
      { text: "the pump having fully restored the ionic gradients" },
      { text: "chloride channels holding the membrane at threshold" },
      { text: "calcium channels being maximally open and conducting" },
    ],
  },
  {
    stem: "A drug binds voltage-gated sodium channels and slows their recovery from inactivation. On a rapidly firing axon this would most directly:",
    topic: "Action Potentials (Nerve)",
    explanation:
      "Slowing recovery from inactivation lengthens the refractory period, so the axon cannot sustain high firing rates; this use-dependent block preferentially affects rapidly firing tissue, the basis of several antiarrhythmic and anticonvulsant drugs.",
    choices: [
      { text: "shorten the refractory period and raise the firing rate" },
      { text: "lengthen the refractory period and limit rapid firing", isCorrect: true },
      { text: "abolish the resting potential between action potentials" },
      { text: "convert each spike into a sustained depolarization" },
      { text: "increase the amplitude of every action potential" },
    ],
  },
  {
    stem: "The action potential is called all-or-none. Which statements about this property are correct? Select all that apply.",
    type: "MULTI",
    topic: "Action Potentials (Nerve)",
    explanation:
      "Once threshold is reached the spike fires with a fixed amplitude independent of stimulus strength, and stronger stimuli are encoded by higher firing frequency rather than larger spikes. A subthreshold stimulus produces only a decrementing local potential, not a spike.",
    choices: [
      { text: "above threshold the amplitude is independent of stimulus size", isCorrect: true },
      { text: "stimulus strength is encoded as the frequency of firing", isCorrect: true },
      { text: "a subthreshold stimulus gives only a local graded response", isCorrect: true },
      { text: "larger stimuli produce proportionally larger spikes" },
      { text: "the spike amplitude falls steadily as it travels" },
    ],
  },
  {
    stem: "After the peak of the spike, the membrane repolarizes and briefly undershoots the resting level. This afterhyperpolarization occurs because:",
    topic: "Action Potentials (Nerve)",
    explanation:
      "Voltage-gated potassium channels are slow to close, so potassium permeability remains elevated after sodium channels have shut, driving the potential transiently below rest toward the potassium equilibrium value before returning.",
    choices: [
      { text: "sodium channels remain open past the point of repolarization" },
      { text: "potassium channels stay open after sodium channels close", isCorrect: true },
      { text: "the pump abruptly stops and gradients collapse" },
      { text: "chloride channels open and clamp the membrane low" },
      { text: "calcium entry prolongs the depolarized plateau" },
    ],
  },
  {
    stem: "Threshold for an action potential is best defined as the membrane potential at which:",
    topic: "Action Potentials (Nerve)",
    explanation:
      "Threshold is the point where the inward sodium current just exceeds the outward potassium (and leak) current, so depolarization becomes self-regenerating; below it, outward currents restore rest, and at it the positive feedback of sodium entry takes over.",
    choices: [
      { text: "the sodium-potassium pump switches off completely" },
      { text: "inward sodium current first exceeds outward potassium current", isCorrect: true },
      { text: "outward potassium current first exceeds inward sodium current" },
      { text: "all voltage-gated channels are simultaneously inactivated" },
      { text: "the resting potential equals the chloride equilibrium value" },
    ],
  },
  {
    stem: "Saltatory conduction increases the speed of impulse propagation along myelinated axons because the action potential:",
    topic: "Nerve Conduction",
    explanation:
      "Myelin restricts regeneration of the spike to the nodes of Ranvier, where sodium channels cluster, so the impulse jumps node to node; the internodal segments conduct passively and quickly, greatly raising conduction velocity.",
    choices: [
      { text: "regenerates continuously along the entire internodal length" },
      { text: "regenerates only at the nodes and jumps between them", isCorrect: true },
      { text: "travels backward and forward to reinforce its strength" },
      { text: "depends on calcium entry at each point of the axon" },
      { text: "moves faster because myelin adds new sodium channels" },
    ],
  },
  {
    stem: "Two unmyelinated axons differ only in diameter. The larger-diameter axon conducts faster because increased diameter:",
    topic: "Nerve Conduction",
    explanation:
      "A larger diameter lowers the internal (axial) resistance to current flow, so local currents spread farther and depolarize the next region sooner, raising conduction velocity even without myelin.",
    choices: [
      { text: "raises the internal resistance to longitudinal current flow" },
      { text: "lowers the internal resistance to longitudinal current flow", isCorrect: true },
      { text: "increases the membrane capacitance and slows charging" },
      { text: "adds nodes of Ranvier along the length of the fiber" },
      { text: "shifts the threshold to a much more negative value" },
    ],
  },
  {
    stem: "Demyelination, as in multiple sclerosis, slows or blocks conduction primarily because loss of myelin:",
    topic: "Nerve Conduction",
    explanation:
      "Stripping myelin increases current leak and capacitance across the internode, so the local current dissipates before reaching the next node and may fail to bring it to threshold, slowing or blocking saltatory conduction.",
    choices: [
      { text: "lets current leak across the internode, failing to reach the next node", isCorrect: true },
      { text: "removes sodium channels from the nodes of Ranvier themselves" },
      { text: "raises the resting potential above the firing threshold" },
      { text: "permanently inactivates potassium channels at each node" },
      { text: "reverses the direction in which the impulse travels" },
    ],
  },
  {
    stem: "Nerve fibers are classified by conduction velocity. Which fiber types are correctly paired with their function? Select all that apply.",
    type: "MULTI",
    topic: "Nerve Conduction",
    explanation:
      "Large myelinated A-alpha fibers carry proprioception and motor output; A-delta fibers carry fast, sharp pain and temperature; unmyelinated C fibers carry slow, dull pain and postganglionic autonomic traffic. B fibers are preganglionic autonomic, not primary motor to muscle.",
    choices: [
      { text: "A-alpha fibers carry motor output and proprioception", isCorrect: true },
      { text: "A-delta fibers carry fast sharp pain and temperature", isCorrect: true },
      { text: "C fibers carry slow dull pain and are unmyelinated", isCorrect: true },
      { text: "A-delta fibers are the largest and fastest of all fibers" },
      { text: "C fibers are heavily myelinated and conduct fastest" },
    ],
  },
  {
    stem: "Local anesthetics preferentially block small unmyelinated pain fibers before large motor fibers in part because small fibers:",
    topic: "Nerve Conduction",
    explanation:
      "Small, high-frequency pain fibers are blocked more readily by use-dependent sodium-channel blockers and have shorter internodal spacing, so a given length of anesthetic overlaps enough nodes to block them before large motor fibers.",
    choices: [
      { text: "possess far more myelin that concentrates the drug" },
      { text: "are blocked more easily by use-dependent channel binding", isCorrect: true },
      { text: "have the fastest conduction velocities of all fibers" },
      { text: "lack voltage-gated sodium channels along their length" },
      { text: "are protected from the drug by a thick connective sheath" },
    ],
  },
  {
    stem: "The strength-duration relationship of a nerve describes that a weaker stimulus can still excite the fiber if it:",
    topic: "Nerve Conduction",
    explanation:
      "Excitation depends on delivering enough charge, so a weaker current can reach threshold if applied for a longer time; rheobase is the minimum intensity for a long pulse, and chronaxie is the time needed at twice rheobase.",
    choices: [
      { text: "is delivered for a much shorter period of time" },
      { text: "is delivered for a longer period of time", isCorrect: true },
      { text: "is applied only at the peak of the last spike" },
      { text: "hyperpolarizes the membrane before the stimulus" },
      { text: "is paired with a simultaneous potassium block" },
    ],
  },
  {
    stem: "A clinical nerve conduction study finds a markedly reduced conduction velocity with preserved amplitude. This pattern most suggests:",
    topic: "Nerve Conduction",
    explanation:
      "Slowed velocity with relatively preserved response amplitude points to a demyelinating process, which impairs saltatory conduction speed; axonal loss instead reduces amplitude because fewer fibers conduct at all.",
    choices: [
      { text: "axonal loss with fewer functioning fibers overall" },
      { text: "a demyelinating process impairing saltatory conduction", isCorrect: true },
      { text: "a defect confined to the neuromuscular junction" },
      { text: "a pure disorder of muscle fiber contraction" },
      { text: "complete transection of the peripheral nerve trunk" },
    ],
  },
  {
    stem: "At the neuromuscular junction the arriving action potential triggers acetylcholine release by opening which channels in the presynaptic terminal?",
    topic: "Synaptic Transmission",
    explanation:
      "Depolarization opens voltage-gated calcium channels in the terminal; the resulting calcium influx triggers fusion of acetylcholine vesicles with the membrane. Sodium entry drives the spike, but calcium entry is the direct trigger for release.",
    choices: [
      { text: "voltage-gated sodium channels in the nerve terminal" },
      { text: "voltage-gated calcium channels in the nerve terminal", isCorrect: true },
      { text: "voltage-gated potassium channels in the nerve terminal" },
      { text: "ligand-gated chloride channels in the nerve terminal" },
      { text: "mechanically gated cation channels in the terminal" },
    ],
  },
  {
    stem: "The end-plate potential at the neuromuscular junction is normally suprathreshold, providing a safety factor. It is produced when acetylcholine opens receptors that are:",
    topic: "Synaptic Transmission",
    explanation:
      "Nicotinic receptors at the end plate are ligand-gated cation channels permeable to both sodium and potassium; net sodium entry depolarizes the end plate well past threshold, ensuring reliable one-to-one transmission.",
    choices: [
      { text: "G-protein-coupled receptors raising intracellular cAMP" },
      { text: "ligand-gated cation channels permeable to sodium and potassium", isCorrect: true },
      { text: "ligand-gated chloride channels producing hyperpolarization" },
      { text: "voltage-gated calcium channels admitting calcium ions" },
      { text: "receptor tyrosine kinases triggering phosphorylation" },
    ],
  },
  {
    stem: "Myasthenia gravis and Lambert-Eaton syndrome both weaken neuromuscular transmission but by different lesions. Which pairings are correct? Select all that apply.",
    type: "MULTI",
    topic: "Synaptic Transmission",
    explanation:
      "Myasthenia gravis is antibody-mediated loss of postsynaptic acetylcholine receptors, worsening with use; Lambert-Eaton is antibody attack on presynaptic calcium channels, reducing release and often improving briefly with repeated effort. Neither is due to excess acetylcholine.",
    choices: [
      { text: "myasthenia gravis targets postsynaptic acetylcholine receptors", isCorrect: true },
      { text: "Lambert-Eaton targets presynaptic voltage-gated calcium channels", isCorrect: true },
      { text: "Lambert-Eaton strength may transiently improve with repeated use", isCorrect: true },
      { text: "myasthenia gravis is caused by excess acetylcholine release" },
      { text: "both disorders spare the neuromuscular junction entirely" },
    ],
  },
  {
    stem: "Acetylcholinesterase inhibitors improve strength in myasthenia gravis because they:",
    topic: "Synaptic Transmission",
    explanation:
      "Blocking acetylcholinesterase lets released acetylcholine linger and repeatedly bind the reduced number of receptors, raising the end-plate potential toward threshold. The drugs add no receptors; they prolong the action of each released molecule.",
    choices: [
      { text: "increase the number of postsynaptic receptors on the end plate" },
      { text: "prolong acetylcholine action by slowing its breakdown", isCorrect: true },
      { text: "block presynaptic calcium channels to limit release" },
      { text: "hyperpolarize the muscle fiber to reset its excitability" },
      { text: "replace the missing acetylcholine with a synthetic agonist" },
    ],
  },
  {
    stem: "Temporal summation at a central synapse refers to the situation in which:",
    topic: "Synaptic Transmission",
    explanation:
      "Temporal summation occurs when a single presynaptic input fires rapidly enough that successive postsynaptic potentials overlap and add before decaying; spatial summation instead combines inputs from several synapses arriving together.",
    choices: [
      { text: "several different synapses fire together at one instant" },
      { text: "one synapse fires rapidly so its potentials overlap and add", isCorrect: true },
      { text: "an inhibitory and excitatory input exactly cancel out" },
      { text: "the axon hillock is prevented from ever reaching threshold" },
      { text: "a single subthreshold input triggers a full action potential" },
    ],
  },
  {
    stem: "An inhibitory postsynaptic potential most commonly results from opening channels permeable to:",
    topic: "Synaptic Transmission",
    explanation:
      "Inhibitory transmitters such as GABA and glycine open chloride (or potassium) channels, driving the membrane toward those negative equilibrium potentials and away from threshold, reducing the chance of firing.",
    choices: [
      { text: "sodium ions moving into the postsynaptic cell" },
      { text: "chloride ions, moving the membrane away from threshold", isCorrect: true },
      { text: "calcium ions triggering transmitter release" },
      { text: "both sodium and potassium in equal measure" },
      { text: "nonselective cations depolarizing the membrane" },
    ],
  },
  {
    stem: "Botulinum toxin produces flaccid paralysis, whereas tetanus toxin produces spastic paralysis. This difference arises because botulinum toxin blocks release at:",
    topic: "Synaptic Transmission",
    explanation:
      "Botulinum toxin blocks acetylcholine release at the neuromuscular junction, preventing muscle activation (flaccid paralysis); tetanus toxin blocks inhibitory transmitter release in the spinal cord, removing inhibition and causing spasticity.",
    choices: [
      { text: "inhibitory synapses within the spinal cord interneurons" },
      { text: "the neuromuscular junction, preventing acetylcholine release", isCorrect: true },
      { text: "adrenergic terminals of the sympathetic nervous system" },
      { text: "dopaminergic synapses within the basal ganglia" },
      { text: "sensory afferent terminals in the dorsal horn" },
    ],
  },
  {
    stem: "In skeletal muscle excitation-contraction coupling, the T-tubule voltage sensor that triggers calcium release from the sarcoplasmic reticulum is the:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "The dihydropyridine receptor in the T-tubule senses depolarization and, through a direct mechanical link, opens the ryanodine receptor of the sarcoplasmic reticulum; in skeletal muscle this coupling needs no extracellular calcium entry.",
    choices: [
      { text: "dihydropyridine receptor mechanically linked to the ryanodine receptor", isCorrect: true },
      { text: "ryanodine receptor sensing voltage directly in the T-tubule" },
      { text: "sodium-calcium exchanger reversing to admit calcium" },
      { text: "sarcoendoplasmic reticulum calcium ATPase pump" },
      { text: "nicotinic acetylcholine receptor on the sarcolemma" },
    ],
  },
  {
    stem: "Skeletal muscle contraction differs from cardiac contraction in its dependence on extracellular calcium because in skeletal muscle:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "Skeletal muscle releases sufficient calcium from the sarcoplasmic reticulum through direct mechanical coupling, so it does not require calcium entry from outside; cardiac muscle depends on calcium-induced calcium release triggered by extracellular calcium.",
    choices: [
      { text: "calcium entry from outside is required to trigger release" },
      { text: "the sarcoplasmic reticulum supplies calcium without outside entry", isCorrect: true },
      { text: "contraction proceeds with no rise in cytosolic calcium" },
      { text: "calcium binds directly to myosin rather than troponin" },
      { text: "the T-tubules store all the calcium needed for contraction" },
    ],
  },
  {
    stem: "At the level of the thin filament, calcium initiates contraction by binding to troponin C, which then:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "Calcium binding to troponin C shifts tropomyosin off the myosin-binding sites on actin, exposing them so cross-bridges can form; removal of calcium reverses this and tropomyosin re-blocks the sites, ending contraction.",
    choices: [
      { text: "directly splits ATP to power the myosin power stroke" },
      { text: "moves tropomyosin to expose myosin-binding sites on actin", isCorrect: true },
      { text: "detaches myosin heads from the actin filament at once" },
      { text: "pumps itself back into the sarcoplasmic reticulum store" },
      { text: "binds myosin and bends the head to produce force" },
    ],
  },
  {
    stem: "Rigor mortis develops after death because, without ATP, myosin heads:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "ATP is required for myosin to detach from actin; when ATP is depleted the cross-bridges remain bound in the rigor state, and the muscle stiffens until proteolysis eventually breaks the filaments down.",
    choices: [
      { text: "cannot bind to the exposed actin sites at all" },
      { text: "remain bound to actin because detachment needs ATP", isCorrect: true },
      { text: "hydrolyze the last ATP to relax the muscle fully" },
      { text: "release calcium continuously back into the cytosol" },
      { text: "are pulled apart from actin by tropomyosin movement" },
    ],
  },
  {
    stem: "Order the following steps of the cross-bridge cycle correctly, beginning with a myosin head bound to ATP.",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "With ATP bound, myosin is detached; ATP hydrolysis cocks the head, which then binds actin; phosphate release drives the power stroke; ADP leaves, and a new ATP binds to release the head for the next cycle.",
    choices: [
      { text: "ATP hydrolysis cocks the head, actin binding, power stroke, release", isCorrect: true },
      { text: "power stroke, actin binding, ATP hydrolysis, head detachment" },
      { text: "actin binding, head release, ATP hydrolysis, power stroke" },
      { text: "head release, power stroke, actin binding, ATP hydrolysis" },
      { text: "ATP hydrolysis, power stroke, actin binding, head cocking" },
    ],
  },
  {
    stem: "On the skeletal muscle length-tension curve, active tension is greatest at an intermediate sarcomere length because there:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "Maximal active force occurs at the length giving optimal overlap of thick and thin filaments, so the greatest number of cross-bridges can form; at longer lengths overlap falls, and at shorter lengths filaments collide and interfere.",
    choices: [
      { text: "the filaments overlap so much that they collide and interfere" },
      { text: "thick and thin filament overlap allows the most cross-bridges", isCorrect: true },
      { text: "almost no cross-bridges can form between the filaments" },
      { text: "passive elastic tension alone accounts for the force" },
      { text: "calcium release from the reticulum is at its lowest point" },
    ],
  },
  {
    stem: "Which statements about the motor unit and its recruitment are correct? Select all that apply.",
    type: "MULTI",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "A motor unit is one motor neuron and all the fibers it innervates; fine-control muscles have small units, and the size principle recruits small, fatigue-resistant units before large, powerful ones. A motor unit does not contain fibers from several different neurons.",
    choices: [
      { text: "a motor unit is one neuron and all fibers it innervates", isCorrect: true },
      { text: "muscles needing fine control have small motor units", isCorrect: true },
      { text: "smaller, fatigue-resistant units are recruited first", isCorrect: true },
      { text: "a single motor unit is shared by several motor neurons" },
      { text: "the largest units are always recruited before small ones" },
    ],
  },
  {
    stem: "Tetanic (fused) tetanus produces greater force than a single twitch because rapid stimulation:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "When stimuli arrive faster than the muscle can relax, cytosolic calcium stays elevated and successive contractions summate into a sustained, stronger contraction; the individual twitches fuse because relaxation is not permitted between them.",
    choices: [
      { text: "recruits additional motor units with each stimulus" },
      { text: "keeps cytosolic calcium high so contractions summate", isCorrect: true },
      { text: "increases the amplitude of each individual spike" },
      { text: "lengthens each sarcomere to its optimal overlap" },
      { text: "switches the fibers from slow to fast twitch types" },
    ],
  },
  {
    stem: "Slow oxidative (type I) muscle fibers differ from fast glycolytic (type II) fibers in that type I fibers:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "Type I fibers are rich in mitochondria, myoglobin, and capillaries and rely on oxidative metabolism, giving fatigue resistance for posture and endurance; type II fibers contract faster and more forcefully but fatigue quickly using glycolysis.",
    choices: [
      { text: "contract rapidly and fatigue quickly using glycolysis" },
      { text: "resist fatigue using oxidative metabolism for endurance", isCorrect: true },
      { text: "contain little myoglobin and appear pale in color" },
      { text: "generate the greatest force for brief, powerful efforts" },
      { text: "lack mitochondria and depend on stored phosphocreatine" },
    ],
  },
  {
    stem: "In an isotonic contraction, unlike an isometric one, the muscle:",
    topic: "Skeletal Muscle Mechanics",
    explanation:
      "An isotonic contraction shortens against a constant load and thereby performs external work; an isometric contraction develops tension without a change in length, doing no external work. The distinction is whether length changes.",
    choices: [
      { text: "develops tension while its length stays the same" },
      { text: "shortens against a constant load and performs work", isCorrect: true },
      { text: "lengthens while producing no tension at all" },
      { text: "neither shortens nor develops any measurable tension" },
      { text: "changes tension continuously while length is fixed" },
    ],
  },
  {
    stem: "The force-velocity relationship of muscle predicts that the velocity of shortening is greatest when the:",
    topic: "Skeletal Muscle Mechanics",
    explanation:
      "Shortening velocity is highest against zero load and falls as load rises, reaching zero at the maximal isometric force; heavier loads slow the cross-bridge cycling, so maximum velocity occurs with no opposing load.",
    choices: [
      { text: "load equals the maximal isometric force of the muscle" },
      { text: "opposing load approaches zero for the contracting muscle", isCorrect: true },
      { text: "muscle is held at a fixed length throughout the effort" },
      { text: "stimulation frequency is at its lowest effective value" },
      { text: "sarcomere is stretched well beyond optimal overlap" },
    ],
  },
  {
    stem: "Smooth muscle contraction is triggered by calcium, but the calcium acts through a different sensor than in skeletal muscle. In smooth muscle calcium binds:",
    topic: "Smooth Muscle",
    explanation:
      "In smooth muscle calcium binds calmodulin, and the calcium-calmodulin complex activates myosin light-chain kinase, which phosphorylates myosin to enable cross-bridge cycling; troponin, the skeletal sensor, is absent from smooth muscle.",
    choices: [
      { text: "troponin C, shifting tropomyosin off the actin filament" },
      { text: "calmodulin, which then activates myosin light-chain kinase", isCorrect: true },
      { text: "the ryanodine receptor to release more stored calcium" },
      { text: "actin directly to expose the myosin-binding regions" },
      { text: "the dihydropyridine receptor within the membrane" },
    ],
  },
  {
    stem: "The latch state allows smooth muscle to maintain tone economically because in it:",
    topic: "Smooth Muscle",
    explanation:
      "In the latch state dephosphorylated cross-bridges remain attached and cycle very slowly, so sustained force is maintained with little ATP use and low calcium; this underlies the economical, long-lasting tone of vascular and visceral smooth muscle.",
    choices: [
      { text: "cross-bridges cycle rapidly to sustain high force" },
      { text: "attached cross-bridges cycle slowly, sustaining force cheaply", isCorrect: true },
      { text: "calcium must remain maximally elevated to hold tension" },
      { text: "the muscle relaxes fully between successive contractions" },
      { text: "ATP consumption rises sharply to maintain the tone" },
    ],
  },
  {
    stem: "Single-unit (visceral) smooth muscle behaves as a functional syncytium, which means that:",
    topic: "Smooth Muscle",
    explanation:
      "Gap junctions electrically couple the cells of single-unit smooth muscle so that activity spreads and they contract together, often driven by pacemaker cells; multi-unit smooth muscle instead has separately innervated, independent fibers.",
    choices: [
      { text: "gap junctions let the cells depolarize and contract together", isCorrect: true },
      { text: "each fiber is separately innervated and acts on its own" },
      { text: "the cells are electrically isolated from one another" },
      { text: "contraction requires direct nerve input to every cell" },
      { text: "pacemaker activity is entirely absent from the tissue" },
    ],
  },
  {
    stem: "Which features distinguish smooth muscle from skeletal muscle? Select all that apply.",
    type: "MULTI",
    topic: "Smooth Muscle",
    explanation:
      "Smooth muscle lacks sarcomeres and troponin, can sustain tone through the latch mechanism, and is controlled involuntarily; it also exhibits plasticity of length. It is not striated and does not depend on troponin for its calcium response.",
    choices: [
      { text: "it lacks the regular sarcomere striations of skeletal muscle", isCorrect: true },
      { text: "it uses calmodulin rather than troponin as its calcium sensor", isCorrect: true },
      { text: "it can maintain prolonged tone with little energy use", isCorrect: true },
      { text: "it is under direct voluntary control like skeletal muscle" },
      { text: "it shortens only by a fixed, non-adjustable amount" },
    ],
  },
  {
    stem: "Vascular smooth muscle relaxation by nitric oxide is mediated by a rise in the second messenger:",
    topic: "Smooth Muscle",
    explanation:
      "Nitric oxide activates soluble guanylate cyclase, raising cyclic GMP, which lowers cytosolic calcium and reduces myosin light-chain phosphorylation, relaxing the vessel; this is the basis of nitrate therapy for angina.",
    choices: [
      { text: "cyclic AMP produced by activated adenylate cyclase" },
      { text: "cyclic GMP produced by activated guanylate cyclase", isCorrect: true },
      { text: "inositol trisphosphate releasing calcium from stores" },
      { text: "diacylglycerol activating protein kinase C" },
      { text: "calcium entering through voltage-gated channels" },
    ],
  },
  {
    stem: "Calcium-induced calcium release in cardiac muscle means that the calcium which triggers contraction:",
    topic: "Cardiac Muscle Cellular Basis",
    explanation:
      "A small influx of calcium through L-type channels during the action potential triggers a much larger release from the sarcoplasmic reticulum through ryanodine receptors; this amplification links membrane excitation to cardiac contraction.",
    choices: [
      { text: "comes entirely from the sarcoplasmic reticulum stores" },
      { text: "enters through membrane channels and triggers a larger release", isCorrect: true },
      { text: "binds troponin without any release from internal stores" },
      { text: "is pumped inward by the sodium-calcium exchanger" },
      { text: "is supplied wholly by the T-tubule membrane itself" },
    ],
  },
  {
    stem: "Cardiac muscle cannot be tetanized like skeletal muscle mainly because the cardiac action potential:",
    topic: "Cardiac Muscle Cellular Basis",
    explanation:
      "The long plateau of the cardiac action potential produces a refractory period nearly as long as the contraction itself, so the muscle recovers excitability only after relaxing; this prevents summation and tetany, protecting the pump's filling.",
    choices: [
      { text: "is far briefer than the twitch it produces" },
      { text: "has a long refractory period lasting almost the whole twitch", isCorrect: true },
      { text: "lacks any refractory period between beats" },
      { text: "depends only on sodium and not on calcium currents" },
      { text: "repolarizes before the muscle begins to contract" },
    ],
  },
  {
    stem: "The plateau phase of the ventricular action potential is produced by a balance between:",
    topic: "Cardiac Muscle Cellular Basis",
    explanation:
      "During the plateau, inward calcium current through L-type channels roughly balances outward potassium current, holding the membrane depolarized; when calcium channels close and potassium current dominates, repolarization follows.",
    choices: [
      { text: "inward sodium current and inward calcium current together" },
      { text: "inward calcium current and outward potassium current", isCorrect: true },
      { text: "outward sodium current and outward chloride current" },
      { text: "inward potassium current and outward calcium current" },
      { text: "the sodium pump and the sodium-calcium exchanger" },
    ],
  },
  {
    stem: "Cardiac glycosides such as digoxin increase contractility by inhibiting the Na+/K+-ATPase, which raises intracellular calcium because:",
    topic: "Cardiac Muscle Cellular Basis",
    explanation:
      "Inhibiting the pump raises intracellular sodium, which weakens the sodium gradient the sodium-calcium exchanger uses; less calcium is extruded, so more is stored and released, strengthening contraction.",
    choices: [
      { text: "higher intracellular sodium reduces calcium extrusion by the exchanger", isCorrect: true },
      { text: "the pump normally imports calcium that now accumulates" },
      { text: "potassium accumulates and directly opens calcium channels" },
      { text: "the drug opens ryanodine receptors on the reticulum" },
      { text: "it blocks the calcium pump of the sarcoplasmic reticulum" },
    ],
  },
  {
    stem: "Which statements correctly contrast cardiac and skeletal muscle? Select all that apply.",
    type: "MULTI",
    topic: "Cardiac Muscle Cellular Basis",
    explanation:
      "Cardiac muscle is electrically coupled through gap junctions in intercalated discs, depends on extracellular calcium for calcium-induced release, and has a long refractory period preventing tetany. Unlike skeletal muscle it is not under voluntary control and is not a non-branching syncytium of independent fibers.",
    choices: [
      { text: "cardiac cells are coupled by gap junctions in intercalated discs", isCorrect: true },
      { text: "cardiac contraction depends on calcium-induced calcium release", isCorrect: true },
      { text: "cardiac muscle has a long refractory period preventing tetany", isCorrect: true },
      { text: "cardiac muscle is under direct voluntary motor control" },
      { text: "cardiac fibers are electrically isolated from one another" },
    ],
  },
  {
    stem: "A hormone binds a Gs-coupled receptor. The immediate downstream event is that the activated G-protein:",
    topic: "Signal Transduction",
    explanation:
      "A Gs-coupled receptor activates adenylate cyclase, raising cyclic AMP, which activates protein kinase A to phosphorylate target proteins; a Gi-coupled receptor would instead inhibit adenylate cyclase and lower cyclic AMP.",
    choices: [
      { text: "inhibits adenylate cyclase and lowers cyclic AMP" },
      { text: "stimulates adenylate cyclase and raises cyclic AMP", isCorrect: true },
      { text: "activates phospholipase C to make inositol trisphosphate" },
      { text: "opens a ligand-gated ion channel in the membrane" },
      { text: "phosphorylates the receptor's own tyrosine residues" },
    ],
  },
  {
    stem: "Signaling through a Gq-coupled receptor raises intracellular calcium because phospholipase C generates inositol trisphosphate, which:",
    topic: "Signal Transduction",
    explanation:
      "Inositol trisphosphate binds receptors on the endoplasmic reticulum and releases stored calcium into the cytosol, while the companion product diacylglycerol activates protein kinase C. The pathway thus couples receptor binding to a calcium signal.",
    choices: [
      { text: "activates protein kinase A at the cell membrane" },
      { text: "releases calcium from endoplasmic reticulum stores", isCorrect: true },
      { text: "opens voltage-gated calcium channels in the membrane" },
      { text: "directly phosphorylates myosin to cause contraction" },
      { text: "degrades cyclic AMP to end the hormonal signal" },
    ],
  },
  {
    stem: "Insulin and many growth factors act through receptors that, on ligand binding:",
    topic: "Signal Transduction",
    explanation:
      "Receptor tyrosine kinases dimerize and autophosphorylate on ligand binding, creating docking sites that launch cascades such as the RAS-MAP kinase and PI3-kinase pathways; they do not act through G-proteins or cyclic nucleotides directly.",
    choices: [
      { text: "activate a G-protein that stimulates adenylate cyclase" },
      { text: "dimerize and autophosphorylate their tyrosine residues", isCorrect: true },
      { text: "open an intrinsic ion channel within the receptor" },
      { text: "diffuse into the nucleus to bind DNA response elements" },
      { text: "raise cyclic GMP through membrane guanylate cyclase" },
    ],
  },
  {
    stem: "Steroid and thyroid hormones produce slower, longer-lasting effects than peptide hormones because they:",
    topic: "Signal Transduction",
    explanation:
      "Lipid-soluble steroid and thyroid hormones cross the membrane and bind intracellular receptors that act as transcription factors, changing gene expression; the need to synthesize new proteins makes the response slow in onset but sustained.",
    choices: [
      { text: "bind surface receptors and open ion channels rapidly" },
      { text: "bind intracellular receptors that alter gene transcription", isCorrect: true },
      { text: "act through cyclic AMP produced at the cell surface" },
      { text: "are degraded within seconds by membrane enzymes" },
      { text: "cannot enter cells and act only on the membrane" },
    ],
  },
  {
    stem: "Cholera toxin causes profuse secretory diarrhea by locking the Gs protein in its active state, which leads to:",
    topic: "Signal Transduction",
    explanation:
      "Cholera toxin ADP-ribosylates Gs so it cannot switch off, causing continuous adenylate cyclase activity and high cyclic AMP; in the gut this drives sustained chloride and water secretion, producing watery diarrhea.",
    choices: [
      { text: "persistent inhibition of adenylate cyclase in the gut" },
      { text: "continuous activation of adenylate cyclase and high cyclic AMP", isCorrect: true },
      { text: "uncontrolled release of calcium from internal stores" },
      { text: "permanent closure of enterocyte chloride channels" },
      { text: "blockade of the sodium-glucose cotransporter" },
    ],
  },
  {
    stem: "Down-regulation of receptors after prolonged exposure to a high hormone concentration is an example of:",
    topic: "Signal Transduction",
    explanation:
      "Sustained high hormone levels reduce receptor number or responsiveness, decreasing the target's sensitivity; this desensitization protects against overstimulation and helps explain tolerance to some sustained signals.",
    choices: [
      { text: "up-regulation increasing the tissue's future responsiveness" },
      { text: "desensitization reducing the tissue's responsiveness", isCorrect: true },
      { text: "permissiveness in which one hormone enables another" },
      { text: "synergy in which two hormones amplify each other" },
      { text: "feedback stimulation raising the hormone still further" },
    ],
  },
  {
    stem: "Which second messengers are correctly matched to their generating enzyme? Select all that apply.",
    type: "MULTI",
    topic: "Signal Transduction",
    explanation:
      "Adenylate cyclase makes cyclic AMP, guanylate cyclase makes cyclic GMP, and phospholipase C makes inositol trisphosphate and diacylglycerol. Protein kinase A is an effector activated by cyclic AMP, not a messenger, and calcium is not generated by phospholipase A2 in this scheme.",
    choices: [
      { text: "adenylate cyclase generates cyclic AMP", isCorrect: true },
      { text: "guanylate cyclase generates cyclic GMP", isCorrect: true },
      { text: "phospholipase C generates inositol trisphosphate and diacylglycerol", isCorrect: true },
      { text: "protein kinase A is itself a diffusible second messenger" },
      { text: "phospholipase A2 directly generates cytosolic calcium" },
    ],
  },
  {
    stem: "The amplification inherent in G-protein signaling arises because:",
    topic: "Signal Transduction",
    explanation:
      "One activated receptor can switch on many G-proteins, and each activated enzyme (such as adenylate cyclase) makes many second-messenger molecules, so a few hormone molecules produce a large intracellular response through cascade amplification.",
    choices: [
      { text: "each hormone molecule activates exactly one target protein" },
      { text: "one receptor activates many G-proteins and enzymes downstream", isCorrect: true },
      { text: "the signal weakens at every step of the cascade" },
      { text: "second messengers are made in a strict one-to-one ratio" },
      { text: "the receptor must be occupied continuously for any effect" },
    ],
  },
  {
    stem: "Severe hyperkalemia paradoxically renders cardiac and skeletal muscle less excitable, not more, because a sustained depolarization:",
    topic: "Membrane Potential Disorders",
    explanation:
      "Chronic depolarization from high extracellular potassium holds voltage-gated sodium channels in the inactivated state, so they cannot open to fire; the tissue becomes unexcitable despite being closer to the old threshold.",
    choices: [
      { text: "moves the membrane far below the firing threshold" },
      { text: "holds sodium channels inactivated so they cannot open", isCorrect: true },
      { text: "permanently opens all potassium channels at rest" },
      { text: "raises the sodium gradient across the membrane" },
      { text: "blocks the sodium-potassium pump reversibly" },
    ],
  },
  {
    stem: "Acute hypokalemia alters the resting potential by making it:",
    topic: "Membrane Potential Disorders",
    explanation:
      "Lowering extracellular potassium makes the potassium equilibrium potential more negative, hyperpolarizing the cell so a larger stimulus is needed to reach threshold; severe hypokalemia causes weakness and arrhythmia from this reduced excitability.",
    choices: [
      { text: "less negative, so the cell fires more readily" },
      { text: "more negative, so a larger stimulus is needed to fire", isCorrect: true },
      { text: "equal to the sodium equilibrium potential value" },
      { text: "independent of the extracellular potassium level" },
      { text: "unstable, oscillating around the threshold value" },
    ],
  },
  {
    stem: "Hypocalcemia increases neuromuscular excitability (producing tetany) because low extracellular calcium:",
    topic: "Membrane Potential Disorders",
    explanation:
      "Extracellular calcium normally stabilizes voltage-gated sodium channels, raising the threshold; when calcium falls, the channels open more easily at less depolarized potentials, so nerves and muscle fire spontaneously, causing tetany.",
    choices: [
      { text: "directly depolarizes the membrane toward threshold" },
      { text: "makes sodium channels open more easily at rest", isCorrect: true },
      { text: "blocks potassium channels and traps the cell depolarized" },
      { text: "prevents acetylcholine release at the junction" },
      { text: "raises the threshold so more stimulus is needed" },
    ],
  },
  {
    stem: "A hyperkalemic periodic paralysis mutation causes some sodium channels to fail to inactivate fully. During an attack the muscle is weak because the fibers are:",
    topic: "Membrane Potential Disorders",
    explanation:
      "Persistent sodium entry keeps the fibers depolarized, which inactivates the normal sodium channels and prevents further action potentials, so the muscle cannot be excited and is weak despite the leaky channels.",
    choices: [
      { text: "hyperpolarized far below the normal resting value" },
      { text: "chronically depolarized so their sodium channels stay inactivated", isCorrect: true },
      { text: "unable to release any calcium from the reticulum" },
      { text: "depleted of acetylcholine at the motor end plate" },
      { text: "locked in a sustained tetanic contraction" },
    ],
  },
  {
    stem: "Local anesthetics show use-dependent block, meaning they are more effective on a nerve that is:",
    topic: "Membrane Potential Disorders",
    explanation:
      "These drugs bind sodium channels best in the open and inactivated states, so a nerve firing rapidly exposes more bindable channels and is blocked more effectively; a quiescent nerve with mostly resting channels is relatively spared.",
    choices: [
      { text: "quiescent with its channels mostly in the resting state" },
      { text: "firing rapidly so more channels are open or inactivated", isCorrect: true },
      { text: "hyperpolarized well below its usual resting potential" },
      { text: "completely myelinated along its entire length" },
      { text: "bathed in a high extracellular calcium concentration" },
    ],
  },
  {
    stem: "Which electrolyte disturbances increase membrane excitability? Select all that apply.",
    type: "MULTI",
    topic: "Membrane Potential Disorders",
    explanation:
      "Hypocalcemia and hypomagnesemia lower the threshold and increase excitability, causing tetany; mild hyperkalemia brings the resting potential nearer threshold and can increase excitability initially. Severe hyperkalemia and hypercalcemia instead reduce excitability.",
    choices: [
      { text: "hypocalcemia lowering the sodium-channel threshold", isCorrect: true },
      { text: "hypomagnesemia enhancing neuromuscular excitability", isCorrect: true },
      { text: "mild hyperkalemia bringing rest closer to threshold", isCorrect: true },
      { text: "hypercalcemia stabilizing membranes and reducing firing" },
      { text: "severe hyperkalemia inactivating sodium channels" },
    ],
  },
  {
    stem: "A patient with weakness that worsens through the day and improves with rest has antibodies against a postsynaptic receptor. Repetitive nerve stimulation would be expected to show:",
    topic: "Clinical Application",
    explanation:
      "In myasthenia gravis the reduced receptor pool means each successive stimulus produces a smaller end-plate potential as acetylcholine stores dip, giving a decremental response on repetitive stimulation, matching the fatigable weakness.",
    choices: [
      { text: "an incremental rise in response amplitude with stimulation" },
      { text: "a decremental fall in response amplitude with stimulation", isCorrect: true },
      { text: "no change in amplitude across repeated stimuli" },
      { text: "a complete conduction block after the first stimulus" },
      { text: "a markedly slowed conduction velocity along the nerve" },
    ],
  },
  {
    stem: "A patient with small-cell lung cancer has proximal weakness that briefly improves after exercise, and antibodies to presynaptic calcium channels. The improvement with brief exercise reflects:",
    topic: "Clinical Application",
    explanation:
      "In Lambert-Eaton syndrome, repeated activity lets calcium accumulate in the terminal, transiently boosting acetylcholine release and strength; this post-exercise facilitation distinguishes it from the worsening seen in myasthenia gravis.",
    choices: [
      { text: "progressive loss of postsynaptic receptors during activity" },
      { text: "calcium accumulation transiently increasing transmitter release", isCorrect: true },
      { text: "a rise in acetylcholinesterase activity during exercise" },
      { text: "hyperpolarization of the muscle membrane with use" },
      { text: "recruitment of entirely new motor units by exercise" },
    ],
  },
  {
    stem: "An organophosphate insecticide poisoning inhibits acetylcholinesterase. The resulting clinical picture is dominated by:",
    topic: "Clinical Application",
    explanation:
      "Blocking acetylcholinesterase floods synapses with acetylcholine, overstimulating muscarinic and nicotinic receptors; the classic effects include salivation, lacrimation, miosis, bronchospasm, and muscle fasciculations, treated with atropine and pralidoxime.",
    choices: [
      { text: "dry mouth, dilated pupils, and reduced secretions" },
      { text: "excess secretions, small pupils, and muscle fasciculations", isCorrect: true },
      { text: "flaccid paralysis with no autonomic features at all" },
      { text: "pure central nervous system depression only" },
      { text: "isolated tachycardia without other cholinergic signs" },
    ],
  },
  {
    stem: "Multiple sclerosis produces neurological deficits that can worsen with a rise in body temperature (Uhthoff phenomenon) because in demyelinated axons, heat:",
    topic: "Clinical Application",
    explanation:
      "Higher temperature shortens the duration of the sodium current, and in demyelinated fibers with an already marginal safety factor this can tip conduction from slowed to blocked, transiently worsening symptoms until the temperature falls.",
    choices: [
      { text: "improves conduction by increasing channel opening" },
      { text: "shortens the sodium current and can block marginal conduction", isCorrect: true },
      { text: "adds new myelin to the affected internodes" },
      { text: "permanently destroys the underlying axon" },
      { text: "raises the resting potential toward threshold" },
    ],
  },
  {
    stem: "A marathon runner collapses with muscle cramps; labs show hyponatremia from excess water intake. Cramping and confusion here reflect that a low extracellular sodium:",
    topic: "Clinical Application",
    explanation:
      "Acute hyponatremia lowers the sodium gradient and draws water into cells, including neurons, causing swelling and dysfunction; the reduced driving force for sodium also blunts action-potential upstrokes, contributing to weakness and cramps.",
    choices: [
      { text: "raises the sodium gradient and speeds all firing" },
      { text: "reduces the sodium gradient and swells cells osmotically", isCorrect: true },
      { text: "has no effect on the action potential upstroke" },
      { text: "hyperpolarizes neurons and abolishes excitability" },
      { text: "selectively blocks potassium channels in muscle" },
    ],
  },
  {
    stem: "A nerve biopsy question: an axon regenerating after injury grows at roughly 1 mm per day guided by Schwann cells. Successful reinnervation of muscle depends most on:",
    topic: "Clinical Application",
    explanation:
      "Regrowing motor axons must reach and form new neuromuscular junctions before the denervated muscle atrophies irreversibly; the Schwann-cell-lined endoneurial tubes guide the axon, and timely reconnection preserves function.",
    choices: [
      { text: "rapid remyelination of the central white matter tracts" },
      { text: "the axon reaching the muscle before irreversible atrophy", isCorrect: true },
      { text: "immediate restoration of the resting membrane potential" },
      { text: "replacement of lost troponin within the muscle fibers" },
      { text: "an increase in the number of motor units in the muscle" },
    ],
  },
  {
    stem: "True or False: In skeletal muscle the amount of force can be graded both by recruiting more motor units and by increasing the firing frequency of active units.",
    type: "TRUE_FALSE",
    topic: "Skeletal Muscle Mechanics",
    explanation:
      "True. Whole-muscle force is graded by recruitment (activating more motor units, smallest first) and by rate coding (higher firing frequency summating twitches toward tetanus); together these mechanisms finely control tension.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "True or False: Because the skeletal muscle action potential is far briefer than the twitch it triggers, the fiber can be re-excited during contraction, allowing summation and tetanus.",
    type: "TRUE_FALSE",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "True. The muscle fiber's brief action potential and short refractory period end well before the mechanical twitch does, so rapid stimulation re-excites the fiber and the twitches summate into tetanus, unlike cardiac muscle.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "True or False: The resting membrane potential is generally closer to the equilibrium potential for potassium than to that for sodium.",
    type: "TRUE_FALSE",
    topic: "Resting Membrane Potential",
    explanation:
      "True. Because resting membrane permeability to potassium greatly exceeds that to sodium, the resting potential lies near the potassium equilibrium value, pulled only slightly positive by the small resting sodium permeability.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "True or False: In smooth muscle, relaxation requires dephosphorylation of myosin by myosin light-chain phosphatase.",
    type: "TRUE_FALSE",
    topic: "Smooth Muscle",
    explanation:
      "True. Smooth muscle relaxes when myosin light-chain phosphatase removes the phosphate that myosin light-chain kinase had added, halting cross-bridge cycling; the balance of kinase and phosphatase activity sets the level of tone.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "A drug blocks L-type calcium channels. Which tissue's contraction would be MOST directly impaired?",
    topic: "Cardiac Muscle Cellular Basis",
    explanation:
      "Cardiac and vascular smooth muscle depend on calcium entry through L-type channels to trigger or produce contraction, so their function is most directly reduced; skeletal muscle relies on internal calcium release and is far less affected by L-type block.",
    choices: [
      { text: "skeletal muscle, which depends on outside calcium entry" },
      { text: "cardiac muscle, which needs L-type calcium entry to contract", isCorrect: true },
      { text: "skeletal muscle at the neuromuscular junction receptor" },
      { text: "myelinated peripheral nerve conduction velocity" },
      { text: "the resting potential of an unstimulated neuron" },
    ],
  },
  {
    stem: "The safety factor of neuromuscular transmission refers to the fact that the end-plate potential is normally:",
    topic: "Synaptic Transmission",
    explanation:
      "Each nerve impulse releases far more acetylcholine than the minimum needed, so the end-plate potential comfortably exceeds threshold; this margin ensures reliable transmission and is what fails as receptors are lost in myasthenia gravis.",
    choices: [
      { text: "just barely at threshold for the muscle fiber" },
      { text: "well above the threshold needed to fire the muscle fiber", isCorrect: true },
      { text: "below threshold and requiring summation to fire" },
      { text: "independent of the amount of acetylcholine released" },
      { text: "determined entirely by the number of calcium channels" },
    ],
  },
  {
    stem: "Curare (a nondepolarizing blocker) causes flaccid paralysis by acting as a:",
    topic: "Synaptic Transmission",
    explanation:
      "Curare competitively blocks nicotinic acetylcholine receptors at the end plate without activating them, so acetylcholine cannot depolarize the muscle; increasing acetylcholine with a cholinesterase inhibitor can overcome the block.",
    choices: [
      { text: "depolarizing agonist that keeps the end plate depolarized" },
      { text: "competitive antagonist at the nicotinic end-plate receptor", isCorrect: true },
      { text: "blocker of presynaptic voltage-gated calcium channels" },
      { text: "inhibitor of acetylcholinesterase in the synaptic cleft" },
      { text: "blocker of the muscle fiber's own sodium channels" },
    ],
  },
  {
    stem: "Succinylcholine, a depolarizing blocker, initially causes fasciculations and then flaccid paralysis because it:",
    topic: "Synaptic Transmission",
    explanation:
      "Succinylcholine persistently activates the end-plate receptor, first depolarizing the muscle (fasciculations) and then, because the sustained depolarization inactivates sodium channels, leaving the fiber unresponsive and flaccid.",
    choices: [
      { text: "competitively blocks the receptor without any activation" },
      { text: "persistently activates the receptor, inactivating sodium channels", isCorrect: true },
      { text: "prevents acetylcholine from ever reaching the receptor" },
      { text: "blocks calcium release from the sarcoplasmic reticulum" },
      { text: "inhibits the breakdown of acetylcholine in the cleft" },
    ],
  },
  {
    stem: "A patient's nerve is stimulated proximal and distal to a suspected lesion. Conduction block localized to the lesion with normal conduction elsewhere indicates a problem that is:",
    topic: "Nerve Conduction",
    explanation:
      "A focal conduction block with normal conduction above and below points to a localized lesion (often focal demyelination or compression) at that site, rather than a diffuse neuropathy or a widespread axonal loss.",
    choices: [
      { text: "diffuse and affecting the entire length of the nerve" },
      { text: "focal and confined to the site of the lesion", isCorrect: true },
      { text: "located at the neuromuscular junction rather than the nerve" },
      { text: "caused by a generalized disorder of muscle fibers" },
      { text: "due to a defect in the central nervous system" },
    ],
  },
  {
    stem: "Which of the following correctly describe the sodium-potassium pump's roles? Select all that apply.",
    type: "MULTI",
    topic: "Membrane Transport",
    explanation:
      "The pump maintains the low-sodium, high-potassium intracellular environment, contributes a few millivolts directly through its 3:2 electrogenic stoichiometry, and sustains the gradients that power secondary active transport. It does not consume calcium as its energy source, and it is not passive.",
    choices: [
      { text: "it maintains low intracellular sodium and high potassium", isCorrect: true },
      { text: "it adds a few millivolts through its electrogenic action", isCorrect: true },
      { text: "it powers secondary active transport by sustaining gradients", isCorrect: true },
      { text: "it moves ions passively without any energy expenditure" },
      { text: "it is driven by hydrolysis of intracellular calcium" },
    ],
  },
  {
    stem: "In the cardiac cell, the sodium-calcium exchanger normally extrudes calcium using energy stored in the:",
    topic: "Cardiac Muscle Cellular Basis",
    explanation:
      "The exchanger uses the inward sodium electrochemical gradient (maintained by the pump) to move calcium out of the cell; when intracellular sodium rises, this extrusion weakens, raising intracellular calcium and contractility.",
    choices: [
      { text: "outward potassium gradient across the membrane" },
      { text: "inward sodium electrochemical gradient across the membrane", isCorrect: true },
      { text: "hydrolysis of ATP bound to the exchanger itself" },
      { text: "calcium gradient built by the reticulum pump" },
      { text: "membrane potential set by chloride channels" },
    ],
  },
  {
    stem: "Malignant hyperthermia, triggered by certain anesthetics, results from an abnormal ryanodine receptor that causes:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "A hyperactive ryanodine receptor releases calcium uncontrollably from the sarcoplasmic reticulum, producing sustained contraction, massive heat and ATP consumption, and rising temperature; dantrolene treats it by blocking this calcium release.",
    choices: [
      { text: "failure of calcium release so the muscle cannot contract" },
      { text: "uncontrolled calcium release causing sustained contraction and heat", isCorrect: true },
      { text: "blockade of the neuromuscular junction receptors" },
      { text: "loss of the resting potential across the sarcolemma" },
      { text: "inability of myosin to bind actin during activation" },
    ],
  },
  {
    stem: "True or False: Nitric-oxide-mediated vasodilation and cholera-toxin-driven secretion both act by raising a cyclic nucleotide second messenger inside the target cell.",
    type: "TRUE_FALSE",
    topic: "Signal Transduction",
    explanation:
      "True. Nitric oxide raises cyclic GMP to relax vascular smooth muscle, and cholera toxin locks Gs on to raise cyclic AMP in enterocytes; both illustrate cyclic-nucleotide signaling, though through different cyclases and effects.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "A researcher measures that a stronger sustained stimulus makes a sensory neuron fire more frequently without changing spike height. This illustrates that stimulus intensity is encoded by:",
    topic: "Action Potentials (Nerve)",
    explanation:
      "Because action potentials are all-or-none, intensity cannot be carried by amplitude; instead a stronger stimulus raises the firing frequency (frequency coding), and often recruits more receptors, conveying how strong the stimulus is.",
    choices: [
      { text: "the amplitude of each individual action potential" },
      { text: "the frequency of action potentials the neuron fires", isCorrect: true },
      { text: "the conduction velocity along the sensory axon" },
      { text: "the duration of the absolute refractory period" },
      { text: "the resting membrane potential between spikes" },
    ],
  },
  {
    stem: "The equilibrium potential of an ion, as given by the Nernst equation, is the membrane voltage at which:",
    topic: "Resting Membrane Potential",
    explanation:
      "At the equilibrium potential the electrical force on an ion exactly opposes its concentration force, so there is no net flux of that ion; the Nernst equation computes this voltage from the ion's concentration ratio.",
    choices: [
      { text: "the ion moves inward as fast as it possibly can" },
      { text: "the electrical and chemical forces on the ion balance", isCorrect: true },
      { text: "the ion is entirely excluded from crossing the membrane" },
      { text: "all ion channels for that species are fully closed" },
      { text: "the membrane is depolarized to its peak overshoot" },
    ],
  },
  {
    stem: "A voltage-clamp experiment holds the membrane at a fixed depolarized voltage. The sodium current rises and then falls despite the maintained voltage because sodium channels:",
    topic: "Action Potentials (Nerve)",
    explanation:
      "Under sustained depolarization sodium channels first activate and then inactivate through a separate gate, so the current is transient; potassium channels, lacking fast inactivation, give a sustained current under the same clamp.",
    choices: [
      { text: "close their activation gate as the voltage is held" },
      { text: "inactivate through a separate gate despite the held voltage", isCorrect: true },
      { text: "run out of sodium ions to conduct across the membrane" },
      { text: "are converted into potassium-selective channels" },
      { text: "depend on the pump, which stops during the clamp" },
    ],
  },
  {
    stem: "Compared with a fast-twitch glycolytic fiber, a slow-twitch oxidative fiber has a lower activity of which enzyme system, matching its metabolic profile?",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "Slow oxidative fibers rely on mitochondrial oxidative enzymes and have relatively low myosin ATPase and glycolytic capacity, giving slower, sustained, fatigue-resistant contractions; fast glycolytic fibers show the opposite pattern.",
    choices: [
      { text: "mitochondrial oxidative phosphorylation enzymes" },
      { text: "fast myosin ATPase and glycolytic enzymes", isCorrect: true },
      { text: "capillary density surrounding the fiber" },
      { text: "myoglobin content within the cytoplasm" },
      { text: "the sarcoplasmic reticulum calcium pump" },
    ],
  },
  {
    stem: "Presynaptic inhibition differs from postsynaptic inhibition in that presynaptic inhibition:",
    topic: "Synaptic Transmission",
    explanation:
      "Presynaptic inhibition reduces transmitter release from a specific input, selectively dampening that pathway without changing the postsynaptic cell's overall excitability, unlike postsynaptic inhibition, which hyperpolarizes the whole cell.",
    choices: [
      { text: "hyperpolarizes the entire postsynaptic cell membrane" },
      { text: "reduces transmitter release from one specific input", isCorrect: true },
      { text: "opens chloride channels across the postsynaptic membrane" },
      { text: "raises the threshold of the postsynaptic axon hillock" },
      { text: "blocks the postsynaptic receptors competitively" },
    ],
  },
  {
    stem: "Gap junctions permit direct cell-to-cell communication and are functionally important in which tissues? Select all that apply.",
    type: "MULTI",
    topic: "Cardiac Muscle Cellular Basis",
    explanation:
      "Gap junctions electrically couple cardiac muscle (through intercalated discs) and single-unit smooth muscle, letting them act as syncytia, and they also connect many neurons and glia. Skeletal muscle fibers are not coupled by gap junctions, and mature red cells have none.",
    choices: [
      { text: "cardiac muscle, through the intercalated discs", isCorrect: true },
      { text: "single-unit visceral smooth muscle", isCorrect: true },
      { text: "many neurons and glial cells in the nervous system", isCorrect: true },
      { text: "skeletal muscle fibers, which are electrically coupled" },
      { text: "mature circulating red blood cells" },
    ],
  },
  {
    stem: "The chief reason the action potential propagates in one direction along an axon under physiological conditions is that:",
    topic: "Nerve Conduction",
    explanation:
      "The region just behind the advancing spike is refractory because its sodium channels are inactivated, so the impulse can only excite the region ahead; this enforces one-way conduction from the point of initiation.",
    choices: [
      { text: "the membrane ahead of the spike is permanently refractory" },
      { text: "the region behind the spike is refractory and cannot re-fire", isCorrect: true },
      { text: "myelin is present on only one side of the axon" },
      { text: "the pump drives the impulse forward directly" },
      { text: "potassium channels open only in the forward direction" },
    ],
  },
  {
    stem: "A cell swells when placed in a solution that is:",
    topic: "Membrane Transport",
    explanation:
      "A hypotonic solution has a lower effective osmolality than the cell, so water moves inward and the cell swells; an isotonic solution causes no net movement, and a hypertonic one causes shrinkage.",
    choices: [
      { text: "hypertonic relative to the cytosol of the cell" },
      { text: "hypotonic relative to the cytosol of the cell", isCorrect: true },
      { text: "isotonic and matched to the cell interior" },
      { text: "identical in composition to the cytosol" },
      { text: "saturated with a freely permeant solute" },
    ],
  },
  {
    stem: "The maximal velocity of shortening of a muscle fiber is set primarily by:",
    topic: "Skeletal Muscle Mechanics",
    explanation:
      "Maximum shortening velocity reflects the intrinsic rate of cross-bridge cycling, which depends on the myosin isoform's ATPase activity; fast fibers with high-ATPase myosin shorten faster than slow fibers, independent of load.",
    choices: [
      { text: "the number of motor units that are recruited" },
      { text: "the ATPase rate of the muscle's myosin isoform", isCorrect: true },
      { text: "the amount of passive elastic tension present" },
      { text: "the concentration of calcium in the extracellular fluid" },
      { text: "the length of the T-tubule network" },
    ],
  },
  {
    stem: "A patient with periodic paralysis has attacks precipitated by a carbohydrate-rich meal that drives potassium into cells. This suggests the hypokalemic form, in which low extracellular potassium causes:",
    topic: "Membrane Potential Disorders",
    explanation:
      "In hypokalemic periodic paralysis, insulin-driven potassium shift lowers extracellular potassium and paradoxically depolarizes susceptible fibers via abnormal channels, inactivating sodium channels and causing weakness; potassium replacement aborts attacks.",
    choices: [
      { text: "hyperexcitability with sustained muscle contraction" },
      { text: "fiber depolarization that inactivates sodium channels", isCorrect: true },
      { text: "a large hyperpolarization that speeds firing" },
      { text: "failure of acetylcholine release at the junction" },
      { text: "uncontrolled calcium release causing rigidity" },
    ],
  },
  {
    stem: "Compared to peptide hormone signaling, the response to a receptor tyrosine kinase such as the insulin receptor characteristically:",
    topic: "Signal Transduction",
    explanation:
      "Receptor tyrosine kinase signaling launches phosphorylation cascades (RAS-MAP kinase, PI3-kinase) that regulate metabolism, growth, and gene expression over minutes to hours, a broader and often slower program than the seconds-fast ion-channel or cyclic-AMP responses.",
    choices: [
      { text: "acts within milliseconds by opening an ion channel" },
      { text: "drives phosphorylation cascades affecting metabolism and growth", isCorrect: true },
      { text: "works only by raising cyclic AMP at the membrane" },
      { text: "bypasses the receptor and enters the nucleus directly" },
      { text: "terminates instantly once the ligand is bound" },
    ],
  },
  {
    stem: "True or False: Extracellular calcium concentration influences neuronal excitability by shielding and stabilizing voltage-gated sodium channels, so hypocalcemia lowers the effective threshold for firing.",
    type: "TRUE_FALSE",
    topic: "Membrane Potential Disorders",
    explanation:
      "True. Calcium binds near sodium channels and stabilizes the closed state; when calcium falls, channels open at less depolarized voltages, effectively lowering threshold and causing the hyperexcitability and tetany of hypocalcemia.",
    choices: [
      { text: "True", isCorrect: true },
      { text: "False" },
    ],
  },
  {
    stem: "A poison that selectively blocks the sarcoplasmic reticulum calcium-ATPase (SERCA) would impair muscle function by preventing:",
    topic: "Skeletal Muscle Excitation-Contraction",
    explanation:
      "SERCA pumps calcium back into the sarcoplasmic reticulum to end contraction; blocking it keeps cytosolic calcium high, so the muscle cannot relax normally and reloading of the store for the next contraction fails.",
    choices: [
      { text: "release of calcium from the reticulum during excitation" },
      { text: "reuptake of calcium that allows the muscle to relax", isCorrect: true },
      { text: "binding of calcium to troponin on the thin filament" },
      { text: "propagation of the action potential down the T-tubule" },
      { text: "formation of cross-bridges between actin and myosin" },
    ],
  },
];
