import {
  Stethoscope,
  Pill,
  HeartPulse,
  Brain,
  Activity,
  ClipboardList,
  BookOpenCheck,
  FlaskConical,
  Calculator,
  Baby,
  Syringe,
  ListChecks,
  BookA,
  Dna,
  GraduationCap,
  Users,
  Scale,
  Compass,
  // Added for the medical & health-sciences taxonomy
  Bone,
  Bug,
  Microscope,
  Atom,
  Scissors,
  Wind,
  Droplets,
  Zap,
  Soup,
  Slice,
  MonitorDot,
  BriefcaseMedical,
  Siren,
  HandHeart,
  ShieldCheck,
  FileText,
  ClipboardCheck,
  type LucideIcon,
} from "lucide-react";

/** Maps a stored icon name to a Lucide icon, with a safe default. */
const ICONS: Record<string, LucideIcon> = {
  Stethoscope,
  Pill,
  HeartPulse,
  Brain,
  Activity,
  ClipboardList,
  BookOpenCheck,
  FlaskConical,
  Calculator,
  Baby,
  Syringe,
  ListChecks,
  BookA,
  Dna,
  GraduationCap,
  Users,
  Scale,
  Compass,
  Bone,
  Bug,
  Microscope,
  Atom,
  Scissors,
  Wind,
  Droplets,
  Zap,
  Soup,
  Slice,
  MonitorDot,
  BriefcaseMedical,
  Siren,
  HandHeart,
  ShieldCheck,
  FileText,
  ClipboardCheck,
};

export function resolveQuizIcon(name?: string | null): LucideIcon {
  if (name && ICONS[name]) return ICONS[name];
  return BookOpenCheck;
}
